### ISSUE TITLE
新功能请求：并发请求

### ISSUE THREAD

**Issue by pexcn** [zfl9/chinadns-ng#10]
记录一些能想到的一些新功能：
1. 并发请求，来自这里 https://github.com/zfl9/chinadns-ng/commit/e76868596cafcd9f2b3d6f10c7a83a2ed6cb3658#r34908475
~~2. 添加一个 `--cache-size <num>` 选项，用于设置缓存域名的个数，默认值为 0，即不设置缓存。
当有客户端请求域名时，先查找缓存中是否有该域名的结果，如果有，则不向上游请求，直接从缓存中返回；如果没有再接着当前版本的逻辑执行下去。缓存过期时间默认为 TTL 超时的时间。~~
~~3. 再添加一个 `--min-cache-ttl <seconds>` 选项，用于重新设置缓存结果的 TTL 超时时间，默认值为 0，即不设置，这时的 TTL 为默认上游返回的时间。~~

~~待定：~~
~~1. 是否应该缓存无效的结果？例如一些不存在的域名：`dig jdhfjdufjsisgovojdjdjf.com`...~~
~~2. 是否应该添加一个 `--min-ttl <seconds>` 用于设置不开启缓存时候的 TTL 超时时间？~~
~~3. 当不存在指定的 ipset 时，是不是应该直接退出程序显得比较合理？不然没有意义。~~

@zfl9

**Comment by zfl9** [comment]
1. 缓存暂时不打算做，chinadns-ng的目的只是为了替换原版chinadns。
2. 至于你说的并发请求，先考虑考虑吧，这个功能倒是问题不大。
3. 当不存在 ipset 时，我觉得不应该退出，反正随时都可以 restore ipset 集合，随时生效。
@pexcn

**Comment by zfl9** [comment]
@pexcn 
并发请求，是仅向 trustdns 连续发送多个 query 包还是 chinadns/trustdns 都连续发送多个 query 包，我感觉丢包的基本就是 trustdns（走 ss-tunnel 这样的 udp 代理隧道时）。

**Comment by pexcn** [comment]
@zfl9 我觉得应该向不在 ipset 里面的上游 DNS 并行请求就好，因为我发现的情况是仅境外 IP 的 UDP 流量被限制了。
最好可以改成可以让用户自定义并发数，`--parallel <N>`, 默认 N = 1, N = 0 时也当作 N = 1 处理这样。

**Comment by zfl9** [comment]
@pexcn 其实就是说并发请求仅针对 trustdns 上游，对吧、

**Comment by pexcn** [comment]
> @pexcn 其实就是说并发请求仅针对 trustdns 上游，对吧、

不一定，有时候 trustdns 是国内 IP, 例如在深港专线 VPS 自建纯净的 DNS

**Comment by zfl9** [comment]
我觉得没有必要这么复杂，你说的这种情况，其实关闭并发就可以了。如果你设置并发请求，其实你就在暗示，可能存在丢包。

**Comment by pexcn** [comment]
嗯嗯，这样也好

**Comment by zfl9** [comment]
缓存其实要做也不复杂，但是对于我自己的使用场景来说，它是多余的。因为我使用 dnsmasq 放在 chinadns-ng 前面，做缓存，另外一些 dhcp 配置。

**Comment by pexcn** [comment]
我只是觉得单独集成到一个软件会比较方便，忽然配置起来比较繁杂... 您的 Linux 环境下是用 dnsmasq + chinadns-ng 吗？

**Comment by zfl9** [comment]
是的，ss-tproxy 透明代理脚本。写 chinadns-ng 的本意其实就是为了替换原版 chinadns。

**Comment by cattyhouse** [comment]
Unix 哲学, 一个软件只做一件事, 而且做到极致... dnsmasq那么多年了, 它带的功能还是不要试图造轮子了

**Comment by zfl9** [comment]
这也是为什么默认参数的监听地址是 127.0.0.1，而不是 0.0.0.0，这其实有一点点暗示。

**Comment by pexcn** [comment]
噢噢好的，原来是这样...

**Comment by zfl9** [comment]
@pexcn 选项名 `-p/--repeat-times`，默认为1，也就是不进行重复发送。如果设为 3，则表示收到一个查询请求时，会连续向 trustdns 发送 3 个查询包。具体看 readme。
