### ISSUE TITLE
可否支持 tcp监听(接收客户端的tcp查询)、tcp请求(转发给tcp上游)

### ISSUE THREAD

**Issue by w311ang** [zfl9/chinadns-ng#106]
原因https://github.com/lifenjoiner/dnsforwarder/issues/7

**Comment by zfl9** [comment]
暂时没有这个计划。

**Comment by ShadowOfTheDay** [comment]
我有同样的问题，搜到了这个旧的issue。不知道OP的问题解决没。
我想OP的意思是希望chinadns-ng可以同时监听来自TCP端口的客户端请求，而不是chinadns-ng通过TCP查询上游DNS服务器。这个功能似乎和dns2tcp实现的目的不一样，因为dns2tcp还是只监听UDP的客户端DNS请求。
应用场景如下：服务器中chinadns-ng作为dnsmasq的上游，客户端shadowsocks-android连接到服务器时，远程DNS[使用TCP查询](https://linhongbo.com/posts/shadowsocks-server-on-openwrt/#远程连接到内部网络)，dnsmasq将请求转发给chinadns-ng，但后者不支持TCP查询，所以DNS请求失败，不知道我理解得对不对，实际操作的确会失败。
不知道 @zfl9 有没有什么建议，谢谢了。

**Comment by zfl9** [comment]
后面应该会加入支持，目前还没什么时间哈，望理解。

**Comment by zfl9** [comment]
> 我有同样的问题，搜到了这个旧的issue。不知道OP的问题解决没。 我想OP的意思是希望chinadns-ng可以同时监听来自TCP端口的客户端请求，而不是chinadns-ng通过TCP查询上游DNS服务器。这个功能似乎和dns2tcp实现的目的不一样，因为dns2tcp还是只监听UDP的客户端DNS请求。 应用场景如下：服务器中chinadns-ng作为dnsmasq的上游，客户端shadowsocks-android连接到服务器时，远程DNS[使用TCP查询](https://linhongbo.com/posts/shadowsocks-server-on-openwrt/#%E8%BF%9C%E7%A8%8B%E8%BF%9E%E6%8E%A5%E5%88%B0%E5%86%85%E9%83%A8%E7%BD%91%E7%BB%9C)，dnsmasq将请求转发给chinadns-ng，但后者不支持TCP查询，所以DNS请求失败，不知道我理解得对不对，实际操作的确会失败。 不知道 @zfl9 有没有什么建议，谢谢了。

---

不太清楚 shadowsocks-android 的 dns 解析流程。但我可以说下 ss-tproxy 关于 dns over tcp 的一个解决方案。

- 最前面还是 dnsmasq，接收本地网络的 dns 请求（基本都是 udp，tcp 可能也有，但非常少，可以忽略）
- chinadns-ng 作为 dnsmasq 的唯一上游（udp），给 chinadns-ng 配置 国内dns上游、可信dns上游（走代理）
- 根据 ss-tproxy.conf 配置，决定是否通过 tcp 来查询可信（国外）dns（注：无论是tcp还是udp，都会走代理）
  - 通过 udp 来查询，无需启动其他 dns 进程，chinadns-ng 的可信dns上游直接就是 8.8.8.8 等国外dns
  - 通过 tcp 来查询，则启动 dns2tcp 进程，作为 chinadns-ng 的可信dns上游，dns2tcp 上游则设为 8.8.8.8

**Comment by zfl9** [comment]
#144

**Comment by zfl9** [comment]
见 2024.03.07 版本。
