### ISSUE TITLE
ipset报错，好像是内核问题？

### ISSUE THREAD

**Issue by xiaoeyv** [zfl9/chinadns-ng#107]
[root@centos chinadns-ng]# ipset -R <chnroute.ipset
ipset v7.1: Error in line 1: Cannot open session to kernel.

**Comment by zfl9** [comment]
https://unix.stackexchange.com/questions/320738/rhel-cant-use-ipset-utility-with-error-cannot-open-session-to-kernel

https://forum.openwrt.org/t/cannot-open-session-to-kernel-when-execute-ipset-create/87175

应该是内核没有启用ipset支持。
