### ISSUE TITLE
 version 2023-02-27 on musl,  "Out of memory"

### ISSUE THREAD

**Issue by cattyhouse** [zfl9/chinadns-ng#111]
问题:

```
chinadns-ng: can't alloc memory. tag:name n:15 bytes:15 errno:12 Out of memory
```

复现步骤:

1. clone latest chinadns-ng
2. on alpine linux: `make`. note alpine uses musl as libc
3. run with **-g or -m or both** : `chinadns-ng -g gfwlist`. if run without -g or -m, no such issue.

**Comment by zfl9** [comment]
能给一下strace信息吗，我看下系统调用

**Comment by zfl9** [comment]
strace -ttv chinadns-ng 参数...

**Comment by zfl9** [comment]
你这个doas是什么程序
给strace加上-f参数

**Comment by zfl9** [comment]
见 2023.02.28 版本
