### ISSUE TITLE
clang does not support -flto-partition=none

### ISSUE THREAD

**Issue by cattyhouse** [zfl9/chinadns-ng#112]
As title says. it is suggested to remove this option from Makefile

**Comment by zfl9** [comment]
不建议使用gcc只在的编译器

**Comment by zfl9** [comment]
@cattyhouse 
我发现一个更好用的 基于musl的静态链接  交叉编译工具链，参数完全同 gcc。
https://musl.cc

用法简单的一批，他直接预先编译好了，直接curl/wget下载即可

```shell
# 查看工具链下载地址
curl https://musl.cc | grep aarch64 | grep cross

wget 对应工具链
tar xvf 解压

# 编译chinadns-ng
make CC="/path/to/bin/xx-gcc -static"
```

**Comment by zfl9** [comment]
确实不错，我刚才成功在wsl上运行了zig cc。
后面就可以直接发布二进制版本了，方便有些不能编译的用户。

> 另外makefile我也加上了clang判断，兼容gcc和clang，不用patch了。
