### ISSUE TITLE
更新2.28版本后pppoe重播之后会无法解析，需要重启

### ISSUE THREAD

**Issue by gnattu** [zfl9/chinadns-ng#113]
看到2月28日的版本修复了和musl的兼容性问题就更新了，然后发现这个版本在pppoe重播以后会一直显示“Network is unreachable", 不论是国内dns还是可信dns均会有这个提示，直到chinadns-ng被重启。

复现方法：
我使用linux的ppp（https://www.samba.org/ppp/）直接进行pppoe拨号，然后手动将这个pppoe界面重播（poff -r），chinadns就会开始变得不响应，查看日志显示对所有dns上游均是“Network is unreachable”状态，即使pppoe重播完成后，也就是直接使用dig指定其他的dns可以返回结果的时候，chinadns-ng依然会保持对上游的Network is unreachable

对于家宽来讲pppoe重播还是挺常见的，现在我只能每天定时重启chinadns-ns来避免突然间无法解析

补充说明环境：pppoe拨号和chinadns-ng是在同一台主机上，chinadnsng使用的命令行是
`-N -p 3 -b 0.0.0.0 -l 5353 -c 国内dns -t 可信dns -M -f  -r`

**Comment by zfl9** [comment]
感谢反馈，我大概知道是哪里的问题了。

**Comment by zfl9** [comment]
看下03.02版本，应该正常了。

**Comment by gnattu** [comment]
确认了 pppoe重播不会影响后续解析了
