### ISSUE TITLE
如果上游国内dns响应的既有国内IP也有国外IP

### ISSUE THREAD

**Issue by w311ang** [zfl9/chinadns-ng#115]
那chinadns是会返回可信dns结果还是就返回国内dns解析结果？按照理论来说，应该还是返回国内dns结果，因为不可能为了污染而返回国内IP

**Comment by zfl9** [comment]
以先遍历到的`A/AAAA record`为准，如果是国内IP，则接收；如果是国外ip，则拒绝。

**Comment by w311ang** [comment]
> 以先遍历到的`A/AAAA record`为准，如果是国内IP，则接收；如果是国外ip，则拒绝。

那也就是说，如果dns返回的ip格式为`国外+国内`那遍历到第一个就直接会拒绝了吗

**Comment by zfl9** [comment]
嗯

**Comment by w311ang** [comment]
暂时没有发现，就是有时候淘宝会提示一个不要用VPN访问，还有clash代理流量中出现国内域名，不确定有没有这样的原因，dig那个域名也没有发现有混用国内外IP。当时没有用chnlist，没开`--noip-as-chnip`，也可能是解析出的cname指定了像是淘宝的国际化域名，我现在都弄了试试看还有没有这种情况吧

**Comment by zfl9** [comment]
ok

**Comment by w311ang** [comment]
![Screenshot_2023-03-12-19-41-03-54_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/30381083/224542240-166b86b4-6cbe-4913-82f2-f585bdce8e70.jpg)
对于`dig.bdurl.net`这个抖音的域名就会有这样的情况

**Comment by zfl9** [comment]
![image](https://user-images.githubusercontent.com/22726048/224542385-64b28ae9-c283-4d79-b52d-e9aa1a870f9a.png)
这个域名都在chnlist里面了，启用-m chnlist.txt列表即可（这就是为什么推荐启用gfwlist+chnlist，避免单纯依赖chnroute判定）

**Comment by w311ang** [comment]
尽管我使用了chinadns-ng内的gfwlist+chnlist，但仍不能解决有类似`8.129.63.1`这样虽然ip.sb检测是国内ip但却不在chnroute内，仍会走代理的情况
如果我把chnlist放到dnsmasq，并将解析结果添加到ipset
```
server=/<chnlist内的域名>/<国内dns>
ipset=/<chnlist内的域名>/chnlist
```
那可以弥补chnroute不全的问题，但是这样做会在dnsmasq启动时炸了我路由器的内存
我看到chinadns-ng有比dnsmasq更好的效率，不知在内存处理上是否比dnsmasq更优，要是更优，还能操作ipset那就可以代替dnsmasq了

**Comment by zfl9** [comment]
内存我没有与dnsmasq对比过，我只能给你说绝对没有你想象的这么占内存，新版本已经做了足够多内存上的优化。

关于你说的这个特殊ip的问题，确实是可以进行一个优化，就是将国内dns解析的ip全部加入(运行时动态加入)chnroute

**Comment by w311ang** [comment]
我还没有尝试过给chinadns-ng配置chnlist，因为不支持添加ipset，像是有`dreamcast.hk`(哔哩哔哩会员购)这样的域名，我还是希望能够直连，而不是由国内dns解析后走代理，而给dnsmasq喂chnlist的结果就是炸内存

最后你提到的全部国内dns解析结果放入chnroute，应该是由chnlist解析的才放到chnroute吧

**Comment by zfl9** [comment]
嗯，是的，准确来说就是chnlist.txt的域名走国内上游，然后其响应的ip加入chnroute/chnroute6

等价于dnsmasq的server加ipset指令

**Comment by zfl9** [comment]
这样就能保证dns分流和ip分流完全一致，这对于透明代理确实很重要。。也能完美解决你的问题

**Comment by zfl9** [comment]
给dnsmasq上chnlist占内存还是小事，主要是太慢了。。。

**Comment by zfl9** [comment]
可以，加起来不复杂。参数就改为逗号隔开，如 -g gfw1.txt,gfw2.txt,...

**Comment by jdnt** [comment]
> 可以，加起来不复杂。参数就改为逗号隔开，如 -g gfw1.txt,gfw2.txt,...

大佬威武！请问chnlist能否也顺便加上这个机制，个别国外的网站需要解析ipv6，这样可以方便的手动加入国内dns解析里。

**Comment by zfl9** [comment]
> > 可以，加起来不复杂。参数就改为逗号隔开，如 -g gfw1.txt,gfw2.txt,...
> 
> 大佬威武！请问chnlist能否也顺便加上这个机制，个别国外的网站需要解析ipv6，这样可以方便的手动加入国内dns解析里。

什么意思，没看明白。你意思是 -m chn1.txt,chn2.txt,... 语法支持吗？还是什么。

**Comment by jdnt** [comment]
> > > 可以，加起来不复杂。参数就改为逗号隔开，如 -g gfw1.txt,gfw2.txt,...
> > 
> > 
> > 大佬威武！请问chnlist能否也顺便加上这个机制，个别国外的网站需要解析ipv6，这样可以方便的手动加入国内dns解析里。
> 
> 什么意思，没看明白。你意思是 -m chn1.txt,chn2.txt,... 语法支持吗？还是什么。

是的，语法支持就可以了。这样更新列表以后就不需要再改一次了。

**Comment by zfl9** [comment]
可以，其实我上面的意思就是 -g 和 -m 都改为支持多列表语法。。只改一个显然不够“对称” 😂

**Comment by jdnt** [comment]
> 可以，其实我上面的意思就是 -g 和 -m 都改为支持多列表语法。。只改一个显然不够“对称” 😂

感谢大佬，大佬辛苦了！

**Comment by zfl9** [comment]
见 2023.04.01 预发布版本。

**Comment by zfl9** [comment]
见最新版本
