### ISSUE TITLE
[Feature Request] 提供一种能让客户端优先使用 IPv4 的方法

### ISSUE THREAD

**Issue by pexcn** [zfl9/chinadns-ng#116]
很多操作系统默认是 IPv6 优先，但是有时候 IPv6 的网络质量不如 IPv4, 此时希望 IPv4 优先，（不禁用系统的 IPv6）同时让系统保留系统访问 IPv6 的能力。

所以希望 `no-ipv6` 能新增一个选项，以达到这样的效果：
- 当访问 IPv4 only 域名的时候，chinadns-ng 仅返回 IPv4
- 当访问 IPv6 only 域名的时候，chinadns-ng 仅返回 IPv6
- 当访问双栈域名的时候，chinadns-ng 仅返回 IPv4

**Comment by zfl9** [comment]
这里有个不可能判断的点，那就是 chinadns-ng 无法判断一个域名是否是 “双栈域名”
因为目前双栈域名的dns查询，都是分开查询的，一次是 qtype=A，一次是 qtype=AAAA
因为一个 dns query，要么是 A 查询，要么是 AAAA 查询，要么是其他type的查询
所以对于中间的dns组件，没有很好的办法来感知这两次查询是否相关联（即所谓“双栈”）

**Comment by zfl9** [comment]
https://blogs.infoblox.com/ipv6-coe/why-should-we-separate-a-and-aaaa-dns-queries/

**Comment by zfl9** [comment]
https://stackoverflow.com/questions/4082081/requesting-a-and-aaaa-records-in-single-dns-query

**Comment by zfl9** [comment]
我能想到的唯一办法就是，通过某种主动检测机制，检测一个域名是否同时查询A和AAAA（且存在answer）

这里面有几个问题需要考虑：

- 这里的“同时”，如何定义，多久间隔内算“同时”
- 如果不考虑“同时”，那就要跟踪并记录相关域名的A/AAAA query和reply，判断该域名是否为双栈域名

这里之所以要考虑 reply，是为了检测对应的域名是否真的包含 ipv4/ipv6 地址（也就是用来判断，是v4 only，还是v6 only，还是v4+v6双栈）。

**Comment by pexcn** [comment]
想了下，好像没有特别好的方法，还是先关闭这个 issue 了😅

**Comment by zfl9** [comment]
嗯，另外，根据经验，我基本上没有碰到过 v6 only 的域名（除非是 ipv6.google.com 这种），这里说的是 www.google.com 这种常规域名。所以我认为把所有 v6 过滤掉，也差不多能用（目前来说）。

**Comment by pexcn** [comment]
> 说实话，现在v6的体验是真的烂（至少对于我来说），我现在所有网络环境，第一时间就是禁用各种ipv6哈哈

大佬是不是在使用 `--no-ipv6=mc` 这选项？禁用墙内的 IPv6, 同时保留墙外的 IPv6.
透明代理的话墙外的 IPv6 应该都走了代理，效果可能不错？😄

**Comment by zfl9** [comment]
> > 说实话，现在v6的体验是真的烂（至少对于我来说），我现在所有网络环境，第一时间就是禁用各种ipv6哈哈
> 
> 大佬是不是在使用 `--no-ipv6=mc` 这选项？禁用墙内的 IPv6, 同时保留墙外的 IPv6. 透明代理的话墙外的 IPv6 应该都走了代理，效果可能不错？😄

如果代理那边的v6网络还不错，这样设置应该是最好的。

**Comment by pexcn** [comment]
> 如果代理那边的v6网络还不错，这样设置应该是最好的。

`no-ipv6=mc` 似乎不是一个好的做法。
可能是因为客户端知道自己有能力连接ipv6，而使用了 mc 这个选项就会过滤了国内的结果，chinadns-ng 就仅会返回国外的AAAA结果了。

也许可以考虑给 no-ipv6 新增一个选项 `G` 来处理这一情况，同时这个选项也整合对应了选项 `C`
```
G：若一个AAAA查询只转发给了trustdns上游，则trustdns上游的响应如果不属于chnip，则过滤
```

另外，`C` 选项的描述大佬也可以考虑更新下，现在不太好理解。。😂
```
C：若一个AAAA查询只转发给了chinadns上游，则chinadns上游的响应如果不属于chnip，则过滤
```

**Comment by zfl9** [comment]
欧克，这个版本会加上。

**Comment by zfl9** [comment]
见 2023.04.01 版本（待我review之后，会正式发布）。

**Comment by zfl9** [comment]
见最新版本
