### ISSUE TITLE
求助：如何不使用ipset，只使用域名分流功能

### ISSUE THREAD

**Issue by InspoOnU** [zfl9/chinadns-ng#117]
因为是配合Clash使用，国内转发国内DNS，国外转发Clash的Fake-IP，所以不需要ipset功能。但是ipset留空，ChinaDNS-NG好像会报错，有办法解决这个吗？

**Comment by zfl9** [comment]
你如果是使用域名分流，那就是要启用 `-g gfwlist.txt -m chnlist.txt`，除非你的这两个列表能匹配所有域名，那么有没有ipset都无所谓，因为都执行不到那个地方。

但是看你的描述，显然chinadns-ng收到了非gfwlist.txt非chnlist.txt的域名查询，所以才会走ipset判定。

我不明白你具体要做什么

**Comment by zfl9** [comment]
也就是说，当一个域名不匹配gfwlist和chnlist时，你希望chinadns-ng如何做？请告诉我这个。比如
 - 转发给国内上游和可信上游，并且不进行ipset判断，无条件采用上游的结果
 - 只转发给国内、或者只转发可信，然后不进行ipset判断，无条件采用其结果
 - 其他？

**Comment by InspoOnU** [comment]
> 也就是说，当一个域名不匹配gfwlist和chnlist时，你希望chinadns-ng如何做？请告诉我这个。比如
> 
>     * 转发给国内上游和可信上游，并且不进行ipset判断，无条件采用上游的结果
> 
>     * 只转发给国内、或者只转发可信，然后不进行ipset判断，无条件采用其结果
> 
>     * 其他？

我希望走代理的域名转发给Clash，其他都用国内DNS
chinadns-ng -b 0.0.0.0 -l 6666 -c 127.0.0.1#6053 -t 127.0.0.1#7874 -g /usr/holo/Lists/Proxy.list
黑名单模式这样配置不对吗？

**Comment by zfl9** [comment]
可以做到，但目前chinadns-ng不支持，当然你如果需要，可以给你加个功能，就是chinadns-ng只作为一个**域名分流工具**

**Comment by zfl9** [comment]
首先还是两组dns，也就是
- `-c 国内dns组`
- `-t 可信dns组`

然后使用其中一个域名列表（用于分流）
- 只提供 `-g gfw列表`，表示：此列表的域名走可信dns上游，其它域名走国内dns上游
- 只提供 `-m chn列表`，表示：此列表的域名走国内dns上游，其它域名走可信dns上游
- 当然，为了兼容之前的chinadns-ng行为，这个新模式（纯域名分流模式）需要一个选项来控制，比如-g改为-C、-m改为-T

也就是：
```shell
# gfwlist.txt中的域名，走222，其它走111
chinadns-ng -c 127.0.0.1#111 -t 127.0.0.1#222 -T gfwlist.txt

# chnlist.txt中的域名，走111，其它走222
chinadns-ng -c 127.0.0.1#111 -t 127.0.0.1#222 -C chnlist.txt

# -T和-C不可同时存在，也就是
# -- 存在-T，则使用上述1的行为
# -- 存在-C，则使用上述2的行为
# -- 都不存在，则沿用原来的chinadns-ng模式（黑白名单+ipset）
```

**Comment by InspoOnU** [comment]
> 可以做到，但目前chinadns-ng不支持，当然你如果需要，可以给你加个功能，就是chinadns-ng只作为一个**域名分流工具**

非常感谢，因为性能还有内存占用等原因，挺需要这个功能的。

**Comment by zfl9** [comment]
嗯，我也是想到，如果使用dnsmasq来实现，就会遇到性能问题（毕竟是链表遍历来匹配的）

**Comment by basncy** [comment]
> **感觉也没必要 ip_check 策略，就一个选项 `-a/--to-another` 就够了，哈哈。**
还不如叫 -a/--auto

不建议把简单的事情做复杂了. 参数已经够多了....
转国内DNS, 即黑名单模式, 该污染的还是被污染.
转可信DNS, 即白名单模式.
这些可替代品太多了, 这个项目存在的目的就是单纯的黑名单和白名单模式都不能满足未来预期.

建议添加geoip.dat 支持, 有些OS确实不支持ipset, 一直没法在各终端本地部署解决CDN问题,  除非有性能问题.

**Comment by zfl9** [comment]
了解，这个应该很简单，我待会就能提交。。

**Comment by zfl9** [comment]
https://github.com/zfl9/chinadns-ng/releases/tag/2023.03.08

**Comment by zfl9** [comment]
用法很简单
```shell
# gfwlist.txt中的域名，走222，其它走111
chinadns-ng -c 127.0.0.1#111 -t 127.0.0.1#222 -g gfwlist.txt -d chn

# chnlist.txt中的域名，走111，其它走222
chinadns-ng -c 127.0.0.1#111 -t 127.0.0.1#222 -m chnlist.txt -d gfw
```

**Comment by zfl9** [comment]
> 建议添加geoip.dat 支持, 有些OS确实不支持ipset, 一直没法在各终端本地部署解决CDN问题, 除非有性能问题.

geoip.dat 这个不好说，我目前没有想到很好的办法能够高效匹配ip(cidr)，得去研究ipset它们是怎么实现高性能匹配的。

**Comment by InspoOnU** [comment]
> https://github.com/zfl9/chinadns-ng/releases/tag/2023.03.08

可以麻烦大佬编译下Linux ARM64版吗？我自己编译的不能启动。

**Comment by zfl9** [comment]
可以了解下zig编译器

https://ziglang.org/zh/learn/overview/#zig-%E4%B8%8E-libc-%E4%B8%80%E8%B5%B7%E5%8F%91%E5%B8%83

**Comment by zfl9** [comment]
也可看看这个，看起来操作更简单
https://ariya.io/2020/06/cross-compiling-with-musl-toolchains

**Comment by InspoOnU** [comment]
> 也可看看这个，看起来操作更简单 https://ariya.io/2020/06/cross-compiling-with-musl-toolchains
> 
> 直接下载已经构建好的工具链，进行编译即可（make CC="/path/to/gcc -static"），看readme。 https://musl.cc/
> 
> 这是我用musl.cc工具链编译好的 https://github.com/zfl9/temp

功能正常，学到了，感谢大佬！

**Comment by zfl9** [comment]
现在chinadns-ng releases页面已经提供了arm/mips/x86的预编译二进制(musl静态链接)。

**Comment by InspoOnU** [comment]
> 现在chinadns-ng releases页面已经提供了arm/mips/x86的预编译二进制(musl静态链接)。

已经用上了，运行很稳定

**Comment by Smallthing** [comment]
请问
在使用
```
chinadns-ng -p 2 -N=gt -l 7913 -c 119.29.29.29#53,119.28.28.28#53 -t 127.0.0.1#1055 -g /tmp/gfwlist.txt -d chn
```
这个参数的时候，时不时的会漏一点ipv6的解析出来(确信bing.com www.bing 各种bing的域名都在gfwlist.txt里面）
是我的配置有误 还是我理解不对 还是说处理中有遗漏呢？谢谢
```
./dig @127.0.0.1 -p53 www.bing.com AAAA
;; ->>HEADER<<- opcode: QUERY; status: NOERROR; id: 31534
;; Flags: qr rd ra; QUERY: 1; ANSWER: 4; AUTHORITY: 0; ADDITIONAL: 0

;; QUESTION SECTION:
;; www.bing.com.       		IN	AAAA

;; ANSWER SECTION:
www.bing.com.       	106	IN	CNAME	www-www.bing.com.trafficmanager.net.
www-www.bing.com.trafficmanager.net. 106	IN	CNAME	www-bing-com.dual-a-0001.a-msedge.net.
www-bing-com.dual-a-0001.a-msedge.net. 395	IN	CNAME	dual-a-0001.a-msedge.net.
dual-a-0001.a-msedge.net.	700	IN	AAAA	2620:1ec:c11::200

```
