### ISSUE TITLE
chinadns-ng 崩溃的问题

### ISSUE THREAD

**Issue by pexcn** [zfl9/chinadns-ng#118]
使用 2023.03.10 版本，并且安装在 OpenWRT 21.02.5 上：

不知道是怎么触发的，在这报错之前的一分钟左右我手动重启了 miniupnpd 服务。

报错信息：
```sh
[ 6481.539725] chinadns-ng[30256]: segfault at 13426b2c ip 0000000000406bd7 sp 00007ffe2fc647b0 error 4 in chinadns-ng[401000+12000]
[ 6481.544497] Code: d6 48 89 44 24 10 4c 89 4c 24 20 eb 1d 66 0f 1f 44 00 00 41 8b 44 24 04 83 f8 ff 74 56 4c 01 f8 4d 8d 64 c5 00 4d 85 e4 74 49 <41> 8b 04 24 c1 e8 03 44 3b 74 05 00 75 db 3a 5c 05 04 75 d5 48 8b
[ 6481.588193] chinadns-ng[30257]: segfault at 38b2c2c ip 0000000000406bd7 sp 00007ffe27c4fc70 error 4 in chinadns-ng[401000+12000]
[ 6481.593033] Code: d6 48 89 44 24 10 4c 89 4c 24 20 eb 1d 66 0f 1f 44 00 00 41 8b 44 24 04 83 f8 ff 74 56 4c 01 f8 4d 8d 64 c5 00 4d 85 e4 74 49 <41> 8b 04 24 c1 e8 03 44 3b 74 05 00 75 db 3a 5c 05 04 75 d5 48 8b
```

![kernel-crash](https://user-images.githubusercontent.com/4590439/226099020-173ca5d4-702f-4136-9dfd-a6db58d123b5.png)
![微信截图_20230318180244](https://user-images.githubusercontent.com/4590439/226099022-6750b7dc-d727-45b9-b8d6-830cb17a0f03.png)

**Comment by pexcn** [comment]
似乎没有太多有价值的信息，先 close 掉了😅

**Comment by zfl9** [comment]
make 一个 DEBUG 版本的，看能否重现，感谢。

**Comment by pexcn** [comment]
> make 一个 DEBUG 版本的，看能否重现（重现了的话，把coredump文件发我）

OK, 我看下 openwrt 能不能开这个 coredump.

> 好像有看到dnsmasq提示并发数达到上限，当时并发查询数很多吗？

好像没，可能是某个客户端的 PTR 查询？刚开始我也没发现这个警告。。感谢大佬提醒😂

**Comment by zfl9** [comment]
先关了，后续有问题再reopen吧。
