### ISSUE TITLE
对 `-a/--add-tagchn-ip` 选项的优化

### ISSUE THREAD

**Issue by pexcn** [zfl9/chinadns-ng#121]
例如 ipset 里已经存在 `192.168.1.0/24`, 而 chn 域名解析得到 `192.168.1.123`.

测试了当前的逻辑，是会加入到 ipset 里的，但是因为 `192.168.1.0/24` 已经包含了 `192.168.1.123`, 就没有必要添加了，所以希望加入 ipset 前先检查 ip 已经存在于 ipset 里。

**Comment by Smallthing** [comment]
为啥我找不到--add-tagchn-ip参数

**Comment by zfl9** [comment]
等我回家再看看哈，我印象中好像测过这种情况

**Comment by zfl9** [comment]
确实存在此问题，正式版之前我这边会优化下（这样就和nft一样了 😄 ）。

**Comment by zfl9** [comment]
让我感到意外的是，我以为 ipset 会检测这种重复添加并去重，结果并没有。

使用 `ipset add chnroute $ip` 手动添加，也是可以复现你说的这种情况。

nft 倒是直接提示 `interval overlaps with an existing one`，不会重复添加。

**Comment by pexcn** [comment]
是的，要先 `ipset test chnroute $ip` 检查是否存在😅

**Comment by zfl9** [comment]
见最新版本
