### ISSUE TITLE
How to compile arm base binary file?

### ISSUE THREAD

**Issue by johnzhang2015** [zfl9/chinadns-ng#13]
I tried  to change command to make CC=arm-linux-gnueabihf-gcc, and there is no respond for it.

it only report"make: Nothing to be done for 'all'." it looks like that can not finish cross compile if the method I tried is right.

Thanks if you have time to reply!

**Comment by zfl9** [comment]
```bash
make clean
make CC=xxx-gcc
```

**Comment by johnzhang2015** [comment]
It works, thanks!

I forgot it should clean first!
