### ISSUE TITLE
chinadns-ng和mosdns有啥区别呢

### ISSUE THREAD

**Issue by jiaoting** [zfl9/chinadns-ng#133]
如题

**Comment by zfl9** [comment]
侧重点不一样，mosdns 功能多，可玩性强，但也意味着配置复杂，有一定的上手难度。

chinadns-ng 只专注于 CN 特色的 DNS 解析，特意考虑了性能优化，低 CPU 使用率，低 RAM 消耗。

上手难度有差别，chinadns-ng 只需几个命令行参数、域名列表.txt、ipset/nftset文件，没有这么多复杂配置。

新版 chinadns-ng 与 mosdns 在功能上有些重合，基本上是 mosdns 的子集（不完全是，有些功能 mosdns 没有）。

---

总结：对于大部分用户，使用 chinadns-ng 基本能满足需求，性能以及资源占用也比 mosdns 好。如果你有特殊需求，chinadns-ng 无法满足，可以折腾下 mosdns（PS：本人没有用过 mosdns 哈，不是非常了解）。
