### ISSUE TITLE
ac68u上的崩溃日志

### ISSUE THREAD

**Issue by Smallthing** [zfl9/chinadns-ng#134]
具体原因未知，观察中

···

kernel: chinadns-ng/23078: potentially unexpected fatal signal 11.
Jun 29 13:00:38 kernel: Pid: 23078, comm:          chinadns-ng
Jun 29 13:00:38 kernel: CPU: 1    Tainted: P             (2.6.36.4brcmarm #1)
Jun 29 13:00:38 kernel: PC is at 0x216dc
Jun 29 13:00:38 kernel: LR is at 0x178c0
Jun 29 13:00:38 kernel: pc : [<000216dc>]    lr : [<000178c0>]    psr: a0000010
Jun 29 13:00:38 kernel: sp : be94ea68  ip : 00000015  fp : 00000004
Jun 29 13:00:38 kernel: r10: 0000000e  r9 : 00000005  r8 : be94eb78
Jun 29 13:00:38 kernel: r7 : 00017b60  r6 : 00000003  r5 : 0000001e  r4 : 0000006b
Jun 29 13:00:38 kernel: r3 : 0000000d  r2 : 00000001  r1 : 00041a28  r0 : 00000000
Jun 29 13:00:38 kernel: Flags: NzCv  IRQs on  FIQs on  Mode USER_32  ISA ARM  Segment user
Jun 29 13:00:38 kernel: Control: 10c53c7d  Table: 9aa5004a  DAC: 00000015

···

**Comment by zfl9** [comment]
有 coredump 文件吗，chinadns 运行日志？

**Comment by Smallthing** [comment]
没 路由器上啥都没
加了日志 coredump应该是不会有

**Comment by Smallthing** [comment]
后来一直没崩溃 姑且先关闭吧
