### ISSUE TITLE
用 int 承接 ts 会导致 2038问题, 建议所有ts都用time_t 或者 long long

### ISSUE THREAD

**Issue by cissusnar** [zfl9/chinadns-ng#135]
https://github.com/zfl9/chinadns-ng/blame/33e75ed57a8dd152ab67451216384ca1b23b9d66/main.c#L167C10-L167C10

**Comment by zfl9** [comment]
感谢你的建议，编码时确实有考虑过使用 time_t 类型（由于某些原因，最终用了 int）。

后面会改为 time_t。
