### ISSUE TITLE
如何对查询结果附加(append)三方DNS记录

### ISSUE THREAD

**Issue by basncy** [zfl9/chinadns-ng#136]
旁路由上有台DNS server, 会返回NAT64和fakeip记录. 希望能将这些记录附加(apped, NOT replace)到现有查询结果里.
过滤情况(可选): opt1:仅附加到trust server的返回结果里, opt2:仅附加到gfwlist的返回结果里.

示例: nslookup harvard.edu
当前结果:
Name:   harvard.edu
Address: 151.101.66.133
Name:   harvard.edu
Address: 2a04:4e42:200::645

期待结果:
Address: 151.101.66.133
Name:   harvard.edu
Address: 1.2.3.4
Name:   harvard.edu
Address: 2a04:4e42:200::645
Name:   harvard.edu
Address: 2001:6464::102:304

**Comment by zfl9** [comment]
为何不交给 **旁路由上的 DNS Server** 去做这件事呢？

**Comment by basncy** [comment]
附加的结果作为备份, 当某些原因导致正常访问失败或过慢时, 客户端会将流量发往该备份ip.

**Comment by zfl9** [comment]
暂不考虑支持，建议在“旁路由上的那台dns-server”上执行此操作。
