### ISSUE TITLE
问一下， chinadns-ng如果接管127.0.0.1:53后会缓存dns结果吗？

### ISSUE THREAD

**Issue by Canda15** [zfl9/chinadns-ng#139]
我看了一下文档。chinadns-ng好像是做域名分流 和转发，不缓存dns结果。想确定一下。我想用chinadns-ng监听53端口做分流。后面接到smartdns上做解析。

**Comment by zfl9** [comment]
chinadns-ng 和原版 chinadns 一样，不做 dns 缓存。你可以在 上游（比如你说的smartdns）或者下游（如dnsmasq）做缓存操作。

**Comment by Canda15** [comment]
> chinadns-ng 和原版 chinadns 一样，不做 dns 缓存。你可以在 上游（比如你说的smartdns）或者下游（如dnsmasq）做缓存操作。

好的。非常感谢。被chinadns-ng文档洗脑了。感觉域名分流可能会比smartdns要快。想折腾看看
