### ISSUE TITLE
能否加个对IPv6结果的偏好开关？

### ISSUE THREAD

**Issue by PussAzuki** [zfl9/chinadns-ng#14]
逻辑如下：
只拥有 国内IPv4地址的网站 无影响
拥有 国内IPv4+任意国家的IPv6 地址的网站，增加个偏好开关，来加速或防减速访问
只拥有 国内IPv6地址的网站 无影响

也就是说逻辑是 先读取ipv4结果，如在表中，则接着读取ipv6结果，然后按开关决定是否保留ipv6结果，这样能优化在国内有CDN的网站和使用6in4的用户的体验

**Comment by zfl9** [comment]
一个 dns reply 中不会出现 ipv4/ipv6 都有的情况，现在解析 ipv4/ipv6 域名的操作都是，客户端会发送两个 dns query，一个 query_type 为 A，一个 query_type 为 AAAA。它们分别对应 ipv4 的 reply 和 ipv6 的 reply。

**Comment by zfl9** [comment]
<https://stackoverflow.com/questions/4082081/requesting-a-and-aaaa-records-in-single-dns-query>

**Comment by zfl9** [comment]
<https://blog.zivaro.com/ipv4-ipv6-dns-queries-a-aaaa>

**Comment by zfl9** [comment]
因为两个查询都是分开的，所以 chinadns-ng 无法对它们进行任何额外的检查和操作。

**Comment by PussAzuki** [comment]
啊，可能是我说明有误，我是说在国内DNS这边查询一个同时拥有国内IPv4和一个IPv6地址的网址的时候，如果 1.IPv6路由差 或者 2.是6in4得来的IPv6 也可能是 3.IPv4地址是国内CDN ，那么目前在用的逻辑就会使这特性失效，这个CDN加速需求貌似还挺常见的

**Comment by zfl9** [comment]
我还是没有明白你要表达的意思？或许可以说的更加清楚和明白。

**Comment by PussAzuki** [comment]
目前的逻辑会使一些网站得到不同程度的访问，下载减速
希望加个开关，让用户在模式这边有更多选择

**Comment by zfl9** [comment]
请把具体需求以及原因说清楚明白，否则我不知道你在说什么。

**Comment by PussAzuki** [comment]
具体需求：加个新模式，来完成先走国内IPv4 CDN的需求（此需求会自动满足 双栈优选 的需求）

原因：国内IPv6访问速度及稳定性在目前看来，仍不能与IPv4的相对敌，所以有以上需求

**Comment by zfl9** [comment]
什么叫“完成先走国内IPv4 CDN的需求”，太抽象了。

**Comment by PussAzuki** [comment]
就是在用户多次对比用ipv4/6进行访问资源，根据需求自行选择保持先走ipv6访问（如果有ipv6网址）还是只走ipv4访问 这还抽象么

**Comment by zfl9** [comment]
不知所言。

**Comment by PussAzuki** [comment]
[目前的fair模式](https://sm.ms/image/CeAMGqRQHun8lrx)
[我的需求](https://sm.ms/image/a6mT2IOWDdkgwsu)
