### ISSUE TITLE
对分流有个优化思路

### ISSUE THREAD

**Issue by Bitcion** [zfl9/chinadns-ng#142]
好像被污染的dns不会有type65（即https）记录，如果用国内dns查询，如果存在65记录就可以判定为无污染。感觉比单纯名单分流更精确一些

**Comment by zfl9** [comment]
不可行，单个 dns 查询中只允许 1 个 question，也就是说上单个 dns 查询只支持一个特定的 qtype。

就比如现在的 ipv4,ipv6 双栈，客户端也是发出两个单独 dns 查询，一个 qtype=A，一个 qtype=AAAA。

因此，对于 chinadns-ng 来说，逻辑处理单位是 **单个 query**，也就是单个 qtype。

没有非常优雅的方法（至少对我来说）来检测 哪些query 是有关联的（比如双栈的 A查询、AAAA查询）。

---

- https://stackoverflow.com/questions/55092830/how-to-perform-dns-lookup-with-multiple-questions
- https://stackoverflow.com/questions/4082081/requesting-a-and-aaaa-records-in-single-dns-query
- https://blogs.infoblox.com/ipv6-coe/why-should-we-separate-a-and-aaaa-dns-queries/
