### ISSUE TITLE
问一个关于ChinaDNS-NG 域名默认标签“智能dns”的逻辑问题

### ISSUE THREAD

**Issue by chenmhao** [zfl9/chinadns-ng#143]
“智能dns”介绍里讲：同时转发给远程和直连DNS，如果直连DNS解析结果是大陆ip，则使用直连结果，否则使用远程结果
远程DNS可以避免更多的DNS泄露，但会导致规则列表外的某些国内域名可能会走代理！
  都同时发起dns请求了，dns不就泄露了吗？应该是先远程dns，如果结果是大陆IP，再直连dns，并返回直连结果吗？

**Comment by zfl9** [comment]
你说的是 openwrt 上的 xx 插件吧。

首先，如果希望避免“dns泄露”，那么插件肯定选择 `-m chnlist.txt -d gfw` 模式，也就是你描述的：大陆域名列表走国内 DNS 解析，其他都走国外(可信) DNS 解析。这种情况下，没有 tag:none 域名，所以也不存在同时转发给国内+可信上游的情况。

总之，如果插件选择的是“避免DNS泄露”策略，那么肯定是以下两种使用模式之一：

- `-g gfwlist.txt -d chn`：gfwlist.txt列表的域名走国外DNS，其他走国内DNS
- `-m chnlist.txt -d gfw`：chnlist.txt列表的域名走国内DNS，其他走国外DNS

**Comment by chenmhao** [comment]
我现在用的是“中国列表外”代理模式，cn域名全都是远程dns结果。

**Comment by zfl9** [comment]
请把 chinadns-ng 的参数发出来，不然讨论无法继续。

**Comment by zfl9** [comment]
> “中国列表外”代理模式

这个概念不属于 chinadns-ng，属于第三方的概念，如果我们没有具体的 chinadns-ng 参数，那么讨论也无意义。

**Comment by chenmhao** [comment]
也可能是pass的问题。
谢谢。

**Comment by zfl9** [comment]
如果是 passwall 插件，那么可以先到对应的插件上提 issue，看下什么情况。

因为 chinadns-ng 的行为，完全取决于命令行参数，所以。。如果没有具体参数，那我也没法给你分析。

**Comment by chenmhao** [comment]
好的，谢谢。
