### ISSUE TITLE
可信DNS解析结果没有加入ipset的集合中，麻烦看一下是配置哪里有问题哦

### ISSUE THREAD

**Issue by zheshinicheng** [zfl9/chinadns-ng#145]
首先展示简化的ipset 集合创建参数：
gfw4, gfw6, cn, cn6 分别存放DNS解析后的gfw和chn的地址
chnroute， chnroute6 是CN IP地址块（这里省略了详细的地址块条目）。
> https://github.com/zfl9/chinadns-ng/blob/master/chnroute.ipset
![ipset](https://github.com/zfl9/chinadns-ng/assets/94763882/afb34331-c2e6-41ce-8939-bd700f08b4c5)
![ipset-list](https://github.com/zfl9/chinadns-ng/assets/94763882/a40d3344-de66-44a2-ac45-930dd4f6b6f0)

这里是chinadns-ng的命令行运行参数，233.5.5.5 是阿里云dns，192.168.1.3的53端口的查询会被转发到国外的vps主机上处理：

![chinadns-ng](https://github.com/zfl9/chinadns-ng/assets/94763882/d5aceb56-4b6a-4a64-9caa-80269653c088)

执行`dig @127.0.0.1 -p 5353 www.youtube.com`命令后，程序输出log：
![dig](https://github.com/zfl9/chinadns-ng/assets/94763882/c2daf3cc-6143-41b5-b3aa-31a73b485e29)

![log](https://github.com/zfl9/chinadns-ng/assets/94763882/4a2feeeb-ff66-4e36-aa10-91094f7812d7)
这里显然可以看到chinadns-ng过滤掉了阿里云的dns响应，但是不知道为什么没有被加入ipset集里面。我想也许是我哪里配置有问题。
我不想要gfwlist.txt基于域名的解析。。。因为我有一份[https://gfwatch.org](url)的学术论文中取到的二十多万行的匹配规则 ，由dnsmasq载入。跑在嵌入式小主机里面简直让人发疯！我想要的是在chinadns-ng向china-dns ， trust-dns发起查询时，如果采用trust-dns的解析结果，会将解析结果写入ipset gfw4中，方便我进行透明网关的策略路由。
谢谢

**Comment by zfl9** [comment]
#138

**Comment by zfl9** [comment]
另外你这里的问题是没有指定 `--chnlist-file`、`--gfwlist-file` 参数，由于没有域名列表，所以 chinadns-ng 不知道哪些域名是 tag:chn，哪些是 tag:gfw，因此你的启动参数导致的情况就是：所有域名都是 tag:none。具体请看 readme 的说明，readme 已经说的很清楚了。

除了通过 `--chnlist-file`、`--gfwlist-file` 来对域名分类（标记tag），还有一个选项那就是 `--default-tag`，具体也请看 readme。

**Comment by zfl9** [comment]
https://github.com/zfl9/chinadns-ng?tab=readme-ov-file#tagchntaggfwtagnone-%E6%98%AF%E6%8C%87%E4%BB%80%E4%B9%88

**Comment by zheshinicheng** [comment]
不好意思，忘记关闭issue了 @zfl9
