### ISSUE TITLE
群晖ds216se上运行报错protocol:12 errno:22 Invalid argument

### ISSUE THREAD

**Issue by lanqiushou** [zfl9/chinadns-ng#148]
设备：synology ds216se
CPU类型：mavell armada 370 
下载的二进制文件：wget https://github.com/zfl9/chinadns-ng/releases/download/2023.10.28/chinadns-ng-armv7l-eabihf
运行命令：
wget https://github.com/zfl9/ss-tproxy/blob/master/chnroute.txt

wget https://github.com/zfl9/ss-tproxy/blob/master/gfwlist.txt

chinadns -b 0.0.0.0 -l 65353 -t 127.0.0.1#60053 -m /etc/chinadns/chnroute.txt -g /etc/chinadns/gfwlist.txt

报错日志：

1970-01-01 08:00:00 I [main.c:388 main] local listen addr: 0.0.0.0#65353
23952127-12-16 14:21:52 I [main.c:391 main] chinadns server#1: 114.114.114.114
23964785-06-14 16:10:40 I [main.c:395 main] trustdns server#1: 127.0.0.1#60053
5019237-08-25 23:02:24 I [dnl.c:532 dnl_init] gfwlist have higher priority
1970-01-01 08:00:00 I [dnl.c:551 dnl_init] chnlist loaded:469 added:426 cost:13.824k
23421057-07-31 12:05:20 I [dnl.c:554 dnl_init] gfwlist loaded:375 added:351 cost:20.037k
23360083-11-03 17:01:52 I [dnl.c:556 dnl_init] L1 items:766 lists:538 buckets:1024 cost:4.000k
23375599-06-25 10:44:16 I [dnl.c:560 dnl_init] L2 items:11 lists:9 buckets:16 cost:0.062k
23391387-04-28 17:23:12 I [dnl.c:563 dnl_init] total memory cost (page-aligned): 40.000k
23406358-07-22 09:12:32 I [main.c:400 main] default domain name tag: none
71637402-07-24 02:44:16 E [nl.c:10 nl_sock_create] failed to create socket. protocol:12 errno:22 Invalid argument

**Comment by lanqiushou** [comment]
烦请大佬看下是什么原因呢

**Comment by zfl9** [comment]
https://github.com/zfl9/chinadns-ng/blob/de1cdc469573675b8610b66d98141665e84b92e2/ipset.c#L509-L513

可能是你的内核不支持 NETLINK_NETFILTER 协议？什么内核版本？

---

另外你的命令/参数看起来有点问题：

```bash
# 这里应该下载chnlist.txt(大陆域名列表)，chnroute.txt是ip地址段
wget https://github.com/zfl9/ss-tproxy/blob/master/chnroute.txt

# 这个没问题，gfwlist.txt是gfw域名列表
wget https://github.com/zfl9/ss-tproxy/blob/master/gfwlist.txt

# 参数 -m chnroute.txt 改为 -m chnlist.txt
chinadns -b 0.0.0.0 -l 65353 -t 127.0.0.1#60053 -m /etc/chinadns/chnroute.txt -g /etc/chinadns/gfwlist.txt
```

---

也可以改一下参数，使用“纯域名分流模式”（此模式下，没有ipset/nftset逻辑）

---

default-tag 可用于实现"纯域名分流"，也可用于实现 [gfwlist分流模式](https://github.com/zfl9/chinadns-ng?tab=readme-ov-file#chinadns-ng-%E4%B9%9F%E5%8F%AF%E7%94%A8%E4%BA%8E-gfwlist-%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86%E5%88%86%E6%B5%81)。

- 该选项的核心逻辑就是指定不匹配任何列表的域名的tag，并无特别之处。
- 通常与-g或-m选项一起使用，比如下述例子，实现了"纯域名分流"模式：
  - `-g gfwlist.txt -d chn`：gfw列表的域名走可信上游，其他走国内上游。
  - `-m chnlist.txt -d gfw`：chn列表的域名走国内上游，其他走可信上游。
- 如果想了解更多细节，建议看一下 [chinadns-ng 的核心处理流程](https://github.com/zfl9/chinadns-ng?tab=readme-ov-file#tagchntaggfwtagnone-%E6%98%AF%E6%8C%87%E4%BB%80%E4%B9%88)。

**Comment by lanqiushou** [comment]
感谢回复，内核版本如下：
root@BAFHome:/etc/chinadns# uname -a
Linux BAFHome 3.2.40 #8451 Wed Aug 17 05:12:07 CST 2016 armv7l GNU/Linux synology_armada370_216se

用chnlist也是同样的报错，用纯域名模式看起来没问题，端口能正常启动监听

**Comment by zfl9** [comment]
内核版本看起来不是很旧，盲猜是缺少了某些 内核模块、内核CONFIG。

先用纯域名分流模式吧。
