### ISSUE TITLE
chnlist.txt加入 -d gfw 之后可信上游不返回v6解析

### ISSUE THREAD

**Issue by jdnt** [zfl9/chinadns-ng#149]
`ExecStart=/root/chinadns-ng/chinadns-ng -l 53 -t 192.168.10.52#7053,192.168.10.51#7053 -g /root/chinadns-ng/gfwlist.txt,/root/chinadns-ng/gfw.txt -m /root/chinadns-ng/chnlist.txt,/root/chinadns-ng/cn.txt -d gfw -c 192.168.10.52#6053,192.168.10.51#6053 -b 0.0.0.0 -r -M -n -N g`

-d gfw（chn列表的域名走国内上游，其他走可信上游）

`# ping ipv6.test-ipv6.com
ping: ipv6.test-ipv6.com: No address associated with hostname
`

删除后解析正常

`# ping ipv6.test-ipv6.com
PING ipv6.test-ipv6.com(2400:8902:e001:24::1 (2400:8902:e001:24::1)) 56 data bytes
64 bytes from 2400:8902:e001:24::1 (2400:8902:e001:24::1): icmp_seq=2 ttl=44 time=79.8 ms
64 bytes from 2400:8902:e001:24::1 (2400:8902:e001:24::1): icmp_seq=3 ttl=44 time=79.0 ms
64 bytes from 2400:8902:e001:24::1 (2400:8902:e001:24::1): icmp_seq=4 ttl=44 time=79.0 ms
64 bytes from 2400:8902:e001:24::1 (2400:8902:e001:24::1): icmp_seq=5 ttl=44 time=79.5 ms
`

**Comment by zfl9** [comment]
参数：`-N g` 过滤了 tag:gfw 的 AAAA 解析，因为你的 `-d gfw`，所有未匹配 chnlist.txt 的域名都是 tag:gfw。

**Comment by jdnt** [comment]
最白了，感谢大佬解答，问题解决！
