### ISSUE TITLE
@fast+lto是什么后缀？怎么安装到openwrt

### ISSUE THREAD

**Issue by xllxll** [zfl9/chinadns-ng#150]
萌新问一下大佬
fast+lto是什么后缀？怎么安装到openwrt

**Comment by zfl9** [comment]
改名chinadns-ng，添加可执行权限chmod +x chinadns-ng，然后放到PATH路径下，就可以了

**Comment by zfl9** [comment]
另外，你说的这个名字不是后缀，只是文件名的一部分。目前 chinadns-ng 的预编译二进制命名规则为 chinadns-ng@目标三元组@cpu型号或微架构级别@优化级别

**Comment by xllxll** [comment]
感谢大佬的极速回复
