### ISSUE TITLE
[增强] tcp pipeline 长连接支持

### ISSUE THREAD

**Issue by wang20150419** [zfl9/chinadns-ng#151]
openwrt 系统，armv8 CPU, 基本上有300个左右的 TIME_WAIT。
同样使用TCP查询，smartdns 没有此现象。不知道是不是BUG。

root@R5S:/etc# cat openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='22.03.0-rc2'
DISTRIB_REVISION='r19374-34b6abf5a8'
DISTRIB_TARGET='rockchip/armv8'
DISTRIB_ARCH='aarch64_generic'
DISTRIB_DESCRIPTION='OpenWrt 22.03.0-rc2 r19374-34b6abf5a8'
DISTRIB_TAINTS=''
root@R5S:/etc# netstat -apn |grep TIME |wc -l
305
root@R5S:/etc# netstat -apn |grep TIME |wc -l
301

**Comment by zfl9** [comment]
这些time_wait是chinadns-ng的吗？我测试正常呀。

**Comment by zfl9** [comment]
你netstat显示一下进程名，看看time_wait的是哪个进程的。

**Comment by zfl9** [comment]
哦看错了，我以为是close_wait，原来是time_wait。。

目前是正常的，因为tcp使用的是短连接。后面可能会优化下。但目前还有其他事要做。

**Comment by wang20150419** [comment]
> 你netstat显示一下进程名，看看time_wait的是哪个进程的。

使用的最新版（2024.03.07）
trust DNS 配置：tcp://45.90.30.0#5353,tcp://9.9.9.9#9953

TIME_WAIT 的链接都是这两个地址（部分展示。另外一台 X86_64的 Linux系统，也是如此，300~400个 TIME_WAIT）：

tcp        0      0 172.16.16.125:45056     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:44648     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55256     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:55508     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:44660     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55236     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:55228     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:55468     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:45200     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55272     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:55424     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:44636     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55364     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:45160     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:44728     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:44884     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55604     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:44996     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:44680     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:44696     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:45240     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55732     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:44976     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:44920     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55672     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:55516     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:44752     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:44708     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55620     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:55704     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:45000     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:44716     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55292     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:44804     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:44900     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55184     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:55644     9.9.9.9:9953            TIME_WAIT   -
tcp        0      0 172.16.16.125:44656     45.90.30.0:5353         TIME_WAIT   -
tcp        0      0 172.16.16.125:55764     9.9.9.9:9953            TIME_WAIT   -

**Comment by zfl9** [comment]
最新dev分支已实现：
- tcp 长连接(自适应)
- pipelining queries

**Comment by zfl9** [comment]
见 2024.04.27 版本。
