### ISSUE TITLE
[Feature Request]: 希望能手动指定监听协议

### ISSUE THREAD

**Issue by BGzEroll** [zfl9/chinadns-ng#152]
openwrt的dnsmasq可能会使用tcp与chinadns-ng通讯，而造成出现大量的dnsmasq进程，希望能指定监听参数，例如指定chinadns-ng只监听udp

详情请看[discussions](https://github.com/xiaorouji/openwrt-passwall/discussions/3044)

**Comment by zfl9** [comment]
OK，过几天会有新版本发布(dns缓存，stale缓存模式，缓存预取，tag:none域名判定结果缓存等)，到时候你这个小需求也会加上。

**Comment by zfl9** [comment]
见最新版本。
