### ISSUE TITLE
请教该下哪个版本合适？

### ISSUE THREAD

**Issue by sunlewuyou** [zfl9/chinadns-ng#154]
![image](https://github.com/zfl9/chinadns-ng/assets/19728435/1bc4a1b1-f400-4531-a3cb-de245518f2c5)
最新版不知道该选哪个版本下载了，下一版可以在发布页说明一下吗？

**Comment by zfl9** [comment]
建议用v2，因为据我了解，很多linux发行版(debian)提供的预编译包都是v2了，基本不用考虑v1。
