### ISSUE TITLE
关于新版本的使用方法

### ISSUE THREAD

**Issue by wstxwd007** [zfl9/chinadns-ng#156]
首先感谢开发新版本
能否给个新版本配置文件范例，毕竟新增了许多新特性，可以的话有个wiki就更棒了
最后再次感谢开发了如此好用的dns工具

**Comment by zfl9** [comment]
过几天我抽空写个wiki，解释一些选项的用例。

**Comment by zfl9** [comment]
新增的功能在 readme 中也有一些简要说明，可以先看看 readme。

**Comment by wstxwd007** [comment]
好的，感谢

**Comment by wstxwd007** [comment]
reuse-port参数后面填disabled无法生效

**Comment by zfl9** [comment]
那个只是选项说明，不是真正的“选项value”，其实意思是，默认情况下，如果未指定 --reuse-port，则不启用此功能。

**Comment by wstxwd007** [comment]
我的意思是后面填啥参数才能开启

**Comment by zfl9** [comment]
不用参数，直接给出 `--reuse-port` 或 `-r`

**Comment by wstxwd007** [comment]
嗯，刚想到了，只要填reuse-port，后面不需要参数
感谢哈

**Comment by wstxwd007** [comment]
还要麻烦您一下
cache 65535
cache-stale 600
cache-refresh 60
verdict-cache 65535
这几个参数有什么建议的吗？

**Comment by zfl9** [comment]
help说明的格式：

- `-r, --reuse-port`：后面没有value说明的，说明是flag选项（有该选项则表示启用、否则表示禁用）
- `-b, --bind-addr <ip>`：这种value带尖括号`<>`的，表示必须提供一个选项的value
- `--hosts [path]`：这种value带方括号`[]`的，表示value可选，一般后面会说明默认值是什么。

**Comment by zfl9** [comment]
cache 是缓存容量，具体看你这边要缓存多少个，65535是上限值，也许并不需要这么大，我个人一般用 2000
cache-stale 是允许使用一个已到期的缓存，值表示最大允许过期多久的（秒），最大65535，我一般直接拉满
cache-refresh 表示，若当前查询的这个缓存的剩余TTL不足N秒，则提前后台刷新（对用户无感），这个30/60/120都行
verdict-cache 是另一种缓存，最大也是65535，这个可以稍微比 cache 大，因为存的信息较少，比如 5000

**Comment by wstxwd007** [comment]
好的，这样就明白了

**Comment by Smallthing** [comment]
cache-refresh这个，有些域名一直在120以下，这个要怎么弄呢？TTL<10? 或者在设置了stale的情况下，这个其实可以关掉？

**Comment by zfl9** [comment]
在设置了stale的情况下，这个其实可以关掉？

是的，设置了stale模式的话，refresh开不开其实没啥很大区别。

**Comment by Smallthing** [comment]
> 在设置了stale的情况下，这个其实可以关掉？
> 
> 是的，设置了stale模式的话，refresh开不开其实没啥很大区别。
> 
> > 我自己是设置为 30。

其实我设想的完美体验是，额外记录max-ttl ，比如我知道有几个域名的ttl是10秒，那么cache-refresh设置120的时候，判断max-ttl=10 10<120 ,因此不主动刷新。 但是这个需要更多的编码和cache空间和性能了（好像也不会太多）

**Comment by zfl9** [comment]
暂时先目前这样吧，你说的这个我大概能理解意思，确实需要对每个cache多几个字节存储他们的初始ttl(从upstream拿到的时候的ttl)。目前这样我使用下来其实还可以。

**Comment by zfl9** [comment]
@Smallthing 

我想了下，要不把 cache-refresh 的单位改为百分比，比如参数值 30：

原先：若当前查询的缓存的TTL不足30秒，则返回该响应的同时，自动在后台刷新缓存。
现在：若当前查询的缓存的TTL不足30%，则返回该响应的同时，自动在后台刷新缓存。

这里的百分比是指：**当前剩余TTL** / **初始TTL**。取值范围 0 ~ 90。

**Comment by windmsn** [comment]
@zfl9 昨天用chinadns-ng监听了53端口代替dnsmasq处理dns业务。
启用reuse-port与cache后，运行四个（4核）chinadns-ng进程，cache不能同步。
使用dig www.qq.com需要dig四次才命中cache
so_reuseport的策略貌似对于udp是轮询，对于tcp好像是哈希

**Comment by zfl9** [comment]
没必要启用多个进程，就目前而言，单进程性能足够满足。

**Comment by zfl9** [comment]
README 我认为已经足够详细，没必要再搞其他文档了，所以先关了。
