### ISSUE TITLE
新版本（2024.03.27）的 udp 似乎有问题

### ISSUE THREAD

**Issue by ir1ka** [zfl9/chinadns-ng#158]
问题描述我提到了 [52](https://github.com/zfl9/ipt2socks/issues/52)。
我用 `dig ip.sb @127.0.0.1 -p 60053` 测试，返回报错，而 `dig +tcp ip.sb @127.0.0.1 -p 60053` 则能成功。

**Comment by zfl9** [comment]
应该和 chinadns-ng 无关，出错（timeout）是因为代理 udp 不通。

**Comment by zfl9** [comment]
我测试过了，chinadns-ng 没问题。我先关了，去 ipt2socks 那边讨论吧。
