### ISSUE TITLE
tag 的说明和功能的例子是混淆了？

### ISSUE THREAD

**Issue by oiiooiiooiio** [zfl9/chinadns-ng#161]
### 说明是这样：
chnlist.txt域名(tag:chn域名)，转发给china组，保证大陆域名不会被解析到国外，对大陆域名cdn友好。
gfwlist.txt域名(tag:gfw域名)，转发给trust组，trust需返回未受污染的结果，比如走代理，具体方式不限。

tag:chn：只走 china 上游（单纯转发），如果启用 --add-tagchn-ip，则添加解析结果至 ipset/nftset
tag:gfw：只走 trust 上游（单纯转发），如果启用 --add-taggfw-ip，则添加解析结果至 ipset/nftset

### 例子的功能个互换了？：
通常与-g或-m选项一起使用，比如下述例子，实现了"纯域名分流"模式：
-g gfwlist.txt **-d chn**：gfw列表的域名**走可信上游**，其他走国内上游。（tag:chn：只走 china 上游？）
-m chnlist.txt -d gfw：chn列表的域名走国内上游，其他走可信上游。

chinadns-ng 也可用于 gfwlist 透明代理分流
chinadns-ng -g gfwlist.txt **-d chn** -A gfwlist,gfwlist6 （gfwlist.txt 走 china 上游？）

**Comment by zfl9** [comment]
没有，你可能没有理解对。

`-m xxx.list` 指定的域名列表，属于 tag:chn，tag:chn 只会走 china 上游
`-g xxx.list` 指定的域名列表，属于 tag:gfw，tag:gfw 只会走 trust 上游
`-d xxx` 用于指定默认的tag（未匹配任何列表的域名的tag），可用值：chn、gfw、none

**Comment by zfl9** [comment]
事实上，利用这几个简单的选项，可以实现 global、gfwlist、chnroute、回国模式 等等。

比如 ss-tproxy 中的用例：

```bash
    if is_global_mode; then
        # 全局模式（ignlist.ext的走china，其他走trust）
        sstp_pid_chinadns=$(
            chinadns-ng \
            $args \
            -m <(list_ext_domain ignlist.ext) \
            -d gfw \
            -a sstp_white,sstp_white6 \
            </dev/null &>>$chinadns_logfile &
            echo $!
        )
    elif is_gfwlist_mode; then
        # gfw模式（gfwlist.txt的走trust，其他走china）
        sstp_pid_chinadns=$(
            chinadns-ng \
            $args \
            -g gfwlist.txt,<(list_ext_domain gfwlist.ext) \
            -d chn \
            -A sstp_black,sstp_black6 \
            </dev/null &>>$chinadns_logfile &
            echo $!
        )
    else # chnroute
        sstp_pid_chinadns=$(
            chinadns-ng \
            $args \
            -m chnlist.txt,<(list_ext_domain ignlist.ext) \
            -g gfwlist.txt,<(list_ext_domain gfwlist.ext) \
            $(is_true "$chinadns_chnlist_first" && echo '-M') \
            -a sstp_white,sstp_white6 \
            -A sstp_black,sstp_black6 \
            -4 sstp_white -6 sstp_white6 \
            </dev/null &>>$chinadns_logfile &
            echo $!
        )
    fi
```
