### ISSUE TITLE
--add-tagchn-ip 选项可否设置黑名单

### ISSUE THREAD

**Issue by puteulanus** [zfl9/chinadns-ng#162]
之前在 passwall 运行的 ChinaDNS-NG 上遇到了奇怪的污染问题（参考 https://github.com/xiaorouji/openwrt-passwall/issues/3089 ），排查之后发现是国内 DNS 上游因为开了广告过滤对 chnlist 的域名返回了 0.0.0.0，导致 0.0.0.0 进入了 ipset，从而影响到了其他国内污染为 0.0.0.0 的域名的选择。

但是当时发现 ipset 里还有个 127.0.0.1，排查之后发现是百度的游帮帮加速器域名（pc.gt.baidu.com）返回的，应该是因为命中了百度所以被加进了 ipset 里，而且不能屏蔽它的解析，不然游帮帮加速会报错。

今天看到帖子 https://www.v2ex.com/t/1032883 有感，这样如果遇到国内 DNS 污染为 127.0.0.1 的域名，应该又会遇到上面那个 issue 的问题。我在文档里只找到了“接受 china 上游返回的 IP为保留地址 的解析记录”，但是似乎没有找到方法“阻止保留 IP 进入 chnroute”（除了整个关闭 --add-tagchn-ip）。

是否有必要为 --add-tagchn-ip 功能再设置一个黑名单，来阻止 0.0.0.0、127.0.0.1 这类或者特定的 IP 进入国内 IP 段的 ipset 来避免污染呢？

**Comment by zfl9** [comment]
黑名单应该不至于，我觉得可以在 add-tagxxx-ip 之前加个判断，过滤这两个ip：

- 0.0.0.0
- 127.0.0.1

应该就能避免类似问题。

**Comment by zfl9** [comment]
一般就这两种ip。

如果确实有其他ip，不如换个思路，将这些受污染的国内域名划到一个单独的自定义group，其上游同--china-dns，但不配置ipset。

**Comment by zfl9** [comment]
> `--add-tagchn-ip` 如果不设置参数, 那么会把 ip 加入 `'--ipset-name4/6' 的 setname`, 也就是 `chnroute/chnroute6`, 而这个是用于 `ip test for tag:none` 的, 那么就会出现一楼说的`从而影响到了其他国内污染为 0.0.0.0 的域名的选择`
> 
> 其实解决方法很简单: 给 `--add-tagchn-ip` 设置一个单独的 setname, 就不会影响 `ip test for tag:none`, 不知道我理解的对不对?

这也是一种方法

**Comment by zfl9** [comment]
确实分开是最好的（从根本上避免该问题）。

不过有时候人就是喜欢偷懒。。。所以这里加个防御措施（127.0.0.1和0.0.0.0这两类ip就不add ip了）

**Comment by zfl9** [comment]
这些不排除，因为非常罕见。就算非常不幸遇到了这类情况，那就把这些“受污染域名”划到单独的group，用不会污染的dns去解析它们（要不要add ipset/nftset看情况，可配置）。

> 排除多了会“略微”损耗 add ip 的性能（因为每次 add 之前都要判断下），但如果只是 127、0，就非常简单，忽略不计。

**Comment by Smallthing** [comment]
tailscale的100.64.0.0还是蛮常见

**Comment by zfl9** [comment]
最新dev已修改

**Comment by zfl9** [comment]
> tailscale的100.64.0.0还是蛮常见

这个暂不考虑，如有需要，用其他方式规避吧（iptables/ipset、或者单独group）。
毕竟过滤 全0地址、loopback地址 只是出于防御目的，而且这两类ip也确实很常见。。

**Comment by puteulanus** [comment]
感谢 🙏
