### ISSUE TITLE
疑难杂症，无法复现，所以也无法修复。。

### ISSUE THREAD

**Issue by windmsn** [zfl9/chinadns-ng#165]
症状：
第一天[4月13日]：使用chinadns-ng作为主服务，开启cache，监听53端口，代替dnsmasq。客户端设备表现为无网络，dig没问题，手机就是连不上网。（设备主要是使用国内APP。抖音微信等日常的）
第二天[4月14日-15日]：为了保障家里设置能正常上网，chinadns-ng监听5354端口，关闭chinadns-ng的cache，开启dnsmasq的cache并作为主dns服务，chinadns-ng作为dnamasq的上游，**客户端备设使用正常两天**
第三天，同上
第四天[4月16日]：因为摆脱不了chinadns-ng的高性能，又把chinadns-ng作为了主服务。设置跟4月13日一样代替dnsmasq，客户端设备表现为无网络，无法连网，还是能dig通
第五天[4月17日]：又改回了**第二天[4月14日-15日]**的设置。**客户端备设使用正常**
第六天[4月18日]：又把chinadns-ng作为了主服务，但此次关闭了自带的cache。**客户端备设使用正常**

设备连不上网，表现为：chinadns-ng重启后，能短暂的使用一会。大概过了一个小时，就开始陆陆续续地出现网络无法连接的问题，重启chinadns-ng后，又正常一段时间。

曾经以为，resolver不支持edns或者tc等问题而提出过修改https://github.com/zfl9/chinadns-ng/issues/160#issuecomment-2051751354

也曾经以为是返回的reply过大https://github.com/zfl9/chinadns-ng/issues/160#issuecomment-2051795097

在4月16日测试的时候，我发现上游的223.5.5.5和119.29.29.29返回reply并不带有AUTHORITY和ADDITIONAL，返回的reply肯定不会超过512，于是我把国内的dns设为了`china-dns  223.5.5.5,udp://119.29.29.29`，但情况一样，一个小时左右客户端设置就开始出了无法连接到网络。

目前情况就是若想正常使用chinadns-ng作为主服务，就必须把它的cache给关了

配置如下
```
bind-addr ::
bind-port 53
china-dns 223.5.5.5,udp://119.29.29.29
trust-dns tcp://8.8.8.8
gfwlist-file /root/gfwlist.txt
chnlist-file /root/chnlist.txt
ipset-name4 cnip
ipset-name6 chnroute6
cache 10000
default-tag chn
add-taggfw-ip gfwlist,gfwlist6
```

![WX20240419-105023@2x](https://github.com/zfl9/chinadns-ng/assets/15327926/fac3506e-9357-40fb-b31b-115612236594)
![WX20240419-105044@2x](https://github.com/zfl9/chinadns-ng/assets/15327926/82ecd566-9931-432b-a308-ae31bef1ecb0)
![WX20240419-105149@2x](https://github.com/zfl9/chinadns-ng/assets/15327926/e9fbfd32-a7ae-4029-9027-66a764b04207)
![WX20240419-105157@2x](https://github.com/zfl9/chinadns-ng/assets/15327926/ddefe2a9-c1ca-4569-94f0-27d3668f1778)
![WX20240419-105210@2x](https://github.com/zfl9/chinadns-ng/assets/15327926/78f51892-0314-440f-99e4-34834e121ea0)
![WX20240419-105217@2x](https://github.com/zfl9/chinadns-ng/assets/15327926/d743ca7e-103b-4195-814c-0310fa7deafb)
![WechatIMG4113](https://github.com/zfl9/chinadns-ng/assets/15327926/7f677ac2-5623-425d-83de-6318e308c6b0)

**Comment by zfl9** [comment]
?

**Comment by windmsn** [comment]
> ?

在描述问题，不小心点了comment，等会，，

**Comment by zfl9** [comment]
看你配置，是gfwlist分流？

路由器上使用？mips吗

没网的时候，有去路由器上观察chinadns-ng什么状态没？还在运行？能否正常dig解析域名

**Comment by zfl9** [comment]
> 目前情况就是若想正常使用chinadns-ng作为主服务，就必须把它的cache给关了

关了cache就正常？

**Comment by zfl9** [comment]
> 没网的时候。chinadns-ng是正在运行的。局域网下的设置是能用dig解析域名的，但只局限于dig。其他客户端就表示没网络。

就是说，出现“没网的时候”，在其他局域网机器上，可以用dig正常解析，但是常规app就是提示没网？

**Comment by windmsn** [comment]
> > 没网的时候。chinadns-ng是正在运行的。局域网下的设置是能用dig解析域名的，但只局限于dig。其他客户端就表示没网络。
> 
> 就是说，出现“没网的时候”，在其他局域网机器上，可以用dig正常解析，但是常规app就是提示没网？

是的。是的。

**Comment by zfl9** [comment]
有没有测过在这种情况下，使用curl、wget测试？能否访问 baidu、google、youtube 之类的

**Comment by windmsn** [comment]
> 有没有测过在这种情况下，使用curl、wget测试？能否访问 baidu、google、youtube 之类的（模拟正常解析dns）

是有的。我常用wget。是可以解析的。也能直接wget到他们的index.html的。dns感觉运行是正常的。

**Comment by zfl9** [comment]
你说的wget测试，在什么机器上进行？openwrt路由器上？还是其他局域网机器上？都ok吗？

**Comment by windmsn** [comment]
> 你说的wget测试，在什么机器上进行？openwrt路由器上？还是其他局域网机器上？都ok吗？

路由器上和局域网下都是ok的。局域网里有2台linux设备。

**Comment by zfl9** [comment]
那就奇了怪了，出现你说的“无网络”症状时：

- 使用wget、dig可以正常解析dns、访问网站
- 但是手机上就提示没网络，无法访问

---

手机上获取的网关和dns都是指向这台openwrt路由器吗？

这个透明代理用的是什么插件？这里可能会有问题吗？

**Comment by windmsn** [comment]
> 那就奇了怪了，出现你说的“无网络”症状时：
> 
> * 使用wget、dig可以正常解析dns、访问网站
> * 但是手机上就提示没网络，无法访问
> 
> 手机上获取的网关和dns都是指向这台openwrt路由器吗？
> 
> 这个透明代理用的是什么插件？这里可能会有问题吗？

手机上提示没网络。主要集中于高频app。（微信，抖音，头条等）

路由器上，是做了dns 53端口胁持的。所有局域网内设置的dns查询都是被REDIRECT到路由器的53端口的。

透明代理用的是ssrplus。但是国内流量。都是直连的。。而且大半个ssrplus我自己重写过了。iptables上我试过把ssrplus的规则删除。情况依旧。透明代理插件应该没问题。

现在主要的区别就是cache与非cache的区别。。。

**Comment by zfl9** [comment]
手机没网的时候，能把那个时间段chinadns-ng日志发出来吗（开一下verbose日志）

**Comment by zfl9** [comment]
我有与你类似的使用场景，也是透明代理，chinadns-ng作为唯一的dns服务器，但不是openwrt，而是在树莓派上。

开了缓存等功能，也在上面持续跑了快半个月了，最长持续运行时间（未重启）应该有5天左右，没有你说的问题。

---

需要一些更详细的信息，才能分析（主要是我没法重现）：

- 出现“无网络”问题时的dns verbose log
- 当时的进程运行情况，cpu占用，内存占用
- dig测试、wget测试时的dns verbose log

**Comment by windmsn** [comment]
> 我有与你类似的使用场景，也是透明代理，chinadns-ng作为唯一的dns服务器，但不是openwrt，而是在树莓派上。
> 
> 开了缓存等功能，也在上面持续跑了快半个月了，最长持续运行时间（未重启）应该有5天左右，没有你说的问题。
> 
> 需要一些更详细的信息，才能分析（主要是我没法重现）：
> 
> * 出现“无网络”问题时的dns verbose log
> * 当时的进程运行情况，cpu占用，内存占用
> * dig测试、wget测试时的dns verbose log

稍等。我写个脚本捕获一下日志。

**Comment by zfl9** [comment]
记得把cache开启。

**Comment by muziling** [comment]
dhcp还需要dnamasq呢。是不是dhcp没了

**Comment by windmsn** [comment]
> dhcp还需要dnamasq呢。是不是dhcp没了

不是的dnsmasq没关，只是监听端口改为了0,chinadns-ng监听53而已。

**Comment by muziling** [comment]
可以考虑用mosdns运行一段时间看看有没有问题。

**Comment by windmsn** [comment]
> 可以考虑用mosdns运行一段时间看看有没有问题。

那倒不必。只要前面再套上dnsmasq，打开缓存。关掉chinadns-ng的cache
`dnsmasq(监听53)->chinadns-ng(监听5354)->各种上游`
这样是完全没问题的。

现在不想用dnsmasq去解析dns。。是因为chinadns-ng不出问题的时候是真的快。。

**Comment by zfl9** [comment]
看了下 cache 的代码，发现有个地方可能会导致某些客户端不兼容。

- NODATA 类型的响应（rcode=0/NOERROR && answer.n=0），我这边误删了 AUTHORITY 节的内容

按照 RFC 规范，这里要保留 SOA 记录的（位于 AUTHORITY 节）

不确定是否是这个问题导致。

**Comment by zfl9** [comment]
下午又出现了“无网络”是吗？

**Comment by windmsn** [comment]
> 下午又出现了“无网络”是吗？

是的。大概出现在下午5点钟左右，我女放学回来玩手机的时候说，日志上的时间+8小时。

**Comment by zfl9** [comment]
这个log的结束时间点是不是就是出故障的那段时间

**Comment by zfl9** [comment]
看日志没啥问题。。。

**Comment by windmsn** [comment]
> 
> > 但我觉得就算这个有影响，也不至于无网络，感觉问题根源不是这个。

其实这个问题在上一个版本的时候就已经有，更早之前的不清楚。那时候还没用chinadns-ng替代dnsmasq。，当时我还跟你说过以为是tc的问题，也以为是edns返回的包超过512字节的问题，才做了第一版的cache调整。

> > 这个log的结束时间点是不是就是出故障的那段时间

这个log的结束点。。。是被我女儿投诉上不了网后我又把dnsmasq加上去结束chinadns-ng缓存的时候的。
收到我女儿反馈的时候是5点左右。故障出现应该更早。。

> > 看日志没啥问题。。。

日志是看不出问题，dig，wget等都是正常的。当时我让她试了一些其他app〉小红书等，也是能正常使用的。

**Comment by zfl9** [comment]
> 日志是看不出问题，dig，wget等都是正常的。当时我让她试了一些其他app〉小红书等，也是能正常使用的。

是部分APP无网络，而不是所有都无网络？

那就更奇怪了。

**Comment by zfl9** [comment]
你确定不是路由器哪里设置有问题吗，这看起来不像是DNS导致的。

**Comment by zfl9** [comment]
cache从理论上来说，如果会出问题，也是一开始就出问题了，而不是运行几个小时后出问题。毕竟程序都是死的。无论运行多久，cache的逻辑都是相同的。

cache只会影响2个方面：
- dns解析速度的快慢，这个很好理解。
- 保存cache的reply msg时，对msg进行了裁剪，丢弃了authority/additional节，只留下了answer节，对于常规响应(answer节有内容，即非NODATA响应)，这样做是完全没问题的，dnsmasq也是一样的做法。而且这个修改只在add cache时进行一次，之后hit cache都只是简单的返回这个数据，无其他修改（除了TTL递减）。

按理来说要是这里会出问题，刚开始运行就会立马发现。所以我想不通。

**Comment by zfl9** [comment]
我想起一个地方：未命中缓存时的响应内容 与 命中缓存时的响应内容 有一些不同：
- 未命中缓存时的响应，带了EDNS信息给客户端（也就是OPT RR），当然前提是客户端发了EDNS信息过来
- 命中缓存时的响应，因为add cache时被修剪了，所以只有answer节，没有EDNS那些信息

我只能怀疑是这个不同 导致某些 dns resolver 产生误判或奇怪行为。

有兴趣的话，我明天给你发个修改版，测试下

**Comment by windmsn** [comment]
> cache从理论上来说，如果会出问题，也是一开始就出问题了，而不是运行几个小时后出问题。毕竟程序都是死的。无论运行多久，cache的逻辑都是相同的。
> 
> cache只会影响2个方面：
> 
> * dns解析速度的快慢，这个很好理解。
> * 保存cache的reply msg时，对msg进行了裁剪，丢弃了authority/additional节，只留下了answer节，对于常规响应(answer节有内容，即非NODATA响应)，这样做是完全没问题的，dnsmasq也是一样的做法。而且这个修改只在add cache时进行一次，之后hit cache都只是简单的返回这个数据，无其他修改（除了TTL递减）。
> 
> 按理来说要是这里会出问题，刚开始运行就会立马发现。所以我想不通。

我今天也扒了半天cache.zig，CacheMsg.zig，dns.zig的代码。。因为zig不太懂，平时主要肝java和python，所以看得有点吃力。
有些也只能猜。。
目前我有这几方面的猜想：

> 
> - dns服务器返回数据时会不会有出错的情况（有这个猜想是因为运营商基本是把dns给劫持了）。概率不知道高不高，如果存在这种情况又把信息给缓存了，dnsmasq又是如何处理的。所以晚上添加了`cache-nodata-ttl 0`测试，有时候dig dnsmasq的时候，需要dig好几次才能Q`uery time: 0 msec`说明缓存命中。
> 
> - 我观察了一下，下午的d.log缓存，大概1小时就add cache 就达到了10000条了。10000条里面有8000条的TTL是30-200，大概有1000条的TTL是400-600，对于高频的域名解析，TTL时间短的，应该是一个不断add cache的过程。这个过程会不会有问题，这主要是联想到高频访问题30-60分钟就会出故障而时间又刚好跟这个有交集。

> 修改的内容：
> 
> 无论是否启用缓存，都把additional节给删了（EDNS信息在这个节，有些dns服务器也会在这个节带上NS记录关联的A/AAAA记> 录），本质上都没啥作用，不如删了，这样无论是否启用缓存，response都是一样的，唯一的区别就是响应时间的快慢，这下总没> 有问题了吧。。。
> 
> 移除这个信息不影响chinadns-ng对query的EDNS bufsize信息的读取，这两操作之间没有关联。也即是说，如果UDP查询端在> OPT RR中声明了 bufsize 为 4096，那么chinadns-ng可以理解这个信息，只要response没超过这个size，就不会发送truncated > response给查询方。


这个可以有。明天有包测试打一个试试。还是一样两个架构
```
ChinaDNS-NG 2024.04.13 | target:x86_64-linux-musl | cpu:x86_64_v3 | mode:fast+lto
ChinaDNS-NG 2024.04.13 | target:mipsel-linux-musl | cpu:mips32r5 | mode:fast+lto
```
我今晚添加的`cache-nodata-ttl 0`明天也可以一同汇报

**Comment by windmsn** [comment]
> 我想起一个地方：未命中缓存时的响应内容 与 命中缓存时的响应内容 有一些不同：
> 
> * 未命中缓存时的响应，带了EDNS信息给客户端（也就是OPT RR），当然前提是客户端发了EDNS信息过来
> * 命中缓存时的响应，因为add cache时被修剪了，所以只有answer节，没有EDNS那些信息
> 
> 我只能怀疑是这个不同 导致某些 resolver 产生奇怪行为。因为我思来想去，与dnsmasq做对比，唯一的区别就在这个地方。
> 
> 有兴趣的话，我明天给你发个修改版，测试下
> 
> 修改的内容：
> 
> 无论是否启用缓存，都把additional节给删了（EDNS信息在这个节，有些dns服务器也会在这个节带上NS记录关联的A/AAAA记录），本质上都没啥作用，不如删了，这样无论是否启用缓存，response都是一样的，唯一的区别就是响应时间的快慢，这下总没有问题了吧。。。
> 
> > 移除这个信息不影响chinadns-ng对query的EDNS bufsize信息的读取，这两操作之间没有关联。也即是说，如果UDP查询端在OPT RR中声明了 bufsize 为 4096，那么chinadns-ng可以理解这个信息，只要response没超过这个size，就不会发送truncated response给查询方。

我发现，dnsmasq，在缓存前缓存后是有不同的
不知道他是否为了兼容性？
>

- 缓存前的reply无论是否带有EDNS的OPT，缓存后都加上，
- 缓存前带有的AUTHORITY SECTION和ADDITIONAL SECTION，缓存后都不见了，


缓存前
```
[root@ManTou:/root]#dig @127.0.0.1 -p53 www.qq.com

; <<>> DiG 9.9.9-P3 <<>> @127.0.0.1 -p53 www.qq.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64538
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 3, ADDITIONAL: 13

;; QUESTION SECTION:
;www.qq.com.                    IN      A

;; ANSWER SECTION:
www.qq.com.             223     IN      CNAME   ins-r23tsuuf.ias.tencent-cloud.net.
ins-r23tsuuf.ias.tencent-cloud.net. 116 IN A    112.53.42.52
ins-r23tsuuf.ias.tencent-cloud.net. 116 IN A    112.53.42.114

;; AUTHORITY SECTION:
tencent-cloud.net.      137794  IN      NS      ns-open2.qq.com.
tencent-cloud.net.      137794  IN      NS      ns-open1.qq.com.
tencent-cloud.net.      137794  IN      NS      ns-open3.qq.com.

;; ADDITIONAL SECTION:
ns-open1.qq.com.        6605    IN      A       203.205.236.176
ns-open1.qq.com.        6605    IN      A       59.36.132.139
ns-open1.qq.com.        6605    IN      A       117.135.174.196
ns-open2.qq.com.        1931    IN      A       182.254.59.163
ns-open2.qq.com.        1931    IN      A       203.205.195.63
ns-open2.qq.com.        1931    IN      A       203.205.195.122
ns-open2.qq.com.        1931    IN      A       61.241.27.10
ns-open3.qq.com.        481     IN      A       101.227.161.202
ns-open3.qq.com.        481     IN      A       121.51.167.100
ns-open3.qq.com.        481     IN      A       140.207.180.51
ns-open3.qq.com.        481     IN      A       203.205.220.25
ns-open3.qq.com.        481     IN      A       218.68.91.163
ns-open2.qq.com.        2590    IN      AAAA    240e:e1:aa00:2001::3

;; Query time: 7 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Apr 20 09:47:49 CST 2024
;; MSG SIZE  rcvd: 397
```

缓存后：
```
[root@ManTou:/root]#dig @127.0.0.1 -p53 www.qq.com

; <<>> DiG 9.9.9-P3 <<>> @127.0.0.1 -p53 www.qq.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32265
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.qq.com.                    IN      A

;; ANSWER SECTION:
www.qq.com.             210     IN      CNAME   ins-r23tsuuf.ias.tencent-cloud.net.
ins-r23tsuuf.ias.tencent-cloud.net. 103 IN A    112.53.42.114
ins-r23tsuuf.ias.tencent-cloud.net. 103 IN A    112.53.42.52

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Apr 20 09:48:02 CST 2024
;; MSG SIZE  rcvd: 119
```

**Comment by zfl9** [comment]
[bin.tgz](https://github.com/zfl9/chinadns-ng/files/15046637/bin.tgz)

**Comment by zfl9** [comment]
@windmsn 试试，参数不变（记得开启cache），替换上去

**Comment by windmsn** [comment]
> @windmsn 试试，参数不变（记得开启cache），替换上去

这个版本是无论缓存与否。都保留AUTHORITY SECTION，砍掉了ADDITIONAL SECTION。

待测，

思考一下，为何dnsmasq，223.5.5.5，119.29.29.29，8.8.8.8等都需要加上EDNS的opt。。。

**Comment by zfl9** [comment]
> 这个版本是无论缓存与否。都保留AUTHORITY SECTION，砍掉了ADDITIONAL SECTION。

是的。

**Comment by zfl9** [comment]
> 为何dnsmasq，223.5.5.5，119.29.29.29，8.8.8.8等都需要加上EDNS的opt。。。

那是因为dig默认启用了EDNS，dig测试时，加上 `+noedns` 标志就明白了。

**Comment by zfl9** [comment]
> 我发现，dnsmasq，在缓存前缓存后是有不同的
不知道他是否为了兼容性？

先不管这个吧，我相信让消息保持一致是有益的（无论是否启用缓存），应该能减少所谓的兼容性问题。

**Comment by windmsn** [comment]
> @windmsn 试试，参数不变（记得开启cache），替换上去

已替换上去。。在测。观察一天。今天周六不上学。应该能体现结果

**Comment by zfl9** [comment]
ok，有问题及时反馈，我这边方便跟进并尝试修复。

**Comment by windmsn** [comment]
> > 为何dnsmasq，223.5.5.5，119.29.29.29，8.8.8.8等都需要加上EDNS的opt。。。
> 
> 那是因为dig默认启用了EDNS，dig测试时，加上 `+noedns` 标志就明白了。
> 
> glibc/musl等libc没有启用edns，我之前观察过。

会不会有这么一种工况：

- resolver支持EDNS，向chinadnsng发送query，chinadns-ng转发query给上游DNS服务器，
- 上游DNS服务器返回带有EDNS opt的reply。chinadns-ng把这部分抹掉了。resolver获取到的数据出现兼容性问题？

会不会有这种情况？

**Comment by zfl9** [comment]
不会有兼容性问题，因为 EDNS 是向后兼容的（具体可以看看 rfc6891）。

比如：当一个支持 EDNS 的客户端（在 query 中携带了 EDNS 信息），查询一个传统服务端时，服务端因为不理解 EDNS 信息，所以返回的 response 不会有 EDNS 信息。

chinadns-ng 会理解客户端传来的 OPT RR（主要是读取其中的 bufsize，用于 reply 时的 truncated 逻辑），但不会在 response 中放入 EDNS 信息，目的是模拟传统服务端的行为。因为 chinadns-ng 本身不提供 EDNS 相关特性，自然没必要发送它。

**Comment by windmsn** [comment]
> ok，有问题及时反馈，我这边方便跟进并尝试修复。

还是反映有问题。。。已经想不出是哪里有可能了。。
![WX20240420-133314@2x](https://github.com/zfl9/chinadns-ng/assets/15327926/2e15abd5-4810-4133-bdf8-314e277afbaf)

**Comment by zfl9** [comment]
见鬼了？

完全相同的配置/dns/环境，只把cache关了(配置cache 0，其他一个都别修改)，然后重启chinadns-ng。再试

**Comment by zfl9** [comment]
另外你没网络时怎么恢复的，操作是什么？单纯重启dns进程？还是重启路由器。还是重新设置iptables？

**Comment by zfl9** [comment]
这回可真是有没有缓存都一样的response哦，如果开cache就会导致微信有问题，关闭cache就没问题，那我只能说见鬼了

我和其他人也没遇见你这种情况。。

ss-tproxy那边也没有类似的反馈

**Comment by windmsn** [comment]
> 另外你没网络时怎么恢复的，操作是什么？单纯重启dns进程？还是重启路由器。还是重新设置iptables？

恢复网络只需重启chinadns-ng即可。其他不需要操作。。

**Comment by zfl9** [comment]
内核dmesg日志有没有？发来看看

**Comment by zfl9** [comment]
劫持dns的iptables发来看看

**Comment by zfl9** [comment]
完整chinadns配置发来看看

测试记得全程开verbose，方便分析

**Comment by windmsn** [comment]
> 内核dmesg日志有没有？发来看看

内核也没报啥奇怪的。。
[dmesg.log](https://github.com/zfl9/chinadns-ng/files/15047013/dmesg.log)

> 劫持dns的iptables发来看看

iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53
iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53
![WX20240420-140048@2x](https://github.com/zfl9/chinadns-ng/assets/15327926/6c4af438-9371-4eb8-8d84-08910a234705)

配置文件是刚修改了`cache 0`之前我是直接把cache给去掉的。。
```
bind-addr ::
bind-port 53
china-dns 223.5.5.5,2400:3200::1
trust-dns tcp://8.8.8.8
gfwlist-file /root/gfwlist.txt
chnlist-file /root/chnlist.txt
ipset-name4 cnip
ipset-name6 chnroute6
cache 0
cache-nodata-ttl 0
default-tag chn
add-taggfw-ip gfwlist,gfwlist6
no-ipv6 tag:gfw
```

verbose的话正在捕获。。需要点时间

**Comment by zfl9** [comment]
你这个config有几个无用配置：

```bash
#这个不需要，因为default-tag chn已经将所有未匹配list的域名tag归为了tag:chn
chnlist-file /root/chnlist.txt

# 这两个也没用，你是gfwlist模式，根本没有tag:none，用不上ip test
# ipset-name4 chip
# ipset-name6 chnroute6
```

**Comment by windmsn** [comment]
> 你这个config有几个无用配置：
> 
> ```shell
> #这个不需要，因为default-tag chn已经将所有未匹配list的域名tag归为了tag:chn
> chnlist-file /root/chnlist.txt
> 
> # 这两个也没用，你是gfwlist模式，根本没有tag:none，用不上ip test
> # ipset-name4 chip
> # ipset-name6 chnroute6
> ```

这个。。因为一直在调整测试。参数。。还没整理。。应该没影响的。。。吧。。

**Comment by zfl9** [comment]
先等你的without cache测试结果。

**Comment by zfl9** [comment]
难道是这个zig hash表有问题？

我待会重写一个hashmap。

你要测试没缓存时是否ok

**Comment by windmsn** [comment]
> 难道是这个zig hash表有问题？
> 
> 我待会重写一个hashmap。
> 
> 你先测试没缓存时是否ok

恩，我先暂定观察6小时，因为昨天关了cache运行16小时没异常。

**Comment by zfl9** [comment]
看起来没问题？我改了下cache.zig，去掉zig的hashmap，待会你试试（开缓存）。

**Comment by zfl9** [comment]
[Uploading bin.tgz…]()

**Comment by zfl9** [comment]
[bin.tgz](https://github.com/zfl9/chinadns-ng/files/15047654/bin.tgz)

**Comment by windmsn** [comment]
> 看起来没问题？我改了下cache.zig，去掉zig的hashmap，待会你试试（开缓存）。

`cache 0`后暂时还未收到异常报告。。。

**Comment by zfl9** [comment]
ok，那可以确定是cache.zig的问题了，可能reply数据错位了。

不确定是zig的hashmap问题，还是我使用不当。

**Comment by zfl9** [comment]
cache 0和直接注释#cache 10000是一样的么？

一样，cache 选项默认值就是0。0就是不启用缓存。

**Comment by windmsn** [comment]
> cache 0和直接注释#cache 10000是一样的么？
> 
> 一样，cache 选项默认值就是0。0就是不启用缓存。

我先放上去开启缓存观察一下。。。

**Comment by windmsn** [comment]
@zfl9 还是不行。。不知道是啥问题了，先不弄了。。老母有大意见，。先在前面套个dnsmasq用着先。。

![WX20240422-084350@2x](https://github.com/zfl9/chinadns-ng/assets/15327926/0015c489-1c6b-4cd9-a7a2-c2566c116d6f)

**Comment by zfl9** [comment]
那就不知道你这边啥问题了，我也无能为力。

因为我和其他人都是正常使用，没见你这种情况。

关了。。

**Comment by windmsn** [comment]
> 那就不知道你这边啥问题了，我也无能为力。
> 
> 因为我和其他人都是正常使用，没见你这种情况。
> 
> 关了。。

不知道跟我双拨有没有关系。。。。

我老母家是双拨电信千兆，。

我自己家是单拨移动千兆。。。

我自己那的单拨，好像问题不大。虽然也有偶发性的解析问题，但是没有老母家的严重。

**Comment by zfl9** [comment]
有可能是 LTO 优化的问题，待会给你构建一个不带 LTO 的版本，试试？

**Comment by windmsn** [comment]
> 有可能是 LTO 优化的问题，待会给你构建一个不带 LTO 的版本，试试？
> 
> @windmsn

可以有。。LTO是什么。。。

**Comment by zfl9** [comment]
链接时优化，今天晚上我和另一个小伙伴测试 x86_64 版本的 chinadns-ng，发现有些问题。

不确定与你的错误是否有关系。

**Comment by windmsn** [comment]
> 链接时优化，今天晚上我和另一个小伙伴测试 x86_64 版本的 chinadns-ng，发现有些问题。
> 
> 不确定与你的错误是否有关系。

哦对的。我老娘那是x86的。电信，双拨，经常反馈有问题。

我自己用的是mipsel，只出现了偶尔的半次打不开阿里云的连接。其他时间很正常。

**Comment by windmsn** [comment]
@zfl9 中午的时候换了不带LTO版本的。老娘反馈还是不行。反馈有问题的时候，套上dnsmasq也不行，后来要把chinadns-ng用回原来的4.13带LTO的才可以

目前正常使用的部署是用dnsmasq监听53端口并做缓存，chinadns-ng只做转发查询分流关闭cache。

先不管了。先这样用着。到时想到是什么问题再反馈。。。

![IMG_0528](https://github.com/zfl9/chinadns-ng/assets/15327926/2f97679d-8a7d-498b-ba37-21761641fd94)

**Comment by zfl9** [comment]
如果后面有空，记得补充细节，从整个issue来看，还是缺少一个整体的描述，特别是所谓“问题”出现时的各种细节：

- 整个局域网都“无网络”？还是只有给定的设备（手机？）无网络？
- 如果是只有手机有问题，是部分“手机APP”显示无网络，还是全部“手机APP”显示无网络？
- 如果能拿到当时手机的“错误日志”，那就可以分析究竟是什么导致它“无网络”，而不是现在这样猜测。。
- 另外，根据你之前说的，出现“问题”时，其他设备可以正常使用dig、wget访问？是否有确认过当时的chinadns log有收到这些dig、wget的dns解析。
- 因为我是没办法重现，而且其他人也没办法重现，要找出问题的真正原因，只能靠你自己了。最最重要的一点时，尽量不要只看表面现象，光在那猜测没意义，解决不了问题。。必须结合日志来分析，而且最好看看出问题时的log，到底有什么异常之处。。不光是chinadns-ng的日志，最理想的情况是能够分析到当时手机APP（或系统）的日志，看看到底什么鬼情况。。。

**Comment by windmsn** [comment]
> 如果后面有空，记得补充细节，从整个issue来看，还是缺少一个整体的描述，特别是“问题”出现时：
> 
> * 整个局域网都“无网络”？还是只有给定的设备（全部手机？某些特定手机？）无网络？
> * 如果是只有手机有问题，是部分“手机APP”显示无网络，还是全部“手机APP”显示无网络？
> * 如果能拿到当时手机的“错误日志”，那就可以分析究竟是什么导致它“无网络”，而不是现在这样猜测。。
> * 另外，根据你之前说的，出现“问题”时，其他设备可以正常使用dig、wget访问？是否有确认过当时的chinadns log有收到这些dig、wget的dns解析。
> * 因为我是没办法重现，而且其他人也没办法重现，要找出问题的真正原因，只能靠你自己了。最最重要的一点时，尽量不要只看表面现象，光在那猜测没意义，解决不了问题。。必须结合日志来分析，而且最好看看出问题时的log，到底有什么异常之处。。不光是chinadns-ng的日志，最理想的情况是能够分析到当时手机APP（或系统）的日志，看看到底什么鬼情况。。。
> 
> 还有个办法，如果可能，建议换个环境测试，先排除是不是被openwrt上的某些东西影响到了。
> 
> 另外，建议多去了解 DNS 相关的细节知识（虽然我也不太抱有什么希望了），就先这样吧。。。

恩，有空再去测了。反正现在套个dnsmasq作缓存。也能用。。。再弄下去。。老母估计会把宽带都取消掉了。。

**Comment by zfl9** [comment]
是的，主要看你自己这边了，不想折腾就现在这样也没问题。。。

**Comment by windmsn** [comment]
> 是的，主要看你自己这边了，不想折腾就现在这样也没问题。。。

已破案，这个原因主要是dnsmasq的port设置为0后，它将停止dns的功能，这会导致他的dhcp服务不会向客户端提供dhcp_option '6,192.168.0.1'这个东西。。客户端获取不到DNS服务器地址导致无法解析域名。而平时有时能正常使用，是因为ipv6 ra时会给客户端下发路由器的ipv6地址作为dns服务器。当ra更新的时候，，就失效了。

查阅了几个案例。发现有部分用户同样使用adgurad home代替dnsmasq时都会出现同样症状，

如若用chinadns-ng替代dnsmasq，则需要手动给dnsmasq添加`dhcp_option '6,192.168.0.1'`
另外，dnsmasq只有port设为53的时候，才会给客户端下发dns地址。。。监听其他端口。。都不行。

至于缓存问题，，，可能是错觉。。但也有可能是ipv6所导致。。目前还不清楚。只知道添加`dhcp_option '6,192.168.0.1'`后，一切症状解决。

还需给普通用户备注提醒。。。

**Comment by zfl9** [comment]
总算找到问题原因了哈，我就说这种“奇怪的”现象和 chinadns-ng 应该没关系，因为不符合程序的常理。。

> 在 dnsmasq 只担任 DHCP 角色时（port=0），必须确保有 `dhcp_option '6,DNS服务器IP'` 这样一条配置的存在。

后面我在 readme 补充说明下，防止还有人掉坑。

**Comment by zfl9** [comment]
翻了下 dnsmasq 文档：

By default, dnsmasq sends some standard options to DHCP clients, the netmask and broadcast address are set to the same as the host running dnsmasq, and the DNS server and default route are set to the address of the machine running dnsmasq.

我猜测 dnsmasq 内部逻辑是这样，当 dnsmasq 的 DNS 功能启用时（可能还有个条件，那就是端口必须是标准的 53），才会自动下发 dns-server 这个 dhcp-option，并且 dns-server 的 IP 是 dnsmasq 所在的主机的 IP。

当这个条件不满足时，比如这个 issue（port=0，关闭了 DNS），就不下发这个 dns-server option 了，于是就出现了你说的这个问题。。确实挺坑的。
