### ISSUE TITLE
24.4.13版本用不了 ，是改变什么吗

### ISSUE THREAD

**Issue by hq999999** [zfl9/chinadns-ng#167]
passwall

**Comment by hq999999** [comment]
回退到24.3.27正常

**Comment by zfl9** [comment]
![image](https://github.com/zfl9/chinadns-ng/assets/22726048/82ee27a7-b3af-477a-926d-5c9ea1dd236b)

估计是 no-ipv6 规则导致，更新 passwall 版本应该可以解决。

**Comment by hq999999** [comment]
谢谢大佬回复
![image](https://github.com/zfl9/chinadns-ng/assets/155155038/6f719cbd-aa7c-4e39-9be9-3d00973d5d41)
![image](https://github.com/zfl9/chinadns-ng/assets/155155038/8fa06b71-f694-4522-9eed-d57e0587f3f0)
果然，更新了最新passwall就可以用了
4.71版本只能用chinadns 24.03.27版本
4.77版本就能最新版本chinadns-ng
