### ISSUE TITLE
现在的版本有原版的压缩指针功能吗？

### ISSUE THREAD

**Issue by pexcn** [zfl9/chinadns-ng#17]
原版的 README: https://github.com/shadowsocks/ChinaDNS#usage 里面说到有个 `-m` 选项可以开启压缩指针功能。
想问一下，压缩指针的作用是什么？chinadns-ng 有这个功能吗（自带了，默认开启？）？

**Comment by zfl9** [comment]
原版的压缩指针应该是个过时的特性，最开始使用 chinadns 防污染的方式是：国外/可信 dns 不走代理，仅靠【压缩指针】来避免污染，这个其实很早就无效了，而且要命的是，在我们现在这种使用方式中（国外/可信dns走代理），如果启用了压缩指针，某些域名会解析失败（此处被坑了好久）。chinadns-ng 虽说是 chinadns 的重构版，但其实吧，是我自己完全重写的，唯一相同的可能就是【核心的判断规则】吧。

**Comment by pexcn** [comment]
噢噢，清楚了
