### ISSUE TITLE
路由器上使用chinadns，一直日志里显示网络不可达

### ISSUE THREAD

**Issue by miaomiaocatmsg** [zfl9/chinadns-ng#171]
May 10 15:55:56 【chinadns_ng】:  ^[[33;1m2024-05-10 15:55:56 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 15:56:56 【chinadns_ng】:  ^[[33;1m2024-05-10 15:56:56 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 15:57:56 【chinadns_ng】:  ^[[33;1m2024-05-10 15:57:56 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 15:58:57 【chinadns_ng】:  ^[[33;1m2024-05-10 15:58:57 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 15:59:57 【chinadns_ng】:  ^[[33;1m2024-05-10 15:59:57 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 15:59:58 【chinadns_ng】:  ^[[33;1m2024-05-10 15:59:57 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable

路由器消息一直是显示这个，请问是什么原因，网络可用。
老毛子版本3.4.3.9-099_24-04-1
chinadns_ng版本 2024.04.27

**Comment by zfl9** [comment]
你 dig 能访问这个 ::1 8053 吗？

换句话说，是否确实网络不可达？

**Comment by miaomiaocatmsg** [comment]
您好，您的邮件我已经收到了。
会尽快处理的。

**Comment by miaomiaocatmsg** [comment]
你好，我不太清楚 dig 是啥，另外 ::1 8053是iPv6地址吗？我电信网关是关闭ipv6的功能的。
如果是ipv6,地址，那应该是不可达的。

May 10 20:02:56 【clash】: clash 守护进程启动
May 10 20:02:57 watchdog: 【dnsmasq is missing】,start again!
May 10 20:02:57 dnsmasq[2970]: cannot access /tmp/ss_tproxy/dnsmasq.d/accelerated-domains.china.conffGnYM9: No such file or directory
May 10 20:02:57 dnsmasq[2970]: FAILED to start up
May 10 20:03:17 watchdog: 【dnsmasq is missing】,start again!
May 10 20:03:18 dnsmasq[3143]: started, version 2.89 cachesize 1024
May 10 20:03:18 dnsmasq[3143]: warning: ignoring resolv-file flag because no-resolv is set
May 10 20:03:18 dnsmasq-dhcp[3143]: DHCP, IP range 192.168.2.2 -- 192.168.2.244, lease time 7d
May 10 20:03:18 dnsmasq-dhcp[3143]: DHCP, sockets bound exclusively to interface br0
May 10 20:03:18 dnsmasq[3143]: more servers are defined but not logged
May 10 20:03:19 dnsmasq[3143]: read /etc/hosts - 12 names
May 10 20:03:19 dnsmasq[3143]: read /etc/storage/dnsmasq/hosts - 0 names
May 10 20:03:19 dnsmasq-dhcp[3143]: read /etc/dnsmasq/dhcp/dhcp-hosts.rc
May 10 20:03:19 dnsmasq[3143]: more servers are defined but not logged
May 10 20:04:16 【chinadns_ng】:  ^[[33;1m2024-05-10 20:04:16 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 20:05:16 【chinadns_ng】:  ^[[33;1m2024-05-10 20:05:16 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 20:06:16 【chinadns_ng】:  ^[[33;1m2024-05-10 20:06:16 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 20:07:17 【chinadns_ng】:  ^[[33;1m2024-05-10 20:07:17 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 20:08:17 【chinadns_ng】:  ^[[33;1m2024-05-10 20:08:17 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 20:09:18 【chinadns_ng】:  ^[[33;1m2024-05-10 20:09:18 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 20:10:18 【chinadns_ng】:  ^[[33;1m2024-05-10 20:10:18 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable
May 10 20:11:18 【chinadns_ng】:  ^[[33;1m2024-05-10 20:11:18 W^[[0m ^[[1m[Upstream.zig:151 udp_send]^[[0m send(udpi://::1#8053) failed: (128) Network unreachable

目前前后日志大概是这样了。

**Comment by zfl9** [comment]
那就是你的插件有问题，::1 是 ipv6 地址。

**Comment by miaomiaocatmsg** [comment]
好的 感谢
