### ISSUE TITLE
c代码真是不忍直视啊

### ISSUE THREAD

**Issue by xiedeacc** [zfl9/chinadns-ng#174]
不是喷楼主哈，只是感觉C风格的代码太难看（纯粹由于鄙人是C++程序员），打算用C++重写下

**Comment by zfl9** [comment]
如果你想重写，当然欢迎，但请不要发这种 具有引战嫌疑的、无建设性意义的 issue。

我不知道你发这个 issue 的核心意义是什么，如果只是编程语言之争，那大可不必。

**Comment by xiedeacc** [comment]
哈哈哈，不是语言争论，纯粹吐槽，现在删除
