### ISSUE TITLE
trust-dns DoT Error：[Upstream.zig:822 Group.parse_failed] invalid proto: 'tls://'

### ISSUE THREAD

**Issue by jiamliang** [zfl9/chinadns-ng#175]
文档中说： 2024.05.12 版本起，DoT 上游地址中，允许省略域名信息，即 tls://IP。
想配置 DoT 上游 DNS， 配置文件里面 ：
trust-dns tls://1.1.1.1
trust-dns tls://8.8.4.4
trust-dns tls://8.8.8.8

./chinadns-ng -C config.txt  会报告错误：

[Upstream.zig:822 Group.parse_failed] invalid proto: 'tls://'
[opt.zig:327 opt_trust_dns] invalid opt-value: 'tls://1.1.1.1'
usage: chinadns-ng <options...>. the existing options are as follows:

# ./chinadns-ng -V
ChinaDNS-NG 2024.05.12 d7b2717 | target:x86_64-linux-musl | cpu:x86_64 | mode:fast+lto | <https://github.com/zfl9/chinadns-ng>

请问是哪里不对吗？
谢谢！

**Comment by zfl9** [comment]
下载的版本不对，带wolfssl的版本才支持DoT。

**Comment by jiamliang** [comment]
> 下载的版本不对，带wolfssl的版本才支持DoT。

正解！
谢谢！
