### ISSUE TITLE
能同时监听多个端口吗？

### ISSUE THREAD

**Issue by Smallthing** [zfl9/chinadns-ng#176]
-l 参数

**Comment by zfl9** [comment]
目前不支持，要支持也比较简单。

不过我想问下这么做的目的是？啥需求？

**Comment by Smallthing** [comment]
底下不同部门的端口不一样，历史遗留问题，不太好改。。。我现在起两个进程，就是缓存不共享

**Comment by zfl9** [comment]
我觉得有更简单的办法，iptables REDIRECT 处理下就可以了。你觉得如何？一条规则就行。

**Comment by Smallthing** [comment]
是可以，先这么处理了，不过配置上体现不出来就和iptables耦合了。

**Comment by zfl9** [comment]
在下次更新中，会带上这个功能。

**Comment by zfl9** [comment]
见 2024.07.16 版本。
