### ISSUE TITLE
支持bridge协议添加到set

### ISSUE THREAD

**Issue by Emong** [zfl9/chinadns-ng#177]
`--add-taggfw-ip bridge@psw@ACC,bridge@psw@ACC6`

如果添加ip到 bridge 协议 的set 会提示

`invalid family`

希望支持

**Comment by zfl9** [comment]
应该可以，我先本地测试下。

**Comment by zfl9** [comment]
见 2024.07.16 版本。

**Comment by Emong** [comment]
验证ok，赞。
