### ISSUE TITLE
apps.apple.com 的问题

### ISSUE THREAD

**Issue by pexcn** [zfl9/chinadns-ng#18]
假如要访问美区的 https://apps.apple.com/us/app/speedtest-by-ookla/id1153157709, chinadns-ng 会返回国内的 IP 的结果，在网页上会显示 404（https://apps.apple.com/us/ 屏蔽了国内的 IP？）。

在 dnsmasq 添加 apps.apple.com 强制让可信 DNS 解析应该可以解决，想问下有没有更好的方法？

**Comment by zfl9** [comment]
必须【美区】？这应该是使用了 cdn 吧，如果使用【域名列表】走可信 dns，估计也是走的 vps 所在区域附近的 cdn 节点。不过无论如何，域名匹配应该是避免不的。关于在 `chinadns-ng` 上的匹配功能，暂时有一个应该可行且性能也应该不错的想法，不过我人为的给它加了个限制：domain.list 文件中的每个域名，label 最少 2 个，最多 4 个。比如这 3 个都符合要求：
```shell
baidu.com # 2 个 label
google.co.jp # 3 个 label
www.google.com.hk # 4 个 label
```

**Comment by pexcn** [comment]
我美国的 IP 这 4 个区的都能访问，看来是大陆 IP 的问题...
https://apps.apple.com/hk/app/speedtest-by-ookla/id1153157709
https://apps.apple.com/tw/app/speedtest-by-ookla/id1153157709
https://apps.apple.com/jp/app/speedtest-by-ookla/id1153157709
https://apps.apple.com/sg/app/speedtest-by-ookla/id1153157709

> 不过我人为的给它加了个限制：domain.list 文件中的每个域名，label 最少 2 个，最多 4 个。比如这 3 个都符合要求：
> 
> ```shell
> baidu.com # 2 个 label
> google.co.jp # 3 个 label
> www.google.com.hk # 4 个 label
> ```

希望不合法的域名可以被忽略，不知道 gfwlist 里面的域名有没有超过 4 个 label 的...

**Comment by zfl9** [comment]
我看了一下 gfwlist.txt，应该没有问题的，限制的原因当然也是主要考虑到性能问题。
![image](https://user-images.githubusercontent.com/22726048/65406349-d623ee00-de11-11e9-8edb-4a0ae322ad6f.png)
1 个 label 的（比如 com），这种直接忽略。因为太短了，命中范围太大。
过长的（4个以上label），直接取后面 4 个label。这样也不会有太大的印象。

**Comment by zfl9** [comment]
@pexcn 已更新，`--gfwlist-file`，具体见 readme 以及最新提交。

**Comment by pexcn** [comment]
嗯，好。

> ... `-` indicate stdin

有个疑问，gfwlist-file 选项的标准输入用在什么场景呢？

**Comment by zfl9** [comment]
当 gfwlist.txt 文件内容需要动态生成时，从 `stdin` 读取比较方便。
