### ISSUE TITLE
能否增加域名列表reload的功能？

### ISSUE THREAD

**Issue by InspoOnU** [zfl9/chinadns-ng#182]
目前我在路由器上设置每周更新一次ipset和国内外域名列表，这样每次重启chinadns-ng后verdict-cache就失效了

**Comment by zfl9** [comment]
目前在着手重写相关zig代码，以便可以更新到最新版zig。所以新功能暂时要等一段时间了。

重载域名列表应该可以，不过我想另一种更简单的办法，支持导出内存中的verdict cache到一个文本文件，并支持从该文件导入verdict cache。感觉这个代码量会很少一些。因为域名列表涉及最多8个group(2个内置+6个自定义)，单重载某个group的列表是不可行的，因为所有group的域名列表都加载到同一个数据结构中，二重载本质上就是先从结构中删除oldlist.txt的数据，然后载入newlist.txt的数据，但由于加载顺序的存在，导致单纯reload某个group不好实现，不如reload全部group的列表。但这样的话，我觉得不如换个思路，支持导入和导出verdict cache。

**Comment by zfl9** [comment]
目前在着手重写相关zig代码，以便可以更新到最新版zig。所以新功能暂时要等一段时间了。

重载域名列表应该可以，不过我想另一种更简单的办法，支持导出内存中的verdict cache到一个文本文件，并支持从该文件导入verdict cache。感觉这个代码量会很少一些。因为域名列表涉及最多8个group(2个内置+6个自定义)，单重载某个group的列表是不可行的，因为所有group的域名列表都加载到同一个数据结构中，二重载本质上就是先从结构中删除oldlist.txt的数据，然后载入newlist.txt的数据，但由于加载顺序的存在，导致单纯reload某个group不好实现，不如reload全部group的列表。但这样的话，我觉得不如换个思路，支持导入和导出verdict cache。

如果导入和导出verdict cache可满足需求，这几天应该可以实现，我可以先放一放todo重构的任务。

**Comment by InspoOnU** [comment]
两种都可以满足需求，本来以为reload更容易实现一些。

**Comment by zfl9** [comment]
reload域名列表的实现方案就是reload全部group的列表，但有个小问题，就是启动时传递给chinadns-ng的命令行参数/配置文件中的域名列表文件可能已经无法再访问，比如有些域名列表时通过脚本生成的，通过shell重定向等魔法实现一个临时文件。

**Comment by InspoOnU** [comment]
> reload域名列表的实现方案就是reload全部group的列表，但有个小问题，就是启动时传递给chinadns-ng的命令行参数/配置文件中的域名列表文件可能已经无法再访问，比如有些域名列表时通过脚本生成的，通过shell重定向等魔法实现一个临时文件。

这种情况比较少见，报错就可以了。reload命令是手动的，一般会先保证文件可以访问

**Comment by zfl9** [comment]
reload域名列表还有个小问题，由于chinadns并没有在某处存储各group的域名列表文件路径，所以只能重新解析整个配置文件和命令行参数。有点小蹩脚。还是verdict cache导入导出方案吧，简单，直截了当。

**Comment by zfl9** [comment]
#183
