### ISSUE TITLE
服务参数改成配置文件时遇到的一些No such file or directory错误

### ISSUE THREAD

**Issue by jdnt** [zfl9/chinadns-ng#184]
之前是写在服务参数里，这样调整配置时都要reload一下比较麻烦，改成配置文件会方便很多，不过遇到一些小问题：
![image](https://github.com/user-attachments/assets/3a621831-7bfb-4a5b-b5a5-c9a57d52c1d6)

![image](https://github.com/user-attachments/assets/bbb17745-00a0-4d2c-a575-69e10b8f1a40)

配置文件为

![image](https://github.com/user-attachments/assets/6cb35195-5f31-46e0-9f42-85fdb4c49199)

照着原来的参数改的配置，不知道哪些地方设置错了，请大佬指正。

**Comment by zfl9** [comment]
和“是否改为配置文件形式”没关系，报错是因为 ipset 未创建。仔细看报错的模块（ipset.c）。

根据你给的配置：
- tag:chn 的 ip 将添加到 ignip、ignip6 集合
- tag:gfw 的 ip 将添加到 gfwip、gfwip6 集合
- tag:none 的 ip 测试数据库为 chnroute、chnroute 集合

请确保这些 ipset 已存在，对于 chnroute/chnroute6，请导入项目 res 目录下的 *.ipset 文件。

**Comment by zfl9** [comment]
如果你不需要“收集某些 tag 的解析结果 IP”，请注释掉相关配置（`add-tag*-ip`）。

我看你配置了 default-tag gfw，因此 ipset-name4 和 ipset-name6 是不需要的，不用导入 chnroute*.ipset。

还有，在配置了 `default-tag gfw` 的情况下，并不需要 `gfwlist-file` 配置行，这是无用且多余的，浪费内存。

**Comment by jdnt** [comment]
明白了，感谢大佬耐心解答！已修改，问题解决。
