### ISSUE TITLE
release中没有mips64架构的版本

### ISSUE THREAD

**Issue by airlychee** [zfl9/chinadns-ng#188]
可否帮忙编译一个，不胜感激！

**Comment by zfl9** [comment]
先试试mips的能不能用？

**Comment by zfl9** [comment]
估计是，我琢磨下如何编译 mips64（主要是 zig 0.10.1 有个文件缺少 mips64 支持）

发一下 mips64 上的 `uname -a` 信息？另外你下载的是那个 release 文件（文件名发一下）。

**Comment by airlychee** [comment]
uname -a
Linux USG-3P 3.10.107-UBNT #1 SMP Thu Jan 12 08:28:15 UTC 2023 mips64 GNU/Linux

之前下载的是
[chinadns-ng+wolfssl@mips-linux-musl@mips32@fast+lto](https://github.com/zfl9/chinadns-ng/releases/download/2024.07.21/chinadns-ng+wolfssl@mips-linux-musl@mips32@fast+lto)


感谢

2.0以前的版本用了一年多了，非常稳定

**Comment by zfl9** [comment]
@airlychee 你需要 tls 上游吗？普通版本我已经构建成功了，但是 wolfssl 构建失败。

**Comment by airlychee** [comment]
就是为了tls才想起来更新的…感谢大佬

**Comment by zfl9** [comment]
你的 mips64 机器是否有 硬浮点？

**Comment by zfl9** [comment]
上传了 release 页面（硬浮点版本的），下载试试。

**Comment by airlychee** [comment]
非常感谢，我先测试一下，我也不知道我的机器有没有硬浮点

**Comment by airlychee** [comment]
经测试，硬浮点、软浮点均可正常运行

**Comment by zfl9** [comment]
OK，感谢测试。
