### ISSUE TITLE
可以增加一个测速优选功能吗？

### ISSUE THREAD

**Issue by muziling** [zfl9/chinadns-ng#190]
类似这个功能： https://pymumu.github.io/smartdns/config/check-speed-mode/ ，比如仅对海外DNS返回的每个IP，测速延迟超过N秒，则丢弃此IP，不是timeout不丢弃，如果被全丢弃，则采用国内DNS
tcp测速有现成的开源工具，比如tcping  paping

第三方的视频网站(https://anime.girigirilove.com/)， 用海外DNS解析经常打不开，运营商的DNS解析能快速打开。  网站的IP地址是非国内IP段。

原先一直以为是网站有问题，昨天偶然发现是自己DNS解析只采用国外DNS结果导致的。

可能还有很多网站有这种问题， 如果能加个测速功能，应该可以有效避免

**Comment by zfl9** [comment]
不打算加测速。对于你说的这个问题，建议收集相关域名到一个单独组，然后用运营商的 DNS 去解析。

**Comment by muziling** [comment]
没办法收集，相当于以后只要碰到打不开或者打开慢的网站，我都要手动试一下运营商的解析打开速度

**Comment by zfl9** [comment]
这种情况还是比较少吧，问题不大。

目前也确实没有时间做这些。

**Comment by zfl9** [comment]
verdict-cache dump 可能对查询此类 tag:none 域名有所帮助（开启`verdict-cache`，`verdict-cache-db`开不开都行）

- 当某个网站打开慢或者无法访问时，给 chinadns-ng 发送 SIGUSR1 信号，导出 verdict 缓存
- 然后检查 `/tmp/chinadns@verdict-cache.db` 或 `--verdict-cache-db` 指定的 db 路径
- 文件的每行都是一个域名，1 开头的表示该域名采纳了 china 结果，0 开头表示采纳了 trust 结果
- 然后将这里面你觉得可能有问题的域名提取出来，放到一个域名列表.txt，尝试使用与之相反的上游 DNS
- 比如，db 文件显示相关域名采纳了 trust 结果，那就尝试用 china 上游解析这些域名，看看如何
