### ISSUE TITLE
no ipv6对group没生效，是我配置有问题吗？

### ISSUE THREAD

**Issue by muziling** [zfl9/chinadns-ng#195]
```
group chinamobile
group-dnl /etc/chinadns-ng/group_chinamobile.txt
group-upstream 223.5.5.5
no-ipv6 tag:gfw,tag:chn

```

/etc/chinadns-ng/group_chinamobile.txt 内容为
```
.chinamobile.com
```

解析 ottrrs.hl.chinamobile.com 的时候得不到ipv6地址，
另外 group-upstream 223.5.5.5 要写成 group-upstream udp://223.5.5.5  吗，不写会去请求tcp？

**Comment by zfl9** [comment]
不带协议限定的upstream是udp+tcp协议，也就是说，若客户端通过x访问chinadns-ng，则chinadn-ng也通过x访问该upstream。x指tcp或者udp。具体在readme有说明。

udp://上游和tcp://上游就是字面意思，用udp访问或者tcp访问。

**Comment by muziling** [comment]
就是可以指定，也可以不指定，对吧
