### ISSUE TITLE
为什么 "-Dtarget=native-native-musl" 无法编译成功？

### ISSUE THREAD

**Issue by sgon00** [zfl9/chinadns-ng#196]
您好，编译环境是 Ubuntu 24.04，zig版本是文档建议使用的：

```
$ zig version
0.10.1
```

我对zig很陌生，文档中提到了在本机编译的两种方法：

```
# 本机
zig build # 链接到glibc
zig build -Dtarget=native-native-musl # 静态链接到musl
```

如果使用单纯链接到glibc的方法编译是可以成功的，比如运行 `zig build -Dwolfssl`，可以生成一个文件 `./zig-out/bin/chinadns-ng+wolfssl@x86_64-linux-gnu.2.39@znver3+native@fast+lto`

但如果选择第二种方式链接到musl，运行 `zig build -Dtarget=native-native-musl -Dwolfssl`，就会遇到如下的错误：

```
checking host system type... Invalid configuration `native-native-musl': machine `native-native' not recognized
```

不确定哪里做错了？ 打扰了，谢谢您。

**Comment by zfl9** [comment]
“本机”编译可能有 bug，无法正确检测到当前是什么 Arch/OS。

如果遇到问题，建议选后面的“为 x86_64 目标构建”（或者其他目标架构）。

提醒一下，除非真的有必要，否则不建议自己编译，去 releases 页面下载吧。

**Comment by sgon00** [comment]
了解，非常感谢您的回复。关闭issue
