### ISSUE TITLE
chinadns-ng安装问题。

### ISSUE THREAD

**Issue by lmhdrive** [zfl9/chinadns-ng#198]
请问大佬[chinadns-ng]的安装方式和原来不一样了，需要用zig了，纯业余玩，不太会用这些编程平台，按readme中的步骤编译完成后在zig-out/bin/目录下生成了chinadns-ng，这个文件也无法使用。请问该如何安装？readme中能否写的详细点儿。

**Comment by zfl9** [comment]
去 releases 页面下载预编译的文件。

自己编译和预编译的没区别，当搞不定编译的时候，就不需要浪费时间折腾编译了。

**Comment by lmhdrive** [comment]
就是预编译的文件，怎么运行啊？不是deb不会安装。不知道这些区别在哪儿？
![2024-08-29_222905](https://github.com/user-attachments/assets/6f270b60-e772-4c37-8697-62fa779d39e6)
![2024-08-29_222946](https://github.com/user-attachments/assets/31322c6a-2b60-4923-8e1b-7404f20bfc81)

**Comment by zfl9** [comment]
下载对应架构的 chinadns-ng 文件，进行适当的重命名（如果需要），然后 `chmod +x` 添加可执行权限，然后运行即可。

**Comment by zfl9** [comment]
区别在 releases 页面中有说明，简单来说，就是 x86_64 v1 ~ v4 的区别，现代 x86_64 CPU 一般都是 v3 了，老一点的是 v2，再老点的就是 v1（不带 v 字眼的），如果有疑问，可以 百度、Google 搜索 x86_64 微架构级别（x86_64 v1 v2 v3 v4 什么区别，如何确定我的 CPU 是 v几）。

**Comment by zfl9** [comment]
这个不是 deb 文件，这是可执行文件，下载后，执行 `chmod +x chinadns-ng*` 给予它可执行权限，然后运行就好了呀，有这么难理解吗？使用过 Linux 系统的都明白吧。。。

**Comment by lmhdrive** [comment]
哦，明白了，感谢！我还以为是安装包呢。

**Comment by zfl9** [comment]
基本常识：在 Unix 世界中，如果一个文件没有后缀名（比如 .txt），那么就是可执行文件（ELF文件、Shell脚本等），`chmod +x` 之后即可运行。

**Comment by lmhdrive** [comment]
> 区别在 releases 页面中有说明，简单来说，就是 x86_64 v1 ~ v4 的区别，现代 x86_64 CPU 一般都是 v3 了，老一点的是 v2，再老点的就是 v1（不带 v 字眼的），如果有疑问，可以 百度、Google 搜索 x86_64 微架构级别（x86_64 v1 v2 v3 v4 什么区别，如何确定我的 CPU 是 v几）。
> 
> 这个是向后兼容的，也就是若目标 CPU 支持 x86_64 v4，则可以运行 x86_64(v1)、x86_64_v2、x86_64_v3、x86_64_v4 版本的 ELF 文件。若希望性能最佳，请选择目标 CPU 支持的最高级别。如果不想关注这些，能用就行，那就无脑选 x86_64（不带v的）。

x86_64我都试了，无法运行，显示command not found,系统是Debian 12.6
![2024-08-30_203645](https://github.com/user-attachments/assets/c969461a-6e8b-4955-8f3f-12b33e38da34)

**Comment by lmhdrive** [comment]
直接运行，真的是无法运行。不知道咋回事。

**Comment by zfl9** [comment]
有没有一种可能，要使用 ./chinadns-ng。这是基本常识

**Comment by zfl9** [comment]
要不就把 可执行文件 放到 /usr/local/bin 等 PATH 路径下。

**Comment by lmhdrive** [comment]
服了。你真厉害！感谢大佬，我水平欠佳，以后多向你！
