### ISSUE TITLE
OpenWRT 上编译错误

### ISSUE THREAD

**Issue by LitingLin** [zfl9/chinadns-ng#20]
`root@OpenWrt:~/chinadns-ng# make
gcc -std=c99 -Wall -Wextra -O3 -c chinadns.c -o chinadns.o
chinadns.c: In function 'parse_command_args':
chinadns.c:210:42: error: 'PATH_MAX' undeclared (first use in this function)
                 if (strlen(optarg) + 1 > PATH_MAX) {
                                          ^
chinadns.c:210:42: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:23: chinadns.o] Error 1`

chinadns.c 里加了 `#include <linux/limits.h>` 就通过了

**Comment by zfl9** [comment]
感谢提醒。待会加上。

**Comment by zfl9** [comment]
已加上。

**Comment by LitingLin** [comment]
感谢
