### ISSUE TITLE
docker 多平台下 armv7无法完成编译

### ISSUE THREAD

**Issue by YahuiWong** [zfl9/chinadns-ng#207]
linux/arm下使用命令：
```zig build -Dtarget=arm-linux-musleabi -Dcpu=generic+v7a```
返回 
```
11.05 thread 14 panic: TODO implement bigint to llvm int for 32-bit compiler builds
11.05 Unable to dump stack trace: debug info stripped
12.75 Aborted (core dumped)
```
但是在 linux/arm64 下 使用 `zig build -Dtarget=aarch64-linux-musl ` 可以完成构建 

代码地址：https://github.com/YahuiWong/chinadns-ng.git

**Comment by zfl9** [comment]
不建议自己编译，因为 zig 0.10.1 基本只在 x86_64 上能稳定运行。除非你改了源码，否则自己编译毫无意义。
