### ISSUE TITLE
反炸ip是国内ip，readme中污染ip一定是国外ip的假设是不是解决不了反炸页面？

### ISSUE THREAD

**Issue by maggch97** [zfl9/chinadns-ng#210]

**Comment by zfl9** [comment]
是的，但 IP 判定是 tag:none 域名（即：未匹配任何列表的域名）的逻辑，即最后的手段。

如果你要处理“反z”污染，请收集相关域名，用一个自定义group去单独解析（使用你认为无污染的上游dns）。
