### ISSUE TITLE
允许为每个域名组设定单独的 no-ipv6 规则

### ISSUE THREAD

**Issue by ellermister** [zfl9/chinadns-ng#212]
你好, 我目前的配置是基于 chnroute 分流，即 CN 直连，其他走代理。
同时配置了 `no-ipv6 ip:non_china` 来屏蔽海外很慢网站的 IPV6，解决慢路由、或代理服务器不支持 IPV6 等情况。

但在此基础上，我又希望加入一些白名单域名。
比如一些 PT tracker 地址是走的海外的 CF CDN.

我希望它解析出的IPV4和IPV6都能直连且正确返回IPV6.
现在解析直连可以通过自定义组解决
```
group white
group-dnl /etc/chinadns/white.txt
group-upstream 1.0.0.1
group-ipset whiteip
```

但是IPV6最终还是被  `no-ipv6 ip:non_china` 忽略了，有没有什么简单的办法解决类似的问题呢?

简而言之：有没有办法 no-ipv6 有没有办法实现 and/! 条件配置, 或者在这个配置前增加一条白名单域名绕过?

**Comment by zfl9** [comment]
好问题，确实可以再细化 ip:* 规则的作用范围。

我的初步想法：
- 原先的 ip:china、ip:non_china 规则作用于 **所有** 域名
- **新增**细化规则：`ip:*@tag:*` 仅针对给定 tag（组）的域名进行 ipv6 filter。

修改后，通过将 no-ipv6 规则设定为：`no-ipv6 ip:non_china@tag:chn ip:non_china@tag:gfw ip:non_china@tag:none` 即可实现你的目标。

**Comment by ellermister** [comment]
好的，感谢。

不过我没有太理解，可能对于我来说。实现忽略解析海外IPV6（但不忽略白名单的域名）。
配置可能如下？
```
# 过滤海外gfw列表域名。（其实我现在用的就是类似 `no-ipv6 tag:gfw`，可能会漏一些域名，勉强够用。）
no-ipv6 ip:non_china@tag:gfw

# 过滤海外其他没有在任何 tag 中的域名/IP？
no-ipv6 ip:non_china@tag:none
```

# 这个我没太理解，为什么会存在：海外IP 和 chn(大陆) 有交集的IP?
```
no-ipv6 ip:non_china@tag:chn
```

**Comment by zfl9** [comment]
你是对的，考虑到 tag:chn 组都是大陆域名（解析结果肯定也是大陆 IPv4/IPv6）；
所以 `ip:non_china@tag:chn` 没有实际意义。当然，增加此规则也不会有什么影响。

**Comment by zfl9** [comment]
功能已添加，但是调换了一下位置 `ip:*@tag:*` -> `tag:*@ip:*`。具体说明见 readme。

因为这个功能的本质是给每个域名组单独设定 no-ipv6 过滤规则，所以在程序内部，每个域名组都配有一个独立的过滤器。

> 正在编译 release 版本。

**Comment by ellermister** [comment]
@zfl9 
感谢你的更新，不过抱歉我好像没搞懂怎么去配置规则。

感觉应该是要配置
```
no-ipv6 tag:gfw
no-ipv6 tag:none@ip:white
```

不知道 `tag:*@ip:*`  配置是取交集还是取差集。
如果是取交集，似乎无法实现我从 ip:non_china / gfw+none 域名里 排除一个。
取差集的话，又报错。
```
# /usr/bin/chinadns --config /etc/chinadns/config.conf
[ip6_filter.zig:53 IP6Filter.add_rule] invalid rule: 'ip:white'                  
[opt.zig:427 opt_no_ipv6] invalid opt-value: 'tag:none@ip:white'
```
看代码好像只支持这 3 个预设的IP组：ip:china/ip:non_china/null
```
    /// `null` means all_query
    pub fn add_rule(filter: *IP6Filter, rule: ?[]const u8) ?void {
        if (rule == null) {
            filter.china_ip = true;
            filter.non_china_ip = true;
        } else if (std.mem.eql(u8, rule.?, "ip:china")) {
            filter.china_ip = true;
        } else if (std.mem.eql(u8, rule.?, "ip:non_china")) {
            filter.non_china_ip = true;
        } else {
            opt.print(@src(), "invalid rule", rule.?);
            return null;
        }
```

如果配置成多个,或是(不存在于任何 tag 的域名 交于 非大陆的 IP = 间接排除了 white.txt )，d但好像没生效
```
no-ipv6 tag:none@ip:non_china
no-ipv6 tag:gfw
```

white.txt 里面的域名都能解析出IPV6，且 IP 地址都是海外的。

**Comment by zfl9** [comment]
你似乎想复杂了，首先我们以 group（域名组） 为基本单位，每个 group 的 ip6 filter 逻辑互相独立，互不影响。

当查询某个域名的 AAAA 记录时，chinadns-ng 首先在域名列表中匹配，拿到域名所属的 group，然后获取该 group 的 ip6 filter 过滤器：

- 如果 china_ip, non_china_ip 都为 false（这是每个过滤器的默认配置），则不进行过滤
- 如果 china_ip，non_china_ip 都为 true，则说明所有 AAAA 都过滤，不需要送给 upstream 去解析
- 如果 china_ip 或 non_china_ip 其中之一为 true，则送给 upstream 去解析，拿到 reply，对 ip 进行 test，根据结果进行过滤

> 我自己在本地测试了，应该是没有问题的。

---

因此，你最后给出的 no-ipv6 规则是正确的

```
# 在 tag:none 组中，过滤 非大陆IP 的 AAAA 响应
no-ipv6 tag:none@ip:non_china

# 在 tag:gfw 组中，过滤所有 AAAA 查询
no-ipv6 tag:gfw
```

**Comment by zfl9** [comment]
> 不知道 `tag:*@ip:*` 配置是取交集还是取差集。

并不是取交集、差集。

- tag:* 是选择器，表示后面的 ip:* 规则将要添加到哪个 group 中。
- 如果缺少 tag:*（未指定选择器），则对所有的 group 都添加后面的 ip:* 规则。
- 如果省略 ip:*，则表示无条件过滤该组的所有 AAAA 查询。

**Comment by ellermister** [comment]
感谢，已经测试成功了。

**Comment by muziling** [comment]
readme里的 `条件`可以举一些例子吗，看的不太明白

**Comment by zfl9** [comment]
> > 不知道 `tag:*@ip:*` 配置是取交集还是取差集。
> 
> 并不是取交集、差集。
> 
> * `tag:*` 是选择器，表示后面的 `ip:*` 规则将要 **添加** 到哪个 group 中。
> * 如果缺少 `tag:*`（未指定选择器），则对所有的 group 都 **添加** 后面的 `ip:*` 规则。
> * 如果省略 `ip:*`，则表示 **无条件过滤** 该 group 的所有 AAAA 查询。
> * 每个 group 的过滤器初始都是空状态，也即不过滤任何 AAAA 查询/响应。
> * `ip:*` 只有两种情况：`ip:china` 若测试结果为大陆IP，则过滤；`ip:non_china`，若测试结果为非大陆IP，则过滤。
> 
> 任何一个 query/reply 都属于某个 group（根据域名列表匹配得知），处理 no-ipv6 逻辑时，只会获取该 group 的过滤器配置，根据配置进行过滤。这实际上类似于 `group-*` 配置，每个 group 的 no-ipv6 配置都是独立的，只作用于该 group 的域名的 AAAA 查询/响应。
> 
> > 在 readme 的 no-ipv6 一节也有详细说明。

看这里，ip:条件 就是上文中的 ip:*，只有两种情况。

**Comment by muziling** [comment]
就是条件只有3种情况
1、星号
2、group名
3、`non_`加group名
是吧。OK，最好更新到readme里，要不还要翻issue才知道怎么用
