### ISSUE TITLE
再次建议加入socks客户端

### ISSUE THREAD

**Issue by lwb1978** [zfl9/chinadns-ng#213]
目前我们在设计科学插件时如果采用chinadns-ng时，可信dns需要通过透明代理后再经节点出站，中间走了一些弯路。在设计访问控制时，可能用户还会设置不同的客户端走不同的节点出国，那么就需要不同客户端的可信dns走不同的节点出站，最简便高效的就是直连节点的socks，目前访问控制需要在chinadns前套一层dns2socks或者sing-box、xray进行转发，多了一个中间件，也不太优雅。所以再次建议作者再考虑一下加入socks客户端，并可以为每个分组单独设置是否启用socks访问。
祝好！

**Comment by zfl9** [comment]
等后面有空再说哈。

**Comment by lwb1978** [comment]
轻轻的催更一下。

**Comment by zfl9** [comment]
等我把 chinadns-ng 的 Zig 版本更到最新先~
