### ISSUE TITLE
感谢创造如止神器

### ISSUE THREAD

**Issue by hleungg** [zfl9/chinadns-ng#22]
我希望能在DOCKER中运行它，能否生成一下DOCKER映像？

**Comment by zfl9** [comment]
对docker不熟，暂时无能为力。:sweat_smile:

**Comment by hleungg** [comment]
有走过路走懂DOCKER的兄弟造一下吗。。。。。

**Comment by pexcn** [comment]
参考一下一些其他项目自己做一个吧，例如：
https://github.com/9seconds/mtg/blob/master/Dockerfile
https://github.com/shadowsocks/shadowsocks-libev/tree/master/docker/alpine
