### ISSUE TITLE
有俩网址，原版没问题，但是chinadns-ng就不行？该怎么设置，哪里的问题呀？

### ISSUE THREAD

**Issue by qwerttvv** [zfl9/chinadns-ng#28]
版本是最新的ChinaDNS-NG v1.0-beta.15

跑在路由器上的，配合ss的dnsmsq，ss是gfwlist模式

这两个网址，同样跑在路由器上原版chinadns使用服务器`202.106.195.68,202.106.46.151,dns.google`可以打开
https://cn.wsj.com/
https://cn.nytimes.com/

ss没有改动任何配置情况下ng版打不开这俩网址，试了下边这几个参数都打不开

- `-g /opt/app/chinadns_ng/gfwlist.txt`
- `-g /opt/app/chinadns_ng/gfwlist.txt -f`
- `-f`
- 空，没加任何参数

gfwlist是采用https://github.com/gfwlist/gfwlist ，包含
`.nytimes.com`
`||nytimes.com`
`.wsj.com`
`||wsj.com`

然后ng版本，测试访问google，youtube正常

**Comment by qwerttvv** [comment]
nslookup

这是ng版

    非权威应答:
    名称:    d2kh1exwe9sgh.cloudfront.net
    Addresses:  2600:9000:201f:7c00:3:bbf5:9440:93a1
              2600:9000:201f:7a00:3:bbf5:9440:93a1
              2600:9000:201f:f400:3:bbf5:9440:93a1
              2600:9000:201f:4000:3:bbf5:9440:93a1
              2600:9000:201f:3000:3:bbf5:9440:93a1
              2600:9000:201f:4200:3:bbf5:9440:93a1
              2600:9000:201f:6800:3:bbf5:9440:93a1
              2600:9000:201f:2200:3:bbf5:9440:93a1
              13.226.219.127
              13.226.219.38
              13.226.219.117
              13.226.219.10
    Aliases:  cn.wsj.com

    非权威应答:
    名称:    d1emgxxou2di91.cloudfront.net
    Addresses:  2600:9000:201f:2800:18:9b35:e940:93a1
              2600:9000:201f:9c00:18:9b35:e940:93a1
              2600:9000:201f:2a00:18:9b35:e940:93a1
              2600:9000:201f:5e00:18:9b35:e940:93a1
              2600:9000:201f:a000:18:9b35:e940:93a1
              2600:9000:201f:9400:18:9b35:e940:93a1
              2600:9000:201f:5c00:18:9b35:e940:93a1
              2600:9000:201f:c800:18:9b35:e940:93a1
              13.226.238.15
              13.226.238.36
              13.226.238.82
              13.226.238.97
    Aliases:  cn.nytimes.com



这是原版


    非权威应答:
    名称:    cn.wsj.com
    Addresses:  2001::43e4:251a
              99.84.143.44
              99.84.143.34
              99.84.143.22
              99.84.143.94

    非权威应答:
    名称:    cn.nytimes.com
    Addresses:  2001::4a7d:9b8b
              13.225.176.77
              13.225.176.124
              13.225.176.20
              13.225.176.10

ng默认不就是8.8.8.8吗？和我设置原版dns.google不是一样？

我启用原版，设置8.8.8.8，结果是一样的

我糊涂了……

**Comment by zfl9** [comment]
你在说啥？请表述清楚！

**Comment by zfl9** [comment]
你的chinadns-ng使用的gfwlist文件是这样的？
> gfwlist是采用https://github.com/gfwlist/gfwlist ，包含
> .nytimes.com
> ||nytimes.com
> .wsj.com
> ||wsj.com

**Comment by qwerttvv** [comment]
https://cn.wsj.com/
https://cn.nytimes.com/
这俩网址chinadns原版和ng版本，返回结果不一样？都是8.8.8.8

不是不是，，ng的gfwlist文件包含nytimes.com和.wsj.com，我开始说错了，

**Comment by zfl9** [comment]
请注意，chinadns-ng 的 gfwlist/chnlist 文件包含的是按行分隔的域名模式，格式如下：
```
baidu.com
www.baidu.com
test.www.baidu.com
```
不以 `.` 开头，不以 `.` 结尾，这两种模式都会被忽略。

**Comment by zfl9** [comment]
补充，过短的会被忽略，如
```
com
```
另外，过长的会被截断，如
```
abc.test.www.baidu.com
```
等价于
```
test.www.baidu.com
```

**Comment by zfl9** [comment]
麻烦给出 chinadns 与 chinadns-ng 的相关运行参数以及相关的文件
> 这俩网址chinadns原版和ng版本，返回结果不一样？都是8.8.8.8

**Comment by zfl9** [comment]
以及测试过程，以及相关日志文件，实验环境，对比过程，等等。如果没有，我将关闭此issue。

**Comment by qwerttvv** [comment]
跟chinadns-ng没啥关系，我大概闹清楚咋回事儿了，可以参考

https://github.com/pymumu/smartdns/issues/324
和
https://github.com/shadowsocks/shadowsocks-libev/issues/2605
