### ISSUE TITLE
需求建议

### ISSUE THREAD

**Issue by bitching** [zfl9/chinadns-ng#29]
由于某些原因我希望用sniproxy来实现(半)透明代理。
sniproxy运行在VPS上，局域网里某台机器443端口tunnel到sniproxy上。
希望能实现若国内DNS的解析结果`是国外IP/不在ipset`里，则返回`自定义IP`，不需要去跟可信DNS解析。
不知道是否方便实现？

**Comment by zfl9** [comment]
暂无时间。

**Comment by bitching** [comment]
好吧。阅读文档之后多跑了一个dnsmasq的instance，将任意域名解析成局域网ip，利用chinadns-ng的fair-mode变相实现了。
如有可能还是希望能从chinadns-ng内部实现。
