### ISSUE TITLE
googleapis.cn的域名解析为污染地址

### ISSUE THREAD

**Issue by om2mo** [zfl9/chinadns-ng#30]
log dump
query [services.googleapis.cn] from 127.0.0.1#53351
[handle_remote_packet] reply [services.googleapis.cn] from 114.114.114.114#53, result: accept
[handle_remote_packet] reply [services.googleapis.cn] from 127.0.0.1#5300, result: ignore

googleapis.cn解析发送给了国内DNS。

root@OpenWrt:~/chinadns-ng-latest# dig services.googleapis.cn @127.0.0.1 -p 5300

; <<>> DiG 9.14.8 <<>> services.googleapis.cn @127.0.0.1 -p 5300
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41291
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;services.googleapis.cn.		IN	A

;; ANSWER SECTION:
services.googleapis.cn.	299	IN	A	74.125.200.94

127.0.0.1#5300为可信DNS，因为cn后缀没有转发给它，所以我还还要在dnsmasq中单独添加一条/googleapis.cn/127.0.0.1#5300

**Comment by zfl9** [comment]
额，你其实只需要在 gfwlist.txt 里面删掉 googleapis.cn 这条就行了。何必这么做呢

**Comment by zfl9** [comment]
@om2mo

**Comment by zfl9** [comment]
哦不对，看log，你似乎没有启用 gfwlist.txt 或者 chnlist.txt。运行参数发上来 @om2mo

**Comment by zfl9** [comment]
说错了，其实你只需要启用 gfwlist 匹配列表就行了。即可完美解决。 @om2mo

**Comment by zfl9** [comment]
> 因为cn后缀没有转发给它

其实不是因为域名啥后缀，chinadns-ng只是检测到114返回的是国内ip罢了。总之启用 gfwlist 列表匹配就可以解决了。自己可以试试。

**Comment by om2mo** [comment]
> 说错了，其实你只需要启用 gfwlist 匹配列表就行了。即可完美解决。 @om2mo
gfwlist模式下这个域名也没有走可信DNS，不过我只是为了测试一下，不在gfw list的很多网站都打不开，通常我只用chnroute。
 chinadns-ng -l 5354 -t 127.0.0.1#5300 -m /root/chinadns-ng-latest/gfwlist.txt -v
[handle_local_packet] query [services.googleapis.cn] from 127.0.0.1#61276
[handle_remote_packet] reply [services.googleapis.cn] from 114.114.114.114#53, result: accept

root@OpenWrt:~/chinadns-ng-latest# dig services.googleapis.cn

; <<>> DiG 9.14.8 <<>> services.googleapis.cn @127.0.0.1 -p 5354
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 573
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;services.googleapis.cn.		IN	A

;; ANSWER SECTION:
services.googleapis.cn.	52	IN	A	203.208.40.95
services.googleapis.cn.	52	IN	A	203.208.40.87
services.googleapis.cn.	52	IN	A	203.208.40.88
services.googleapis.cn.	52	IN	A	203.208.40.79

**Comment by zfl9** [comment]
你逗我呢，-m 指定的是 chnlist，-g 才是 gfwlist。
