### ISSUE TITLE
-4, --ipset-name4 <ipv4-setname> 这个参数不使用也是默认在用吗?

### ISSUE THREAD

**Issue by blog2i2j** [zfl9/chinadns-ng#32]
请教作者

-4, --ipset-name4 <ipv4-setname>     ipset ipv4 set name, default: chnroute
说明文档中说该参数默认是 chnroute, 如果我在命令行中不使用-4, 程序也是默认使用chnroute的吗? 还是说命令行中没有-4 就不使用ipset了? 只是在用-4 不指定<ipv4-setname>时默认chnroute?

我想问的意思是是不是不管命令行有没有-4的参数, 这个ipset都是起作用的?

**Comment by zfl9** [comment]
ipset 始终是必须的，只有 gfwlist/chnlist 是可选的。即：
- 未指定 -4 选项，则默认使用 chnroute 这个 ipset
- 指定了 -4 选项，但未提供选项值，则直接启动报错
- 指定了 -4 选项，且选项值为 chnroute，则同默认情况
- 指定了 -4 选项，且选项值为 xxx，则使用 xxx 这个 ipset
