### ISSUE TITLE
dnsutils.c 似乎和centos 6不兼容？

### ISSUE THREAD

**Issue by sanigo** [zfl9/chinadns-ng#33]
2020-03-03 20:03:23 ERR: [dns_qheader_check] this is a query packet, but header->qr != 0
2020-03-03 20:03:28 ERR: [dns_qheader_check] this is a query packet, but header->qr != 0
2020-03-03 20:03:33 ERR: [dns_qheader_check] this is a query packet, but header->qr != 0
完全无法解析，修改dns_qheader_check函数，直接return true倒是可以绕过

**Comment by zfl9** [comment]
估摸着应该是大小端的检测问题。

**Comment by zfl9** [comment]
你的电脑是大端还是小端？

**Comment by zfl9** [comment]
大概知道了，gcc提供的检测大小端的宏不可靠，看来错怪之前那位老哥了，抱歉抱歉。@hiboyhiboy

我改一下代码吧，include 一下 `<endian.h>` 头文件，这里面有预定义的宏可检测大小端。

**Comment by zfl9** [comment]
@sanigo 试一下最新的提交？

**Comment by sanigo** [comment]
好的，我试试看看

**Comment by sanigo** [comment]
这个好使， @zfl9

**Comment by zfl9** [comment]
好的。

**Comment by sanigo** [comment]
> 你的电脑是大端还是小端？

X86_64，应该是小端吧？

**Comment by XenMe** [comment]
今天刚好也碰到了，估计还是兼容性问题
大小端确定小端，编译也没有任何问题，最后发现我用了一个常见端口5353，结果局域网小米电视会广播到这个端口，然后chinadns-ng就一直报这个错了

**Comment by zfl9** [comment]
> 今天刚好也碰到了，估计还是兼容性问题
> 大小端确定小端，编译也没有任何问题，最后发现我用了一个常见端口5353，结果局域网小米电视会广播到这个端口，然后chinadns-ng就一直报这个错了

你的这个问题和楼主的问题不一样。你这是非dns包发到了chinadns-ng监听端口而已。
