### ISSUE TITLE
如何为 arm_cortex-a9_vfpv3 编译此库？

### ISSUE THREAD

**Issue by qiaoyan** [zfl9/chinadns-ng#35]
不胜感激涕零

**Comment by zfl9** [comment]
?没懂，你找对应的编译工具链编译不就可以了？还是遇到什么编译错误。

**Comment by qiaoyan** [comment]
初次接触，不知如何做才能达到类似的效果？
` openwrt-dist 软件源安装方法：

添加软件源公钥

# wget http://openwrt-dist.sourceforge.net/packages/openwrt-dist.pub
# opkg-key add openwrt-dist.pub

添加软件源到配置文件，注意命令中 x86_64 替换为你的硬件架构

# vim /etc/opkg/customfeeds.conf
src/gz openwrt_dist http://openwrt-dist.sourceforge.net/packages/base/x86_64
src/gz openwrt_dist_luci http://openwrt-dist.sourceforge.net/packages/luci

安装 shadowsocks-libev、luci-app-shadowsocks

# opkg update
# opkg install shadowsocks-libev
# opkg install luci-app-shadowsocks`

**Comment by zfl9** [comment]
不知所云。

**Comment by wazzx** [comment]
> 初次接触，不知如何做才能达到类似的效果？
> ` openwrt-dist 软件源安装方法：
> 
> 添加软件源公钥
> 
> # wget http://openwrt-dist.sourceforge.net/packages/openwrt-dist.pub
> # opkg-key add openwrt-dist.pub
> 添加软件源到配置文件，注意命令中 x86_64 替换为你的硬件架构
> 
> # vim /etc/opkg/customfeeds.conf
> src/gz openwrt_dist http://openwrt-dist.sourceforge.net/packages/base/x86_64
> src/gz openwrt_dist_luci http://openwrt-dist.sourceforge.net/packages/luci
> 
> 安装 shadowsocks-libev、luci-app-shadowsocks
> 
> # opkg update
> # opkg install shadowsocks-libev
> # opkg install luci-app-shadowsocks`

我知道你的意思，你是想要现成的makeflie或者ipk

**Comment by wazzx** [comment]
> 不知所云。

大佬好难，其实我小白的时候也是这样问的，现在是大白了，差不多
