### ISSUE TITLE
-4 和 -6 参数能否支持完整的路径？

### ISSUE THREAD

**Issue by pexcn** [zfl9/chinadns-ng#4]
想在 OpenWrt 上面运行，指定那两个文件的完整路径
![1](https://user-images.githubusercontent.com/4590439/63639569-80034400-c6c7-11e9-88a6-fb828d152022.png)

**Comment by pexcn** [comment]
原来不是路径，看来是集合的名称。。

**Comment by zfl9** [comment]
是的，是ipset的集合名称，就是 `chnroute`、`chnroute6`，具体是什么名称看你的 chnroute.ipset、chnroute6.ipset 文件里面定义的 set name。

**Comment by zfl9** [comment]
默认参数等效于：
```
chinadns-ng -b 127.0.0.1 -l 65353 -c 114.114.114.114 -t 8.8.8.8 -4 chnroute -6 chnroute6 -o 5
```
