### ISSUE TITLE
关于trust-dns 的问题

### ISSUE THREAD

**Issue by bzzjh** [zfl9/chinadns-ng#40]
trust-dns 可以为本地的dnscrypt-proxy么？
我看readme里说访问可信DNS必须经过代理，不过我这里的trust-dns 是本地的dnscrypt-proxy（127.0.0.1:5753），应该是可以的吧？ 多谢！

**Comment by zfl9** [comment]
当然可以，只要可信dns没被污染，什么地址无所谓。

**Comment by bzzjh** [comment]
明白，多谢!!!

**Comment by bzzjh** [comment]
在请教一个问题，关于抢答模式和公平模式，可信 DNS是dnscrypt-proxy且有缓存的情况下，是否应该修改为公平模式呢?因为有缓存，查询时间应该是非常快，快于国内DNS的，这时候有可能chinadns-ng收到的回复结果是dnscrypt-proxy的回复且回复的ip是一个不同于本地DNS的结果，导致客户端访问速度不快，因为国内的DNS返回结果是离客户端最近的结果，而dnscrypt-proxy则不会。

**Comment by zfl9** [comment]
是的，理解正确。可信返回比国内返回早，就要启用公平模式。
