### ISSUE TITLE
failed: connection refused

### ISSUE THREAD

**Issue by thb007** [zfl9/chinadns-ng#43]
```
root@iZwz9d1rjhrzzxa4lsoi93Z:~# dig pixiv.net @127.0.0.1 -p 5360
;; Truncated, retrying in TCP mode.
;; Connection to 127.0.0.1#5360(127.0.0.1) for pixiv.net failed: connection refused.
```

```
root@iZwz9d1rjhrzzxa4lsoi93Z:~# dig pixiv.net @127.0.0.1 -p 5360

; <<>> DiG 9.10.3-P4-Debian <<>> pixiv.net @127.0.0.1 -p 5360
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44245
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;pixiv.net.                     IN      A

;; ANSWER SECTION:
pixiv.net.              168     IN      A       210.140.131.219

;; Query time: 5 msec
;; SERVER: 127.0.0.1#5360(127.0.0.1)
;; WHEN: Tue Mar 31 22:31:45 CST 2020
;; MSG SIZE  rcvd: 43
```

第一TCP查询失败，第二次才正常，怎么解决这中问题？
![A}$KPTIBX7DXN$~~@ZV8ZHJ](https://user-images.githubusercontent.com/17548936/78039183-608c7200-73a0-11ea-9a85-392730b2b44f.png)

**Comment by zfl9** [comment]
你倒是把日志发出来啊。

**Comment by thb007** [comment]
> 你倒是把日志发出来啊。

![PTYE22VU$D1}D_`J2 {N13A](https://user-images.githubusercontent.com/17548936/78146302-8e3aef00-7464-11ea-99cf-84e2a2450273.png)

**Comment by thb007** [comment]
![QN`JR((_T0{ P{GO10P`SLS](https://user-images.githubusercontent.com/17548936/78146409-b32f6200-7464-11ea-81d4-b5fe43e0e9e7.png)

**Comment by zfl9** [comment]
你的ipset都没导入。我怀疑你没看readme（不，你没看）。

**Comment by zfl9** [comment]
请先使用 ipset 导入对应的 chnroute、chnroute6 集合。

**Comment by thb007** [comment]
> 请先使用ipset导入对应的chnroute，chnroute6集合。
还是报错
![M5FA0K_2UFIXCB1$ZW1T$}X](https://user-images.githubusercontent.com/17548936/78357051-4e4e4600-75e3-11ea-9b04-1fb94cbf54c5.png)

**Comment by thb007** [comment]
![BE14HS((S(VX)YQ4VCJL_42](https://user-images.githubusercontent.com/17548936/78357906-dda82900-75e4-11ea-83e4-cea484ea5847.png)
超时

**Comment by thb007** [comment]
![}6K4_)}PNDOZX)WC@$LP@YY](https://user-images.githubusercontent.com/17548936/78358114-3aa3df00-75e5-11ea-9a97-1a20c88316da.png)
dig正常解析，但是一直显示[handle_timeout_event] upstream dns server reply timeout, unique msgid: 2019
![4OFMVSR_}E0IARS@QJ9~K_F](https://user-images.githubusercontent.com/17548936/78358203-5c9d6180-75e5-11ea-93f1-d873b471e759.png)

**Comment by zfl9** [comment]
解析正常就行了，这个超时不用管，就是一个普通的解析超时而已。应该是你的可信dns上游不稳定

**Comment by zfl9** [comment]
可以加上 `-p 3` 参数试试
