### ISSUE TITLE
交叉编译的文件不能运行

### ISSUE THREAD

**Issue by rwzsycwan** [zfl9/chinadns-ng#45]
我用entware的toolchain交叉编译出来的文件，在K3上不能运行，提示 -sh: ./chinadns-ng: not found 。编译过程中没有报错。

**Comment by zfl9** [comment]
`make clean && make CC=/path/to/xxx-gcc`

**Comment by zfl9** [comment]
如果还不行就是你的工具链与目标主机不对应。

**Comment by ilpl** [comment]
> 最终在entware下安装了make和gcc编译出来能运行了

能把编译好的chinadns-ng 发我一份吗? 我也是K3,   Email: hi.pinglin[a]gmail.com

**Comment by rwzsycwan** [comment]
> > 最终在entware下安装了make和gcc编译出来能运行了
> 
> 你好~ 能把编译好的chinadns-ng 发我一份吗? 我也是K3, Email: hi.pinglin[a]gmail.com,

发你了

**Comment by brainos233** [comment]
> 最终在entware下安装了make和gcc编译出来能运行了

我也遇到了这个问题，可否详细请教一下怎么做

**Comment by elxy** [comment]
参考这里：https://github.com/Entware/Entware/wiki/Using-GCC-for-native-compilation
