### ISSUE TITLE
讨论：一个关于国内、可信dns返回的处理的逻辑问题

### ISSUE THREAD

**Issue by cod1ingcoding** [zfl9/chinadns-ng#46]
当可信dns先返回，如果是国内ip，则结束此次回话，直接以这个国内ip作为标准。这里一个问题是，可能一些网站，国外解析线路都会解析到沿海（比如广东移动），来加速国外访问，这时候如果我是联通，可能访问就炸了。

**Comment by zfl9** [comment]
那你说怎么办。。

**Comment by zfl9** [comment]
你要访问速度的话请使用类似 smartdns 的工具作为 chinadns-ng 的上游，chinadns-ng不负责这些。

**Comment by zfl9** [comment]
https://github.com/zfl9/chinadns-ng#%E7%9B%B8%E5%85%B3%E8%AF%B4%E6%98%8E

**Comment by cod1ingcoding** [comment]
我只是提出问题讨论下，并没有冒犯的意思。

是否可以加入选项，让可信dns返回国内ip的时候，也可以等待国内dns返回的结果再做处理，如果国内dns返回也是国内，则以国内dns为准。

**Comment by zfl9** [comment]
> 让可信dns返回国内ip的时候，也可以等待国内dns返回的结果再做处理，如果国内dns返回也是国内，> 则以国内dns为准。

这个倒是可以实现。周末再弄。

**Comment by zfl9** [comment]
> 我只是提出问题讨论下，并没有冒犯的意思。

我也只是啰嗦几句，提问题时不要光撂下一个描述，也请给一个改进建议。

**Comment by cod1ingcoding** [comment]
> 这个倒是可以实现。周末再弄。

非常感谢🤝

**Comment by zfl9** [comment]
还没解决前先不关掉吧，不然我很容易忘记的

**Comment by pexcn** [comment]
> 我只是提出问题讨论下，并没有冒犯的意思。
> 
> 是否可以加入选项，让可信dns返回国内ip的时候，也可以等待国内dns返回的结果再做处理，如果国内dns返回也是国内，则以国内dns为准。

这个功能在 "公平模式" 里不是已经实现了？

**Comment by bzzjh** [comment]
> > 是否可以加入选项，让可信dns返回国内ip的时候，也可以等待国内dns返回的结果再做处理，如果国内dns返回也是国内，则以国内dns为准。
> 
> 这个功能在 "公平模式" 里不是已经实现了？

公平模式里只针对返回的国外ip有判断，返回的国内ip好像还是抢答模式的，默认抢答模式里好像都是国内国外的ip都是抢答的。
一个域名隶属于国外，解析出的是国内的ip还优先于国内dns返回。我好奇这样域名到底是啥，可以拿出我也试试。有很多这样的特殊域名吗？假如需要强制这个域名用国内dns去解析，那直接加白名单，假如默认白名单没有，可以手动写进去。这样也可以吧。

**Comment by zfl9** [comment]
仔细想了下，还是重新定义一下公平模式比较好。默认还是抢答模式。具体的：
- 抢答模式（默认）：假设国内dns始终先于可信dns返回。逻辑：如果国内dns返回的是国内ip，则接收此响应并结束会话；如果国内dns返回的是非国内ip，则丢弃此响应，等待可信dns返回，然后接受可信dns的响应，然后结束会话。这个逻辑其实还是没有变化，不展开讨论。
- 公平模式（可选）：假设大概率存在可信dns先返回的情况。逻辑：如果国内先返回，则走上述抢答模式逻辑；如果可信先返回，则等待国内dns返回后再进行上述抢答模式逻辑（先判断国内的响应，再判断可信的响应）。你们觉得如何，这样感觉更接近“公平”的意义。

**Comment by zfl9** [comment]
@cod1ingcoding 
@pexcn 
@bzzjh

**Comment by bzzjh** [comment]
个人愚见：
其实没必要把逻辑弄得这么复杂，目前的模式加上配合gfwlist和chnlist已经完全够用了，个人觉得既然有大神在维护gfwlist和chnlist我们为啥不去利用它呢，而去复杂化这种利用返回IP是否为国内还是国外、返回速度是快还是慢的判断逻辑呢？
逻辑越简单，出问题也越好判断，同时BUG也会越少。

**Comment by zfl9** [comment]
> 个人愚见：
> 其实没必要把逻辑弄得这么复杂，目前的模式加上配合gfwlist和chnlist已经完全够用了，个人觉得既然有大神在维护gfwlist和chnlist我们为啥不去利用它呢，而去复杂化这种利用返回IP是否为国内还是国外、返回速度是快还是慢的判断逻辑呢？
> 逻辑越简单，出问题也越好判断，同时BUG也会越少。

道理是这样没错，虽然有了gfwlist/chnlist，但是最原始的方式该优化还是优化下。也不算复杂吧，其实这样改了之后比原先简单点。

**Comment by bzzjh** [comment]
> > 个人愚见：
> > 其实没必要把逻辑弄得这么复杂，目前的模式加上配合gfwlist和chnlist已经完全够用了，个人觉得既然有大神在维护gfwlist和chnlist我们为啥不去利用它呢，而去复杂化这种利用返回IP是否为国内还是国外、返回速度是快还是慢的判断逻辑呢？
> > 逻辑越简单，出问题也越好判断，同时BUG也会越少。
> 
> 道理是这样没错，虽然有了gfwlist/chnlist，但是最原始的方式该优化还是优化下（毕竟不是所有域名都被gfwlist/chnlist覆盖了）。也不算复杂吧，其实这样改了之后比原先简单点。

那既然这样，默认就该是公平模式了，抢答模式就没有存在的需要了。

再次多谢作者的开源!

**Comment by zfl9** [comment]
> 那既然这样，默认就该是公平模式了，抢答模式就没有存在的需要了。

是的，我也准备这么干。

**Comment by zfl9** [comment]
仔细讨论了下，还是保留抢答模式。反正改动也很小。

**Comment by zfl9** [comment]
改完了。明天我再自测一下，应该是没啥问题。

**Comment by bzzjh** [comment]
> 改完了。明天我再自测一下，应该是没啥问题。
> 
> UPDATE: 还是有个小问题（果然不能熬夜），今早发现已修复，b22。

我也更新测试一下。多谢

**Comment by cod1ingcoding** [comment]
> 公平模式（可选）：假设大概率存在可信dns先返回的情况。逻辑：如果国内先返回，则走上述抢答模式逻辑；如果可信先返回，则等待国内dns返回后再进行上述抢答模式逻辑（先判断国内的响应，再判断可信的响应）。你们觉得如何，这样感觉更接近“公平”的意义。

对，我觉得这样更好！

**Comment by om2mo** [comment]
C版Chinadns不是有“双向过滤”吗，如果国内dns返回国外ip丢弃，如果国外dns返回国内ip丢弃。
