### ISSUE TITLE
想请教一下bind_address是否支持绑定ipv6地址

### ISSUE THREAD

**Issue by Licolnlee** [zfl9/chinadns-ng#47]
想请教一下bind_address是否支持绑定ipv6地址，具体格式上需不需要加中括号？

**Comment by zfl9** [comment]
你试下不就知道了。鉴于你这么懒，还是说一下吧：可以v4/v6，不用中括号。

**Comment by Licolnlee** [comment]
> 你试下不就知道了。鉴于你这么懒，还是说一下吧：可以v4/v6，不用中括号。

不好意思打扰您了，我其实是因为无法同时绑定双栈地址只能绑定一方所以才发的issue来请教您，感谢您耐心的解答，有劳，受教了。

**Comment by zfl9** [comment]
chinadns-ng 的 ipv6 监听设置了 ipv6_v6only，可其两个进程，一个监听v4一个监听v6。
