### ISSUE TITLE
[feature request]打印上游DNS的响应时间

### ISSUE THREAD

**Issue by zhaibin18** [zfl9/chinadns-ng#49]
在日志中打印上游DNS的响应时间，以便评估上游DNS的延时情况。

**Comment by zfl9** [comment]
dns延时情况建议用别的工具看，比如dig。在chinadns-ng里面做的话我需要新加一些字段在query_context里面，如果是光为了打印一个日志而浪费这部分内存的话我觉得没有必要（虽然也就几个字节而已）。
