### ISSUE TITLE
设置两个国内DNS或两个可信DNS时，其中一个DNS不可用可能导致查询失败

### ISSUE THREAD

**Issue by wyf88** [zfl9/chinadns-ng#54]
作者你好，

想请教下，当设置两个国内DNS和两个可信DNS时，当其中一个国内DNS或其中一个可信DNS不可用时（e.g. 国内DoH服务器故障，或可信DNS走的代理失效），有时候会导致ChinaDNS-ng timeout无法给出结果。我想知道查询的逻辑是同时查询两个DNS，还是会先查询第一个，如果失效再查询第二个呢？看log感觉似乎是前者，但不太理解为何有时把失效的DNS放在第二个时又能给出结果。

谢谢！

**Comment by zfl9** [comment]
同时查询，然后采用第一个返回的结果。
