### ISSUE TITLE
请问gfwlist是否可以只解析ipv4？

### ISSUE THREAD

**Issue by t66y100** [zfl9/chinadns-ng#55]
我不会设置ipv6分流规则，好像路由的ip6tables也不支持nat，同时，我有pt需要，不能禁用ipv6。

所以希望gfwlist只解析ipv4，不知道该如何设置？还是默认就可以不需要设置？

谢谢。

**Comment by zfl9** [comment]
不支持，建议通过上游dns去解决禁用v6的问题
