### ISSUE TITLE
我看chnlist中没有结尾CN域名，请问CN域名是如何分流的呢

### ISSUE THREAD

**Issue by secretandanon** [zfl9/chinadns-ng#59]
我看到文档中写不能添加只有一个元素的域名如cn/net/com/org这样的，至少要有两个元素，那这样做的话，CN结尾的域名如何做到走china的dns服务器呢

**Comment by secretandanon** [comment]
@zfl9

**Comment by zfl9** [comment]
是的，填不了目前来说。也许后面会放开这个限制。
