### ISSUE TITLE
支持V2rayr的域名和ip数据

### ISSUE THREAD

**Issue by teapethu** [zfl9/chinadns-ng#63]
有没有打算支持V2rayr的域名和ip数据？

以下2个是V2ray官方和一个三方规则，
https://github.com/v2fly/domain-list-community
https://github.com/Loyalsoldier/v2ray-rules-dat

感觉这个项目能实现更精准的规则

**Comment by zfl9** [comment]
暂时没有相关计划。目前的规则对我来说可以满足需求了。
