### ISSUE TITLE
大神帮忙看看我的计划任务是否正确，环境OPENWRT

### ISSUE THREAD

**Issue by xspeed1989** [zfl9/chinadns-ng#66]
```bash
*/30 * * * * wget -O- 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > /etc/chinadns-ng/chnroute.txt
*/30 * * * * wget -O- 'https://raw.githubusercontent.com/alphabetY/goflyway2/master/chinalist.txt'  > /etc/chinadns-ng/chinalist.txt
*/30 * * * * cd /etc/chinadns-ng && /etc/chinadns-ng/update-gfwlist.sh
*/30 * * * * cd /etc/chinadns-ng && /etc/chinadns-ng/update-chnlist.sh
*/30 * * * * cd /etc/chinadns-ng && /etc/chinadns-ng/update-chnroute.sh && ipset -F chnroute && ipset -R -exist <chnroute.ipset
*/30 * * * * cd /etc/chinadns-ng && /etc/chinadns-ng/update-chnroute6.sh && ipset -F chnroute6 && ipset -R -exist <chnroute6.ipset
```

**Comment by zfl9** [comment]
这个自己测试一下吧，我也没有openwrt的测试环境。

**Comment by xspeed1989** [comment]
@zfl9 嗯 想问下 chinadns-ng开启的时候是不是会读取chnroute.txt 然后进行ipset操作。
然后在运行过程中就需要运行 update-chnroute.sh update-chnroute.sh 更新两个ipset文件并导入？

**Comment by zfl9** [comment]
chinadns-ng 不会操作 ipset，只会读取

**Comment by zfl9** [comment]
这个readme写了呀

**Comment by zfl9** [comment]
>
注意，chinadns-ng 并不读取 chnroute.ipset、chnroute6.ipset 文件，启动时也不会检查这些 ipset 集合是否存在，它只是在收到 dns 响应时通过 netlink 套接字询问 ipset 模块，指定 ip 是否存在

**Comment by zfl9** [comment]
你可以随时运行update-chnroute*.sh来更新ipset。不需要重启chinadns-ng。只有更新gfwlist.txt和chnlist.txt（域名列表）的时候，才需要重启chinadns-ng来生效。ipset的更新时立即生效的。chinadns-ng只会查询ipset集合，不会操作ipset

**Comment by xspeed1989** [comment]
> > 
> 
> 注意，chinadns-ng 并不读取 chnroute.ipset、chnroute6.ipset 文件，启动时也不会检查这些 ipset 集合是否存在，它只是在收到 dns 响应时通过 netlink 套接字询问 ipset 模块，指定 ip 是否存在

明白了，我那个openwrt版本的init.d下面的文件，会从一个txt文件操控ipset，然后再启动chinadns-ng，不是chinadns-ng操控的

自动更新ipset并导入，我看ipset是实时生效
我这个计划任务只是定时更新 chinalist.txt  gfwlist.txt 这个是实时生效的吗

**Comment by xspeed1989** [comment]
明白了哈哈  大佬可以去搞个openwrt的路由器 SS+CHINADNS-NG爽的一匹

**Comment by xspeed1989** [comment]
谢谢解答 我关闭issue啦
