### ISSUE TITLE
如何过滤掉返回的ipv6结果

### ISSUE THREAD

**Issue by xspeed1989** [zfl9/chinadns-ng#67]
如何过滤掉返回的ipv6结果？是否能提供选项，如果自己修改的话，关键代码在哪里呢？

**Comment by zfl9** [comment]
过几天我会加上这个选项。

**Comment by zfl9** [comment]
你可以先简单的清空 chnroute6 这个ipset 
ipset -F chnroute6

**Comment by zfl9** [comment]
先临时对付一下ipv6

**Comment by xspeed1989** [comment]
@zfl9 多谢大佬，我昨天还自己实现了gethostbyname这个函数，还说想想看咋个搞呢

**Comment by xspeed1989** [comment]
@zfl9 我自己实现了，并提交了一个PR，如果可以的话，请合并下。谢谢大佬提供的项目

**Comment by zfl9** [comment]
有时间我会看的，这几天家里忙。

**Comment by xspeed1989** [comment]
> 有时间我会看的，这几天家里忙。

好的大王

**Comment by zfl9** [comment]
已添加，有时间帮忙测试下。 B24

**Comment by xspeed1989** [comment]
> 已添加，有时间帮忙测试下。 B24

现在在老家，初7回去测试 谢谢大佬

**Comment by xspeed1989** [comment]
@zfl9 测试通过，并自行编译到arm平台
