### ISSUE TITLE
[Feature]能否增加一个开关, 让某一个dns，总是返回NoDomain

### ISSUE THREAD

**Issue by emacsnt** [zfl9/chinadns-ng#68]
dns分流，但是在一些场景下，china dns和trust dns可能只是单边工作的（因为想要彻底的分流）
1，没有科学环境的前提下， trust dns无法正常工作。这个时候不希望trust dns返回国外域名查询结果，反正也是被污染的
2，全局的前提下， china dns结果没有用。

所以，是否可以增加开关，关闭dns，关闭以后，查询只返回nodomain的结果

**Comment by zfl9** [comment]
我觉得不需要返回nxdomain，不请求这一组dns就行了吧。比如
1. 要禁用china上游，那么chinadns-ng在收到客户端的查询请求时，就只给trust上游发送查询请求，那么自然只有trust返回查询结果，客户端收到的是trust的响应。
2. 同样的道理，如果禁用trust上游，那么就不给trust上游发送查询请求，那么自然也只会收到china上游的响应结果咯。

我觉得这应该就符合你的需求了吧。

**Comment by emacsnt** [comment]
非常感谢zfl9回复。

我现在的情况是只开启了域名白名单和china上游，openwrt配置如下，然后查询www.google.com，结果返回了被污染的解析
我期望是不返回任何结果, 因为china-domain不包含www.google.com，因为去查trust dns，但是trust没有开启，结果还是使用了china dns的返回值。

config chinadns-ng
        option enable '1'
        option bind_addr '127.0.0.1'
        option bind_port '5353'
        option china_dns '192.168.1.1#53'
        option trust_dns '' 
        option ipset_name4 'chnroute'
        option ipset_name6 'chnroute6'
        option gfwlist_file ''
        option chnlist_file '/etc/chinadns-ng/china-domain.txt'
        option timeout_sec '1'
        option repeat_times '1'
        option chnlist_first '1'
        option fair_mode '0'
        option reuse_port '0'
        option noip_as_chnip '0'

**Comment by zfl9** [comment]
> 非常感谢zfl9回复。
> 
> 我现在的情况是只开启了域名白名单和china上游，openwrt配置如下，然后查询www.google.com，结果返回了被污染的解析
> 我期望是不返回任何结果, 因为china-domain不包含www.google.com，所以去查trust dns，但是trust没有开启，结果还是使用了china dns的返回值。
> 
> config chinadns-ng
> option enable '1'
> option bind_addr '127.0.0.1'
> option bind_port '5353'
> option china_dns '192.168.1.1#53'
> option trust_dns ''
> option ipset_name4 'chnroute'
> option ipset_name6 'chnroute6'
> option gfwlist_file ''
> option chnlist_file '/etc/chinadns-ng/china-domain.txt'
> option timeout_sec '1'
> option repeat_times '1'
> option chnlist_first '1'
> option fair_mode '0'
> option reuse_port '0'
> option noip_as_chnip '0'

额，你直接说，我的这个实现方式，是否满足你的需求就行了。因为这是最简单的方式了，返回nxdomain其实更不好处理，还不如不返回dns查询结果。

**Comment by zfl9** [comment]
> 非常感谢zfl9回复。
> 
> 我现在的情况是只开启了域名白名单和china上游，openwrt配置如下，然后查询www.google.com，结果返回了被污染的解析
> 我期望是不返回任何结果, 因为china-domain不包含www.google.com，所以去查trust dns，但是trust没有开启，结果还是使用了china dns的返回值。
> 
> config chinadns-ng
> option enable '1'
> option bind_addr '127.0.0.1'
> option bind_port '5353'
> option china_dns '192.168.1.1#53'
> option trust_dns ''
> option ipset_name4 'chnroute'
> option ipset_name6 'chnroute6'
> option gfwlist_file ''
> option chnlist_file '/etc/chinadns-ng/china-domain.txt'
> option timeout_sec '1'
> option repeat_times '1'
> option chnlist_first '1'
> option fair_mode '0'
> option reuse_port '0'
> option noip_as_chnip '0'

我明白你的意思了，但是我不明白你这样配置chinadns-ng的意义是什么，禁用一组dns上游，有什么作用和意义？我不明白

**Comment by emacsnt** [comment]
>我明白你的意思了，但是我不明白你这样配置chinadns-ng的意义是什么，禁用一组dns上游，有什么作用和意义？我不明白

这样做的语义是 保证查询结果永远是可信的，不管china dns 和 trust dns配置了哪一组，任何返回结果都是可以被信任的，不被信任的查询结果不返回，只返回NoDomain。

**Comment by zfl9** [comment]
我觉得你只需要启用gfwlist+chinalist就行了吧，感觉并不需要禁用某组dns(返回nxdomain之类的)。你说的那个例子（解析www.google.com的那个），如果启用了gfwlist和chinalist，则查询的时候，只会给trust-dns发送请求，然后trust-dns不会响应任何东西，那么自然客户端也就不会收到任何reply，这不就解决问题了吗？

**Comment by emacsnt** [comment]
谢谢建议，我先开着这个issue，等年后测试一下设定gfwlist但是trust-dns为空白的配置效果

**Comment by zfl9** [comment]
OK

**Comment by emacsnt** [comment]
测试结果如下：
1，trust-dns留空，则程序用了缺省trust-dns 8.8.8.8来查询，结果取决于网络环境，没有透明翻墙的情况下，查询结果被污染，不是我所预期的
2，trust-dns设定为没有提供dns服务的ip#port，譬如127.0.0.1#6666，结果是我预期的，
但是openwrt报下面错误
tcp too many orphaned sockets
nf_conntrack table full dropping packet
看起来chinadns-ng访问不存在的dns服务会产生孤儿sockets？

**Comment by zfl9** [comment]
> 还是希望可以提供一个关闭选项，只返回单组结果

描述详细点，详细规则，说清楚

**Comment by emacsnt** [comment]
增加一个严格模式(strict mode)， 所谓严格模式，即保证dns查询结果是用户预期的，程序不做主动揣测，不做额外工作。

严格模式(strict mode):返回严格精确结果，如果不能保证准确性，则返回nodomain
严格模式下，服务器留空，则不使用缺省dns，有以下三个场景：
1. 设定chinadns，未设定trustdns，域名命中chnlist-file，只返回chinadns查询结果，其余未命中的返回nodomain
2. 设定trustdns，未设定chinadns，域名命中gfwlist-file，只返回trustdns查询结果，其余未命中的返回nodoamin
3. 设定chinadns和trustdns，域名命中chnlist-file，返回chinadns查询结果，域名命中gfwlist-file, 返回trustdns查询结果, 其余未命中的返回nodomain
严格模式下的参数检查，对应dns服务器如果设定了，那么对应域名list文件必须设定，也即
场景1，chnlist-file必须设定，否则无法工作
场景2，gfwlist-file必须设定，否则无法工作
场景3，chnlist-file/gfwlist-file至少有一个设定，否则无法工作；只设定了一个域名list的，相当于切换到场景1 或者 场景2

**Comment by emacsnt** [comment]
补充一下这个需求的背景：
几乎所有科学上网相关的dns都把注意力放在返回正确的dns解析结果，但却忽略了产生dns污染和劫持的原因。
既然不想让访问某些网络的力量存在，那么访问这些网络必然是存在一定的法律或者政策风险，那么最好不要让国内dns知道用户有哪些解析请求，最好把这些隐私小心保护起来。
目前程序行为，并不在意国内dns是否知道/纪录用户的解析请求，只求最大可能返回能够使用的IP。严格模式的初衷，就是把隐私考虑在内，把域名解析请求按照用户的期望进行彻底分流，杜绝隐私泄露风险。

**Comment by zfl9** [comment]
等我有时间再考虑下，现在业余时间不足，抱歉。
