### ISSUE TITLE
求助，--china-dns 和 --trust-dns 选项的问题

### ISSUE THREAD

**Issue by pexcn** [zfl9/chinadns-ng#7]
尝试把 chinadns-ng 移植到了 OpenWrt, 参考了 openwrt-chinadns 的代码。但是出现了一个问题，`--china-dns` 和 `--trust-dns` 参数的 `#` 号被忽略了，请问是这个软件本身对 `#` 号的处理有问题吗？（openwrt-chinadns 没有这个问题）
https://github.com/pexcn/openwrt-chinadns-ng/blob/master/files/chinadns-ng.init#L149-L150

描述得不是很清楚，截了几个图：
![1](https://user-images.githubusercontent.com/4590439/63651389-bb187c80-c786-11e9-9695-b7f67839eec7.png)
![2](https://user-images.githubusercontent.com/4590439/63651391-bb187c80-c786-11e9-8988-47aee469ebd7.png)
![3](https://user-images.githubusercontent.com/4590439/63651392-bb187c80-c786-11e9-8e61-4cd74b0d3a5a.png)

**Comment by zfl9** [comment]
这只是显示问题

**Comment by zfl9** [comment]
实际用的是指定端口的dns

**Comment by zfl9** [comment]
![image](https://user-images.githubusercontent.com/22726048/63651446-6aedea00-c787-11e9-98de-9597ba8ed817.png)
rushangtu如上图，井号其实没显示出来，但是确实用的是那个指定的端口，你可以实际测试下的，而且启动chinadns-ng时会打印upstream的地址和端口号，都是没问题的。

**Comment by pexcn** [comment]
看来的确是的，但是能否修复一下？

**Comment by zfl9** [comment]
这个应该不是程序的问题，只是ps它们显示上的问题，无伤大雅

**Comment by pexcn** [comment]
额好吧，但是 ChinaDNS 没有这个问题。。

另外，有个关于请求流程优化的建议：
1. 同时向上游的 DNS 请求，如果任意一个先返回的 DNS 的 IP 是国内 IP，则立即采用，同时丢弃其它结果；
2. 如果先返回的不是国内的 IP，则等待另一个 DNS 返回数据，如果此时返回的 IP 如果是国内 IP，则采用，如果不是国内 IP，也采用可信 DNS 的结果。

我想这样应该可以解决可信 DNS 比国内 DNS 返回快而导致返回的结果都是境外 IP 的问题了。

**Comment by pexcn** [comment]
说得好像太长了，简单的流程就是：
同时向所有上游 DNS 请求，如果先返回的 IP 是国内的，即采用；否则采用可信 DNS 的。

**Comment by cattyhouse** [comment]
> 说得好像太长了，简单的流程就是：
> 同时向所有上游 DNS 请求，如果先返回的 IP 是国内的，即采用；否则采用可信 DNS 的。

可信DNS比如8888是走proxy代理的 (目的是确保8888不被劫持), 不可能比国内DNS快.

**Comment by zfl9** [comment]
> 额好吧，但是 ChinaDNS 没有这个问题。。
> 
> 另外，有个关于请求流程优化的建议：
> 
> 1. 同时向上游的 DNS 请求，如果任意一个先返回的 DNS 的 IP 是国内 IP，则立即采用，同时丢弃其它结果；
> 2. 如果先返回的不是国内的 IP，则等待另一个 DNS 返回数据，如果此时返回的 IP 如果是国内 IP，则采用，如果不是国内 IP，也采用可信 DNS 的结果。
> 
> 我想这样应该可以解决可信 DNS 比国内 DNS 返回快而导致返回的结果都是境外 IP 的问题了。

但这样

> > 说得好像太长了，简单的流程就是：
> > 同时向所有上游 DNS 请求，如果先返回的 IP 是国内的，即采用；否则采用可信 DNS 的。
> 
> 可信DNS比如8888是走proxy代理的 (目的是确保8888不被劫持), 不可能比国内DNS快.

对的，我觉得没有这个必要，如果

> 说得好像太长了，简单的流程就是：
> 同时向所有上游 DNS 请求，如果先返回的 IP 是国内的，即采用；否则采用可信 DNS 的。

可是现在不就是这么判断的吗。。

**Comment by zfl9** [comment]
或者可以说清楚一些？

**Comment by zfl9** [comment]
> 额好吧，但是 ChinaDNS 没有这个问题。。
> 
> 另外，有个关于请求流程优化的建议：
> 
> 1. 同时向上游的 DNS 请求，如果任意一个先返回的 DNS 的 IP 是国内 IP，则立即采用，同时丢弃其它结果；
> 2. 如果先返回的不是国内的 IP，则等待另一个 DNS 返回数据，如果此时返回的 IP 如果是国内 IP，则采用，如果不是国内 IP，也采用可信 DNS 的结果。
> 
> 我想这样应该可以解决可信 DNS 比国内 DNS 返回快而导致返回的结果都是境外 IP 的问题了。

但我感觉没有这个必要，反正可信dns都是经过代理的。

**Comment by zfl9** [comment]
> 额好吧，但是 ChinaDNS 没有这个问题。。
> 
> 另外，有个关于请求流程优化的建议：
> 
> 1. 同时向上游的 DNS 请求，如果任意一个先返回的 DNS 的 IP 是国内 IP，则立即采用，同时丢弃其它结果；
> 2. 如果先返回的不是国内的 IP，则等待另一个 DNS 返回数据，如果此时返回的 IP 如果是国内 IP，则采用，如果不是国内 IP，也采用可信 DNS 的结果。
> 
> 我想这样应该可以解决可信 DNS 比国内 DNS 返回快而导致返回的结果都是境外 IP 的问题了。

我仔细看了你这个流程，实在没有看的太明白。。或许可以表述的更加清楚明白些

**Comment by pexcn** [comment]
但是用深港专线 VPS 的非标准端口转发 8.8.8.8 是有时候比一些国内 DNS 延迟低的

**Comment by zfl9** [comment]
@pexcn  明天或者啥时候有时间再详细研究.

**Comment by pexcn** [comment]
> 我仔细看了你这个流程，实在没有看的太明白。。或许可以表述的更加清楚明白些

1. 同时向上游的 DNS 请求，如果任意一个 DNS 返回的结果是国内 IP，则立即采用，同时丢弃其它结果。
2. 如果先返回的不是国内 IP，则陆续等待其它结果，只要其中有的结果返回的是国内 IP 就采用。
3. 最后才使用可信 DNS 的结果。

好像也跟现在的差不多...



> @pexcn 明天或者啥时候有时间再详细研究.

嗯，好的

**Comment by zfl9** [comment]
@pexcn 
其实不用这么麻烦，反正要解决的问题就是：**可信dns比国内dns先返回的特殊情况**，对吧。这种情况确实存在，比如你说的港深专线。那么要解决这个问题，我们只需抓住一个根本：**必须等到任意一个国内DNS上游返回解析结果后，再进行判断**，这样就没任何问题了。流程如下：
1. 当chinadns-ng从客户端收到一个dns查询请求包后，chinadns-ng会同时向所有上游dns发送此请求包，然后等待上游的dns响应包。
2. 第一种情况，国内dns先返回，可信dns后返回，那么流程和之前是一样的，首先检查国内dns返回的ip地址是否在ipset中，如果在，那么最终的解析结果就是它了，其它的结果全部丢弃，将这个解析结果返回给请求客户端。那么这个请求就处理完毕了。
3. 第二种情况，可信dns先返回，国内dns后返回；当收到可信dns的响应包后，检查发现此前暂未收到国内dns的响应包，那么chinadns-ng就等待任意一个国内上游dns返回一个响应包，当任意一个国内dns响应到来之后，判断逻辑还是同上，先检查国内dns的响应包含的ip是否在ipset中，如果在，那么最终的解析结果就是国内上游的解析结果，其它的全部丢弃，该请求处理完毕；如果国内dns解析出来的ip不在ipset中，那么我们就采用可信dns上游的响应，其它的全部丢弃，该请求处理完毕。

我有时间会加一个选项，默认还是“抢答模式”，也就是和之前的模式是一样的，不会出现谁等谁的情况；然后如果指定了这个选项，那么chinadns-ng就会变为“公平模式”，公平模式就是上面描述的这样，如果可信dns比国内dns先返回，那么最终的解析结果确认必须等到任意一个国内dns返回解析结果之后才能进行判断。这样就能避免你说的港深专线可信dns比国内dns先返回的情况了。

**Comment by pexcn** [comment]
> 3\. 第二种情况，可信dns先返回，国内dns后返回；当收到可信dns的响应包后，检查发现此前暂未收到国内dns的响应包，那么chinadns-ng就等待任意一个国内上游dns返回一个响应包，当任意一个国内dns响应到来之后，判断逻辑还是同上，先检查国内dns的响应包含的ip是否在ipset中，如果在，那么最终的解析结果就是国内上游的解析结果，其它的全部丢弃，该请求处理完毕；如果国内dns解析出来的ip不在ipset中，那么我们就采用可信dns上游的响应，其它的全部丢弃，该请求处理完毕。

我觉得可以直接判断这个 IP 是不是国内的，如果是，就直接采用，如果不是，再等待国内 DNS 不是更快吗？

**Comment by zfl9** [comment]
@pexcn 确实是的。那就收到回复包之后先判断是不是国内ip。

**Comment by pexcn** [comment]
嗯，好

**Comment by zfl9** [comment]
@pexcn 已更新，具体看readme。

**Comment by pexcn** [comment]
@zfl9 嗯，发现在这个 commit: https://github.com/zfl9/chinadns-ng/commit/346ecf84d61f39b730b536af8a7203e3f44e798e 去掉了私网的地址，为什么要这么做呢？

**Comment by zfl9** [comment]
有需要的话自己加上即可。之前默认加上私网地址是考虑有人会使用内网dns作为china-dns上游。不过我在readme里面也说明了，具体的话看下readme就明白了。

**Comment by pexcn** [comment]
噢噢，好，谢谢。
