### ISSUE TITLE
[增强] 国内和可信DNS单独提供no-ipv6选项

### ISSUE THREAD

**Issue by kiddin9** [zfl9/chinadns-ng#72]
因为梯子的国外节点基本都不提供IPV6,我只需要过滤可信DNS的IPV6即可,国内还是想保留IPV6, 谢谢.

**Comment by zfl9** [comment]
有时间再弄下，现在忙，没时间哈

**Comment by z826540272** [comment]
支持

**Comment by jliveusa** [comment]
支持+1~

**Comment by Yesterday17** [comment]
如果想保留 chnlist 域名的 ipv6 解析的话可以参考这个

https://github.com/Yesterday17/chinadns-ng/commit/3a2bf634d9073094034ff10ffe81e501be62db05

**Comment by z10056** [comment]
> > 保留 chnlist 域名的 ipv6 解析
> 
> padavan固件测试有效，终于解决了ipv6与翻墙共存

兄弟，你是如何替换padavan里的chinadns的

**Comment by Bitcion** [comment]
> > > 保留 chnlist 域名的 ipv6 解析
> > 
> > 
> > padavan固件测试有效，终于解决了ipv6与翻墙共存
> 
> 兄弟，你是如何替换padavan里的chinadns的

插u盘，ex4格式，直接找到文件替换

**Comment by zfl9** [comment]
虽然时间有点久了(打工仔，望理解哈)，不过我想重新确认下需求。最近会对chinadns-ng小更新一波，所以打算把这个拖了这么久的issue一并解决了。

提供三种过滤选项：
1. 全部v6请求都过滤掉(像现在这样)
2. 过滤'国内上游'的v6响应
3. 过滤'可信上游'的v6响应
4. 过滤gfwlist域名的v6响应
5. 过滤chnlist域名的v6响应

**Comment by zfl9** [comment]
已更新，见最新master版本。

参数改了下：

- `--no-ipv6`：默认，同之前的版本，过滤所有v6
- `--no-ipv6=规则串`：每个规则都是一个字符，目前有如下：
  - `a`：all，过滤所有name的v6请求，同默认行为
  - `g`：gfwlist name，过滤所有gfwlist域名的v6请求
  - `m`：chnlist name，过滤所有chnlist域名的v6请求
  - `c`：chinadns upstream，对国内上游过滤v6请求（不将v6请求转发给国内上游）
  - `t`：trustdns upstream，对可信上游过滤v6请求（不将v6请求转发给可信上游）

**Comment by pexcn** [comment]
@zfl9 请问也支持 `-N=gt` 这种方式传参吗？

**Comment by zfl9** [comment]
支持

**Comment by zfl9** [comment]
-Ngt、-N=gt 都可以

**Comment by pexcn** [comment]
> ```shell
> -Ngt #可行，但不建议
> -N=gt
> --no-ipv6=gt
> ```

@zfl9 `-N gt` 这个方式也支持吗？刚忘记问了，我下游 openwrt 的版本也需要跟进一下😅

**Comment by zfl9** [comment]
不可以，必须作为一个 param（也就是不允许有空白符）

**Comment by pexcn** [comment]
了解

**Comment by zfl9** [comment]
> 

参数可以先跟进，不过版本先别发布，因为今天还发现一个优化点，关于dnl匹配的。

**Comment by zfl9** [comment]
还没改完，所以还没更新readme :joy:

**Comment by zfl9** [comment]
readme更新了，版本已发布，版本号规则改了下。

**Comment by zfl9** [comment]
no-ipv6之前的处理有逻辑bug，请更新到2023.03.06版本。
