### ISSUE TITLE
UDP 查询超时

### ISSUE THREAD

**Issue by z826540272** [zfl9/chinadns-ng#73]
直接查询没问题,都可以在150ms内快速回应.(结果正确无污染)
但是通过chinadns设置上游查询大概率超时,少部分情况下可以查询到结果.
目标服务器是8.8.8.8 / 1.0.0.1
走的是v2ray代理,
大部分节点是这样的,少部分节点又是完全正常的.
请排查下问题,我可以提供节点测试.

**Comment by zfl9** [comment]
麻烦提供一下chinadns-ng的verbose日志

**Comment by z826540272** [comment]
![QQ截图20210221181823.jpg](https://i.loli.net/2021/02/21/nMisfK3o7gX6cJT.jpg)

**Comment by z826540272** [comment]
虽然DIG显示查询时间239ms,但是每次查询等待结果显示要5秒以上.

**Comment by z826540272** [comment]
root@OpenWrt:~# dig www.google.com.hk @8.8.8.8

; <<>> DiG 9.16.8 <<>> www.google.com.hk @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8812
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.hk.             IN      A

;; ANSWER SECTION:
www.google.com.hk.      284     IN      A       216.58.199.3

;; Query time: 89 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Feb 21 18:20:49 CST 2021
;; MSG SIZE  rcvd: 62

直接查询8.8.8.8一般是立即出结果的.

**Comment by zfl9** [comment]
日志请不要截图，我想看文字版的
图片看不清

**Comment by z826540272** [comment]
`root@OpenWrt:~# /var/etc/passwall/bin/chinadns-ng -v -b 0.0.0.0 -l 88 -c 119.29.29.29 -m /var/etc/passwall/chnlist -M -t 8.8.8.8 -g /var/etc/passwall/gfwlist.txt -f
2021-02-21 20:30:31 INF: [main] local listen addr: 0.0.0.0#88
2021-02-21 20:30:31 INF: [main] chinadns server#1: 119.29.29.29#53
2021-02-21 20:30:31 INF: [main] trustdns server#1: 8.8.8.8#53
2021-02-21 20:30:31 INF: [main] ipset ip4 setname: chnroute
2021-02-21 20:30:31 INF: [main] ipset ip6 setname: chnroute6
2021-02-21 20:30:31 INF: [main] dns query timeout: 5 seconds
2021-02-21 20:30:31 INF: [main] gfwlist entries count: 5455
2021-02-21 20:30:31 INF: [main] chnlist entries count: 70651
2021-02-21 20:30:31 INF: [main] chnlist have higher priority
2021-02-21 20:30:31 INF: [main] filter reply without ip addr
2021-02-21 20:30:31 INF: [main] cur judgment mode: fair mode
2021-02-21 20:30:31 INF: [main] print the verbose running log
2021-02-21 20:30:57 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#41261 (0)
2021-02-21 20:30:57 INF: [handle_remote_packet] reply [www.google.com.hk] from 8.8.8.8#53 (0), result: accept
2021-02-21 20:30:59 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#36253 (1)
2021-02-21 20:31:04 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#36253 (2)
2021-02-21 20:31:04 ERR: [handle_timeout_event] upstream dns server reply timeout, unique msgid: 1
2021-02-21 20:31:04 INF: [handle_remote_packet] reply [www.google.com.hk] from 8.8.8.8#53 (2), result: accept
2021-02-21 20:31:10 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#40019 (3)
2021-02-21 20:31:10 INF: [handle_remote_packet] reply [www.google.com.hk] from 8.8.8.8#53 (3), result: accept
2021-02-21 20:31:12 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#35572 (4)
2021-02-21 20:31:17 ERR: [handle_timeout_event] upstream dns server reply timeout, unique msgid: 4
2021-02-21 20:31:17 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#35572 (5)
2021-02-21 20:31:17 INF: [handle_remote_packet] reply [www.google.com.hk] from 8.8.8.8#53 (5), result: accept
2021-02-21 20:31:19 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#43612 (6)
2021-02-21 20:31:24 ERR: [handle_timeout_event] upstream dns server reply timeout, unique msgid: 6
2021-02-21 20:31:24 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#43612 (7)
2021-02-21 20:31:29 ERR: [handle_timeout_event] upstream dns server reply timeout, unique msgid: 7
2021-02-21 20:31:29 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#43612 (8)
2021-02-21 20:31:29 INF: [handle_remote_packet] reply [www.google.com.hk] from 8.8.8.8#53 (8), result: accept
2021-02-21 20:31:31 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#59183 (9)
2021-02-21 20:31:31 INF: [handle_remote_packet] reply [www.google.com.hk] from 8.8.8.8#53 (9), result: accept
2021-02-21 20:31:32 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#57448 (10)
2021-02-21 20:31:37 ERR: [handle_timeout_event] upstream dns server reply timeout, unique msgid: 10
2021-02-21 20:31:37 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#57448 (11)
2021-02-21 20:31:37 INF: [handle_remote_packet] reply [www.google.com.hk] from 8.8.8.8#53 (11), result: accept
2021-02-21 20:31:39 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#59028 (12)
2021-02-21 20:31:44 ERR: [handle_timeout_event] upstream dns server reply timeout, unique msgid: 12
2021-02-21 20:31:44 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#59028 (13)
2021-02-21 20:31:44 INF: [handle_remote_packet] reply [www.google.com.hk] from 8.8.8.8#53 (13), result: accept
2021-02-21 20:31:46 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#56430 (14)
2021-02-21 20:31:46 INF: [handle_remote_packet] reply [www.google.com.hk] from 8.8.8.8#53 (14), result: accept
2021-02-21 20:31:49 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#42220 (15)
2021-02-21 20:31:54 ERR: [handle_timeout_event] upstream dns server reply timeout, unique msgid: 15
2021-02-21 20:31:54 INF: [handle_local_packet] query [www.google.com.hk] from 10.0.0.10#42220 (16)
2021-02-21 20:31:55 INF: [handle_remote_packet] reply [www.google.com.hk] from 8.8.8.8#53 (16), result: accept
`

**Comment by z826540272** [comment]
DIG信息

root@OpenWrt:~# dig www.google.com.hk @10.0.0.10 -p 88

; <<>> DiG 9.16.8 <<>> www.google.com.hk @10.0.0.10 -p 88
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56750
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.hk.             IN      A

;; ANSWER SECTION:
www.google.com.hk.      275     IN      A       216.58.220.195

;; Query time: 239 msec
;; SERVER: 10.0.0.10#88(10.0.0.10)
;; WHEN: Sun Feb 21 20:31:31 CST 2021
;; MSG SIZE  rcvd: 62

root@OpenWrt:~# dig www.google.com.hk @10.0.0.10 -p 88

; <<>> DiG 9.16.8 <<>> www.google.com.hk @10.0.0.10 -p 88
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6291
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.hk.             IN      A

;; ANSWER SECTION:
www.google.com.hk.      84      IN      A       216.58.221.227

;; Query time: 209 msec
;; SERVER: 10.0.0.10#88(10.0.0.10)
;; WHEN: Sun Feb 21 20:31:37 CST 2021
;; MSG SIZE  rcvd: 62

root@OpenWrt:~# dig www.google.com.hk @10.0.0.10 -p 88

; <<>> DiG 9.16.8 <<>> www.google.com.hk @10.0.0.10 -p 88
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4952
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.hk.             IN      A

;; ANSWER SECTION:
www.google.com.hk.      252     IN      A       216.58.220.195

;; Query time: 219 msec
;; SERVER: 10.0.0.10#88(10.0.0.10)
;; WHEN: Sun Feb 21 20:31:44 CST 2021
;; MSG SIZE  rcvd: 62

root@OpenWrt:~# dig www.google.com.hk @10.0.0.10 -p 88

; <<>> DiG 9.16.8 <<>> www.google.com.hk @10.0.0.10 -p 88
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51888
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.hk.             IN      A

;; ANSWER SECTION:
www.google.com.hk.      11      IN      A       172.217.24.35

;; Query time: 229 msec
;; SERVER: 10.0.0.10#88(10.0.0.10)
;; WHEN: Sun Feb 21 20:31:46 CST 2021
;; MSG SIZE  rcvd: 62

root@OpenWrt:~# dig www.google.com.hk @10.0.0.10 -p 88

; <<>> DiG 9.16.8 <<>> www.google.com.hk @10.0.0.10 -p 88
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17081
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.google.com.hk.             IN      A

;; ANSWER SECTION:
www.google.com.hk.      251     IN      A       216.58.220.195

;; Query time: 229 msec
;; SERVER: 10.0.0.10#88(10.0.0.10)
;; WHEN: Sun Feb 21 20:31:55 CST 2021
;; MSG SIZE  rcvd: 62

**Comment by z826540272** [comment]
虽然DIG每次都查到了,但是会延迟大概5秒左右才给出结果,nslookup同样.

**Comment by zfl9** [comment]
我觉得这不是chinadns-ng的问题

**Comment by zfl9** [comment]
因为我看log以及dig的输出，都是229ms左右。
至于为什么dig会延迟5秒出结果，这个有待细究。

**Comment by zfl9** [comment]
你用其它linux主机 dig @10.0.0.10 -p 88 试下？

**Comment by zfl9** [comment]
/etc/resolv.conf 的文件内容发来看下？

**Comment by zfl9** [comment]
https://github.com/kubernetes/kubernetes/issues/56903

**Comment by zfl9** [comment]
建议配合 tcpdump 抓包、strace 系统调用跟踪，看下是什么地方耗时了5秒钟。5秒这个数字貌似是dns查询超时的时间（印象中）

**Comment by z826540272** [comment]
/etc/resolv.conf
search lan
nameserver 127.0.0.1
nameserver ::1

Windows下用dig查询是同样的结果,延迟5ms是估算的,还有一个现象就是,好像延迟一次之后第二次查又是立即.
直接dig 8.8.8.8 没延迟. 走的是代理

**Comment by XGFan** [comment]
在openwrt上安装了china-dns，也有类似的现象。

```
root@OpenWrt:~# chinadns-ng -V
ChinaDNS-NG v1.0-beta.24 <https://github.com/zfl9/chinadns-ng>
```

启动命令

```
/usr/bin/chinadns-ng -b 0.0.0.0 -l 5353 -c 114.114.114.114 -t 127.0.0.1#1053 -g /etc/chinadns-ng/gfwlist.txt -m /etc/chinadns-ng/chinalist.txt -o 3 -p 2 -M -N -r -v
```

在openwrt手动查询上游dns服务器，均能正常返回：

```
root@OpenWrt:~# dig @127.0.0.1 -p1053 www.qq.com

; <<>> DiG 9.16.12 <<>> @127.0.0.1 -p1053 www.qq.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29432
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.qq.com.			IN	A

;; ANSWER SECTION:
www.qq.com.		600	IN	A	121.14.77.221
www.qq.com.		600	IN	A	121.14.77.201

;; Query time: 20 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Tue Mar 02 00:37:06 CST 2021
;; MSG SIZE  rcvd: 60

root@OpenWrt:~# dig @114.114.114.114 -p53 www.qq.com

; <<>> DiG 9.16.12 <<>> @114.114.114.114 -p53 www.qq.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35333
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.qq.com.			IN	A

;; ANSWER SECTION:
www.qq.com.		136	IN	CNAME	ins-r23tsuuf.ias.tencent-cloud.net.
ins-r23tsuuf.ias.tencent-cloud.net. 71 IN A	121.14.77.221
ins-r23tsuuf.ias.tencent-cloud.net. 71 IN A	121.14.77.201

;; Query time: 20 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Tue Mar 02 00:37:18 CST 2021
;; MSG SIZE  rcvd: 119

```

通过chinadns-ng查询

```
root@OpenWrt:~# dig @127.0.0.1 -p5353 www.qq.com A

; <<>> DiG 9.16.12 <<>> @127.0.0.1 -p5353 www.qq.com A
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached
```

同时，日志显示超时

```
[handle_local_packet] query [weather-data.apple.com] from 127.0.0.1#17347 (1192)
[handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1192), result: accept
[handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1192), result: ignore
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1188
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1035
[handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1191), result: accept
[handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1191), result: ignore
[handle_local_packet] query [a2047.dscb.akamai.net] from 127.0.0.1#18394 (1040)
[handle_local_packet] query [a2047.dscb.akamai.net] from 127.0.0.1#42448 (1041)
[handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1041), result: accept
[handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1041), result: ignore
[handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1040), result: accept
[handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1040), result: ignore
[handle_local_packet] query [iphone-ld.apple.com] from 127.0.0.1#3490 (1193)
[handle_local_packet] query [iphone-ld.apple.com] from 127.0.0.1#14564 (1042)
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1036
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1037
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1038
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1042
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1193
[handle_local_packet] query [github.com] from 127.0.0.1#36389 (1194)
[handle_remote_packet] reply [github.com] from 127.0.0.1#1053 (1194), result: accept
[handle_remote_packet] reply [github.com] from 127.0.0.1#1053 (1194), result: ignore
```

BTW，只有请求上游china-dns会超时。如果请求trust-dns相关域名，并不会超时。

```
root@OpenWrt:~# dig @127.0.0.1 -p5353 www.google.com

; <<>> DiG 9.16.12 <<>> @127.0.0.1 -p5353 www.google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47752
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		600	IN	A	216.58.200.36

;; Query time: 180 msec
;; SERVER: 127.0.0.1#5353(127.0.0.1)
;; WHEN: Tue Mar 02 00:43:11 CST 2021
;; MSG SIZE  rcvd: 48
```

这个问题重启进程之后就会消失，但是过一段时间就会重新出现。

**Comment by zfl9** [comment]
```shell
root@OpenWrt:~# dig @127.0.0.1 -p5353 www.qq.com A

; <<>> DiG 9.16.12 <<>> @127.0.0.1 -p5353 www.qq.com A
; (1 server found)
;; global options: +cmd
;; connection timed out; no servers could be reached

# 同时，日志显示超时

[handle_local_packet] query [weather-data.apple.com] from 127.0.0.1#17347 (1192)
[handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1192), result: accept
[handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1192), result: ignore
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1188
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1035
[handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1191), result: accept
[handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1191), result: ignore
[handle_local_packet] query [a2047.dscb.akamai.net] from 127.0.0.1#18394 (1040)
[handle_local_packet] query [a2047.dscb.akamai.net] from 127.0.0.1#42448 (1041)
[handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1041), result: accept
[handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1041), result: ignore
[handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1040), result: accept
[handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1040), result: ignore
[handle_local_packet] query [iphone-ld.apple.com] from 127.0.0.1#3490 (1193)
[handle_local_packet] query [iphone-ld.apple.com] from 127.0.0.1#14564 (1042)
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1036
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1037
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1038
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1042
[handle_timeout_event] upstream dns server reply timeout, unique msgid: 1193
[handle_local_packet] query [github.com] from 127.0.0.1#36389 (1194)
[handle_remote_packet] reply [github.com] from 127.0.0.1#1053 (1194), result: accept
[handle_remote_packet] reply [github.com] from 127.0.0.1#1053 (1194), result: ignore
```
你这里都没找到www.qq.com的查询日志？确定给全了？这个log

**Comment by XGFan** [comment]
> ```shell
> ```shell
> root@OpenWrt:~# dig @127.0.0.1 -p5353 www.qq.com A
> 
> ; <<>> DiG 9.16.12 <<>> @127.0.0.1 -p5353 www.qq.com A
> ; (1 server found)
> ;; global options: +cmd
> ;; connection timed out; no servers could be reached
> 
> # 同时，日志显示超时
> 
> [handle_local_packet] query [weather-data.apple.com] from 127.0.0.1#17347 (1192)
> [handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1192), result: accept
> [handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1192), result: ignore
> [handle_timeout_event] upstream dns server reply timeout, unique msgid: 1188
> [handle_timeout_event] upstream dns server reply timeout, unique msgid: 1035
> [handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1191), result: accept
> [handle_remote_packet] reply [weather-data.apple.com] from 127.0.0.1#1053 (1191), result: ignore
> [handle_local_packet] query [a2047.dscb.akamai.net] from 127.0.0.1#18394 (1040)
> [handle_local_packet] query [a2047.dscb.akamai.net] from 127.0.0.1#42448 (1041)
> [handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1041), result: accept
> [handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1041), result: ignore
> [handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1040), result: accept
> [handle_remote_packet] reply [a2047.dscb.akamai.net] from 127.0.0.1#1053 (1040), result: ignore
> [handle_local_packet] query [iphone-ld.apple.com] from 127.0.0.1#3490 (1193)
> [handle_local_packet] query [iphone-ld.apple.com] from 127.0.0.1#14564 (1042)
> [handle_timeout_event] upstream dns server reply timeout, unique msgid: 1036
> [handle_timeout_event] upstream dns server reply timeout, unique msgid: 1037
> [handle_timeout_event] upstream dns server reply timeout, unique msgid: 1038
> [handle_timeout_event] upstream dns server reply timeout, unique msgid: 1042
> [handle_timeout_event] upstream dns server reply timeout, unique msgid: 1193
> [handle_local_packet] query [github.com] from 127.0.0.1#36389 (1194)
> [handle_remote_packet] reply [github.com] from 127.0.0.1#1053 (1194), result: accept
> [handle_remote_packet] reply [github.com] from 127.0.0.1#1053 (1194), result: ignore
> ```
> 
> 
> 你这里都没找到www.qq.com的查询日志？确定给全了？这个log
> ```

日志可能跟查询不太对的上（时间相差了几十秒

**Comment by zfl9** [comment]
把对应的log发出来

**Comment by zfl9** [comment]
不要发这种不对应的log呀
