### ISSUE TITLE
关于域名label数量

### ISSUE THREAD

**Issue by entr0pia** [zfl9/chinadns-ng#75]
如果设为至少两个, 规则中的cn顶级域名可能被忽略

![image](https://user-images.githubusercontent.com/30486766/117151481-b6291e80-adeb-11eb-8bdc-84378407180b.png)

**Comment by zfl9** [comment]
等有时间，加上顶级域名的处理支持。

**Comment by zfl9** [comment]
已更新，现在已经支持1~4个label的域名模式了。另外这个N是可以修改的（修改dnlutils.c中的LABEL_MAXCNT常量，重新编译就行了）。
