### ISSUE TITLE
有什么方法可以过滤输出到文件

### ISSUE THREAD

**Issue by om2mo** [zfl9/chinadns-ng#77]
`chinadns-ng -v|grep google.com`
这条命令在标准输出过滤了只有google.com的解析，但是我想输出到文件，下面的命令无效
`chinadns-ng -v|grep google.com >>a.log`

**Comment by zfl9** [comment]
将output的缓冲区类型改为行缓冲就可以了。默认是全缓冲（只有缓冲区满了才会flush）。
