### ISSUE TITLE
被污染的域名GFW为什么只返回国外IP？

### ISSUE THREAD

**Issue by om2mo** [zfl9/chinadns-ng#78]
既然对返回的IP也没有形成DDOS，如果GFW返回国内IP，那DNS分流是不是都失效或者难度加大了？

**Comment by om2mo** [comment]
我用的判断是ipset ip，用黑白名域名感觉好傻，其实我想从GFW原理去了解它对解析国外域名的DNS污染只会返回国外随机IP，而不返回国内的。假如对国外域名国内的随机ip污染，效果也是一样的，为什么不这么做？而且这样也似乎增加了寻找真实IP的难度。

**Comment by om2mo** [comment]
正常逻辑是国内dns解析出国外域名就地丢弃，那如果国内dns解析出国内ip，那还怎么判断呢？我的意思是gfw污染域名的ip从国外变成国内，那还怎么判断？

**Comment by zfl9** [comment]
1. 绝大部分受污染的域名（gfwlist列表），直接走可信dns上游，与国内dns无关。
2. 绝大多数国内域名（chnlist列表），直接走国内dns上游，与可信dns无关。
3. 剩下的少部分域名，才走chnroute+chnroute6（ipset集合）进行判断。

**Comment by om2mo** [comment]
其实我一直使用ipset集，使用需要长期维护并且读取黑白名单文件感觉好傻，会有误判和漏加，性能上也不如ipset，这也是我一直使用chinadns的原因，所以也冒出了这个想法。
