### ISSUE TITLE
what will happen if china-dns return 127.0.0.1

### ISSUE THREAD

**Issue by xlighting2017** [zfl9/chinadns-ng#8]
In the README, it was said that "if a result from china-dns is in ipset CHNRoute, we use that result, and ignore any other results", while in "chnroute.ipset", 127.0.0.1/8 is included;
  so, if china-dns return 127.0.0.1 for sites like google.com,  chinadns-ng will use that result too?

**Comment by zfl9** [comment]
Yes.

**Comment by zfl9** [comment]
Of course you can remove any address from chnroute.ipset, depending on yourself.

**Comment by zfl9** [comment]
The reason for adding these addresses such as 127.0.0.1 by default is that when the upstream of china-dns is the internal dns server, the normal parsing result including these ips may occur.

**Comment by xlighting2017** [comment]
Thanks, so I think there is a "flaw" here... 
for example, if I'm working in an Intranet, while the upstream ISP DNS has pollution the result with addresses like 127.0.0.1, I'll be in trouble...

it's the "ignore any other results" that causes the "flaw"
how about we "wait until both DNSs return, and compare the results"?

**Comment by zfl9** [comment]
There is no perfect solution, but there are many ways to avoid this:
1. Use `dnsmasq` as the dns server, for `gfwlist` domain names, tell dnsmasq, use `8.8.8.8` dns server (via proxy), for other domain names, use `chinadns-ng` to resolve them. This is the solution for `ss-tproxy v4.x`. This can avoid 99% of special cases.
2. Remove these special addresses and reserved addresses from chnroute.ipset, chnroute6.ipset.

**Comment by zfl9** [comment]
After actual testing, I think the first solution is the closest to perfection.

**Comment by xlighting2017** [comment]
hmmm, I was hoping to reduce the dependency of other components, especially dnsmasq;(for its bad performance in searching/parsing long config files)

anyway, thanks for the effort!

**Comment by zfl9** [comment]
If you don't like dnsmasq, you can customize chnroute.ipset yourself. This method is also very simple and effective.
