### ISSUE TITLE
国内DNS返回国外地址, 在可信DNS不可用的状态下的返回逻辑

### ISSUE THREAD

**Issue by weyou** [zfl9/chinadns-ng#81]
如果域名未命中黑白名单, 然后国内的DNS返回了国外地址,  但是这时候可信DNS临时不可用, chinadns-ng现在的是实现是不会返回任何结果. 

这种情况下是否应该返回国内DNS返回的地址比较合理呢? 因为不少情况下, 国内的DNS返回的国外地址也是未受污染的. 能获取到一个地址总比没有强吧?

**Comment by zfl9** [comment]
chinadns-ng不考虑上游dns服务不可用的情况。
