### ISSUE TITLE
在alpine linux上编译出现警告

### ISSUE THREAD

**Issue by windrosecn** [zfl9/chinadns-ng#83]
`
logutils.h:12:16: warning: format '%ld' expects argument of type 'long int', but argument 8 has type 'time_t' {aka 'long long int'} [-Wformat=]
   12 |         printf("\e[1;32m%04d-%02d-%02d %02d:%02d:%02d INF:\e[0m " fmt "\n", \
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
logutils.h:12:16: note: in definition of macro 'LOGINF'
   12 |         printf("\e[1;32m%04d-%02d-%02d %02d:%02d:%02d INF:\e[0m " fmt "\n", \
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
`
alpine 版本是3.13.5
gcc版本： gcc (Alpine 10.2.1_pre1) 10.2.1 20201203

**Comment by zfl9** [comment]
收到

**Comment by zfl9** [comment]
这个警告应该不会影响正常使用，等有时间在一起处理吧。

**Comment by zfl9** [comment]
见最新提交。
