### ISSUE TITLE
docker运行chinadns-ng如何传递自定义参数？比如china-dns,trust-dns

### ISSUE THREAD

**Issue by lcylgs** [zfl9/chinadns-ng#86]
我尝试通过环境变量-e trust-dns，发现并没有生效。
查阅了文档和dockerfile，没找到相关介绍。
另外无法通过docker exec -it chinadns-ng bash进入docker

**Comment by zfl9** [comment]
参数在最后
`docker run -d  --name chinadns-ng  --restart always  --net host  chinadns-ng <args>`

如果要进入shell，需要修改entrypoint，改为/bin/sh
docker文件里面指定的入口点是/app/chinadns-ng
`docker run --rm -it --entrypoint /bin/sh chinadns-ng`

**Comment by lcylgs** [comment]
感谢大佬
