### ISSUE TITLE
docker 运行chinadns-ng 提示[ipset_addr4_is_exists] received an error code from kernel: (-1) Operation not permitted

### ISSUE THREAD

**Issue by lcylgs** [zfl9/chinadns-ng#87]
尝试加了--privileged 参数，还是会报[ipset_addr4_is_exists] received an error code from kernel: (-1) Operation not permitted

**Comment by zfl9** [comment]
应该是运行的用户id不对（我看docker文件里面配置的user是nobody）。docker文件最初不是我添加的，所以没有仔细测试。。

先试试把user改为root：
`docker run -d --name chinadns-ng --restart always --net host --user root chinadns-ng <args>`

**Comment by tzcjh** [comment]
> 应该是运行的用户id不对（我看docker文件里面配置的user是nobody）。docker文件最初不是我添加的，所以没有仔细测试。。
> 
> 先试试把user改为root： `docker run -d --name chinadns-ng --restart always --net host --user root chinadns-ng <args>`

我也遇到了这个问题，user设为root还是不行
