### ISSUE TITLE
手动更新路由列表长时间停留不动

### ISSUE THREAD

**Issue by wangjianpro** [zfl9/chinadns-ng#89]
手动更新路由列表长时间停留不动
![Screenshot_2021-09-10-07-26-24-286_com microsoft emmx](https://user-images.githubusercontent.com/20982614/132775584-6f179614-3a25-4813-80c1-20741f781565.jpg)

**Comment by zfl9** [comment]
第三方bug。去找开发这个openwrt插件的作者看看。
