### ISSUE TITLE
received an error code from kernel: (-2) No such file or directory

### ISSUE THREAD

**Issue by cutemanworking** [zfl9/chinadns-ng#9]
any tips for me to find the root cause?  thanks in advanced!
[ipset_addr4_is_exists] received an error code from kernel: (-2) No such file or directory

**Comment by zfl9** [comment]
You need to import `chnroute.ipset` and `chnroute6.ipset`

**Comment by cattyhouse** [comment]
> any tips for me to find the root cause? thanks in advanced!
> [ipset_addr4_is_exists] received an error code from kernel: (-2) No such file or directory

before running chinadns, run these commands firstly:
```
ipset restore -file chnroute.ipset
ipset restore -file chnroute6.ipset
```
the 2 files are in this repo, just:
git clone https://github.com/zfl9/chinadns-ng

**Comment by cutemanworking** [comment]
many thanks!!!
