### ISSUE TITLE
请问，配置文件保存在哪里？

### ISSUE THREAD

**Issue by hululu1068** [zfl9/chinadns-ng#90]
配置好了之后想查看配置文件，没找到保存位置

![image](https://user-images.githubusercontent.com/68652362/137621873-09cfd0d2-5aff-4c59-b61a-75396b7d5408.png)

**Comment by emacsnt** [comment]
openwrt安装目录
/etc/config/chinadns-ng
/usr/bin/chinadns-ng
/etc/chinadns-ng/chinalist.txt
/etc/chinadns-ng/gfwlist.txt
/etc/init.d/chinadns-ng
/etc/chinadns-ng/chnroute6.txt
/etc/chinadns-ng/chnroute.txt
