### ISSUE TITLE
添加nftables支持

### ISSUE THREAD

**Issue by piledog** [zfl9/chinadns-ng#91]
nftables的目标是替换现有的iptables等框架, 请考虑适配.

**Comment by zfl9** [comment]
暂不考虑

**Comment by Typhonling** [comment]
猜测这个问题导致了openwrt-chinadns-ng在openwrt 22中无法正常使用？openwrt 19没有问题。

**Comment by zfl9** [comment]
不应该吧，现在的版本，只和ipset有关系呀

**Comment by zfl9** [comment]
见 2023.04.01 预发布版本。

**Comment by zfl9** [comment]
见最新版本
