### ISSUE TITLE
domain shown both in chnlist and gfwlist

### ISSUE THREAD

**Issue by tritu** [zfl9/chinadns-ng#94]
Hi,
I'm a little bit confused about the behaviour when a domain shown both in chnlist (whitelist) and gfwlist (blacklist).
It's supposed to be blacklist has higher priority after reading in the README. But why I always got chn IP back?
The set up is simple: chinadns-ng is the upstream of dnsmasq and let's try "pubads.g.doubleclick.net". Here is the log from dnsmasq:
Nov 26 08:11:01 dnsmasq[3506]: 240 192.168.1.42/63631 query[type=65] pubads.g.doubleclick.net from 192.168.1.42
Nov 26 08:11:01 dnsmasq[3506]: 240 192.168.1.42/63631 forwarded pubads.g.doubleclick.net to 127.0.0.1
Nov 26 08:11:01 dnsmasq[3506]: 241 192.168.1.42/63079 query[AAAA] pubads.g.doubleclick.net from 192.168.1.42
Nov 26 08:11:01 dnsmasq[3506]: 241 192.168.1.42/63079 forwarded pubads.g.doubleclick.net to 127.0.0.1
Nov 26 08:11:01 dnsmasq[3506]: 242 192.168.1.42/60725 query[A] pubads.g.doubleclick.net from 192.168.1.42
Nov 26 08:11:01 dnsmasq[3506]: 242 192.168.1.42/60725 forwarded pubads.g.doubleclick.net to 127.0.0.1
Nov 26 08:11:01 dnsmasq[3506]: 242 192.168.1.42/60725 reply pubads.g.doubleclick.net is <CNAME>
Nov 26 08:11:01 dnsmasq[3506]: 242 192.168.1.42/60725 ipset add gfwlist 114.250.67.38 partnerad.l.doubleclick.net
Nov 26 08:11:01 dnsmasq[3506]: 242 192.168.1.42/60725 ipset add gfwlist6 114.250.67.38 partnerad.l.doubleclick.net
Nov 26 08:11:01 dnsmasq[3506]: 242 192.168.1.42/60725 ipset add chnroute 114.250.67.38 partnerad.l.doubleclick.net
Nov 26 08:11:01 dnsmasq[3506]: 242 192.168.1.42/60725 ipset add chnroute6 114.250.67.38 partnerad.l.doubleclick.net
Nov 26 08:11:01 dnsmasq[3506]: 242 192.168.1.42/60725 reply partnerad.l.doubleclick.net is 114.250.67.38
Nov 26 08:11:01 dnsmasq[3506]: 241 192.168.1.42/63079 reply pubads.g.doubleclick.net is <CNAME>
Nov 26 08:11:01 dnsmasq[3506]: 241 192.168.1.42/63079 reply partnerad.l.doubleclick.net is NODATA-IPv6

**Comment by zfl9** [comment]
gfwlist.txt和chnlist.txt发来看一下？

**Comment by zfl9** [comment]
以及chinadns-ng的启动参数

**Comment by tritu** [comment]
OMG! Never mind man. I think that's all because I accidentally add -M option there...
