### ISSUE TITLE
Can I make chinadns-ng return the domestic DNS response in case trusted DNS times out?

### ISSUE THREAD

**Issue by VorontsovIE** [zfl9/chinadns-ng#96]
My trusted DNS sometimes fails, especially if the connection is bad. If the original request is neither in the black list, nor in the white list, even if it does not belong to the "domestic ipset" (i.e. is probably not very good), well, some response is better than no response.  This is, in some sense, almost the same thing as adding all the ip space into the "domestic ipset", but not quite, since in general "trusted" responses are better.

**Comment by zfl9** [comment]
This weekend, maybe a new command line option will be added to handle this situation

**Comment by basncy** [comment]
can we drop A record that does not in the domestic ipset?
We could enable NAT64 in trusted dns server for those v4 only domain.
the advantage is to replace thousands of ipv4 routes with only one NAT64 ipv6 route.

**Comment by zfl9** [comment]
https://github.com/zfl9/chinadns-ng/tree/failover
