### ISSUE TITLE
Drop A record that does not in the domestic ipset

### ISSUE THREAD

**Issue by basncy** [zfl9/chinadns-ng#98]
can we drop A record that does not in the domestic ipset?
We could enable NAT64 in trusted dns server for those v4 only domain.

**Comment by zfl9** [comment]
？没看懂你说的什么问题

**Comment by basncy** [comment]
希望增加这么一个选项:
目标: 对于A查询, 只想保留国内地址.  即只返回--china-dns查询到且匹配--ipset-name4的结果.

**Comment by zfl9** [comment]
现在的处理逻辑不就是这样吗？

**Comment by zfl9** [comment]
你可以指出一下，原来的逻辑是什么，然后哪些点要修改，修改之后的逻辑是什么，方便阅读/对比。

**Comment by basncy** [comment]
原来的:
A query会返回正确结果,不管这结果是什么.
修改点:
A query只返回--ipset-name4里的结果.
应用场景:
所有不在--ipset-name4里的v4地址, 通过NAT64服务, 一条路由搞定. 
dig aaaa twitter.com @2001:4860:4860::6464
