### ISSUE TITLE
docker received an error code from kernel: (-2) No such file or directory

### ISSUE THREAD

**Issue by tzcjh** [zfl9/chinadns-ng#99]
_“
5、received an error code from kernel: (-2) No such file or directory
意思是指定的 ipset 不存在；如果是 [ipset_addr4_is_exists] 函数提示此错误，说明没有导入 chnroute ipset（IPv4）；如果是 [ipset_addr6_is_exists] 函数提示此错误，说明没有导入 chnroute6 ipset（IPv6）。要解决此问题，请导入项目根目录下 chnroute.ipset、chnroute6.ipset 文件。
”_

请问我是用的docker， 出现了这个log，在容器内shell识别不了ipset命令。如何解决？
已经给了privileged=true和user root

**Comment by zfl9** [comment]
在容器内shell识别不了ipset命令
具体报错是什么？
command not found?
如果是这个，那就在容器内安装一下ipset就好了

**Comment by tzcjh** [comment]
感谢回复
报错是“sh: ipset: not found”
求教sh下的ipset如何安装。。。系统是armbian
apt-get dpkg都是not found。。。

**Comment by zfl9** [comment]
那你要搜索一下armbian如何安装ipset了。

**Comment by tzcjh** [comment]
好的谢谢！
